# Required Environment Variables to set:
# * DB_DEV_VOL_PATH
# * DB_TEST_VOL_PATH
# * DB_PATH_VOL_PATH
# 
# More details for configuring the environment variables:
# * ./docker_env/moebooru-app.env.example
# * ./docker_env/moebooru-db.env.example
#
# Example Usage: docker compose --env-file .docker/moebooru-app.dev.env.example --env-file .docker/moebooru-db.env.example -f docker-compose.yml -f .docker/docker-compose.dev.yml up -d
#

version: '3'
services:
  moebooru-db:
    image: postgres:alpine
    container_name: moebooru-db-${RAILS_ENV}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: moebooru-${RAILS_ENV}
    restart: unless-stopped

  moebooru-app:
    platform: linux/${ARCHITECTURE}
    image: moebooru:${RAILS_ENV}
    container_name: moebooru-app-${RAILS_ENV}
    build:
      dockerfile: "./Dockerfile"
      target: moebooru-${RAILS_ENV}
    environment:
      - RAILS_ENV
      - DB_USERNAME
      - DB_PASSWORD
      # Additional environment variables that can be set
      # - MB_DATABASE_URL # This must be set accordingly. Uncommenting this and not setting will cause the container to not work.
      # - MB_MEMCACHE_SERVERS
      # - MB_PIWIK_HOST
      # - MB_PIWIK_ID
      # - MB_THREADS
    ports:
      - ${HOST_PORT}:3000
    restart: unless-stopped
