# Required Environment Variables to set:
# * DB_DEV_VOL_PATH
# * DB_TEST_VOL_PATH
# * DB_PATH_VOL_PATH
# 
# More details for configuring the environment variables:
# * ./docker_env/moebooru-app.env.example
# * ./docker_env/moebooru-db.env.example
#
# Example Usage: docker compose --env-file .docker-env/moebooru-app.env.example --env-file .docker-env/moebooru-db.env.example up -d 
#

version: '3'
services:
  moebooru-dev:
    image: postgres:alpine
    container_name: moebooru-dev
    volumes:
      - ${DB_DEV_VOL_PATH}:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imouto
      POSTGRES_DB: moebooru-dev
    restart: unless-stopped

  moebooru-test:
    image: postgres:alpine
    container_name: moebooru-test
    volumes:
      - ${DB_TEST_VOL_PATH}:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imouto
      POSTGRES_DB: moebooru-test
    restart: unless-stopped

  moebooru-prod:
    image: postgres:alpine
    container_name: moebooru-prod
    volumes:
      - ${DB_PROD_VOL_PATH}:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imouto
      POSTGRES_DB: moebooru
    restart: unless-stopped

  moebooru-app:
    platform: linux/${ARCHITECTURE:-x86_64}
    image: moebooru:latest
    container_name: moebooru-app
    command: >
      "${COMMAND_PARAMS:-echo ''} && npm run build && bundle exec rails server -b ${APP_LISTEN_IP:-'0.0.0.0'}"
    build:
      dockerfile: "./Dockerfile"
    environment:
      - RAILS_ENV
      # Additional environment variables that can be set
      # - MB_DATABASE_URL # This must be set accordingly. Uncommenting this and not setting will cause the container to not work.
      # - MB_MEMCACHE_SERVERS
      # - MB_PIWIK_HOST
      # - MB_PIWIK_ID
      # - MB_THREADS
    ports:
      - ${HOST_PORT:-8080}:3000
    restart: unless-stopped
