source 'http://rubygems.org'

gem 'rails', '~> 2.3.0'
gem 'pg'
gem 'html5'
gem 'diff-lcs'
gem 'gchartrb'
gem 'json'
gem 'hpricot'
gem 'memcache-client'
gem 'mime-types'
gem 'unicorn'
gem 'redhillonrails_core'
gem 'geoip'
gem 'repeated_auto_complete'
gem 'exception_notification', '~> 2.3.0'
gem 'will_paginate', '~> 2.3.16'
