# Be sure to restart your server when you modify this file.

# sourcemap for css and non-esbuild javascripts
Rails.application.config.assets.debug = true

# Version of your assets, change this if you want to expire all your assets.
# set to nil so the hash is predictable (for sourcemap generated by esbuild)
Rails.application.config.assets.version = nil

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path

# Add Yarn node_modules folder to the asset load path.
Rails.application.config.assets.paths << Rails.root.join('node_modules')

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
# Rails.application.config.assets.precompile += %w( admin.js admin.css )
