import 'src/globals'
import 'src/globals-jquery'

import 'src/cookie'
import 'src/compat.jquery'
import 'src/forum'
import 'src/notice'

import 'src/moebooru'

import 'src/init.autocomplete'
import 'src/init.cookie'
import 'src/post'
import 'src/vote'

import 'src/legacy/browser-img-pool'
import 'src/legacy/browser-post-loading'
import 'src/legacy/browser-thumb-view'
import 'src/legacy/browser-url-hash'
import 'src/legacy/browser-view'
import 'src/legacy/common'
import 'src/legacy/debug-window'
import 'src/legacy/history'
import 'src/legacy/inline_image'
import 'src/legacy/notes'
import 'src/legacy/pool'
import 'src/legacy/post'
import 'src/legacy/post-frame-editor'
import 'src/legacy/post-upload-form'
import 'src/legacy/post_mode_menu'
import 'src/legacy/post_tag_history'
import 'src/legacy/preload'
import 'src/legacy/similar-thumbnailing'
import 'src/legacy/tag_completion'
import 'src/legacy/touchscreen-web-app-helpers'
import 'src/legacy/user'

import 'src/boot'
