import 'src/globals'
import 'src/globals-jquery'

import 'src/prefix'
import 'src/cookie'
import 'src/compat.jquery'
import 'src/i18n_scopify'
import 'src/dmail'
import 'src/favorite'
import 'src/forum'
import 'src/user_record'
import 'src/notice'

import 'src/utils/fixed-encode-uri-component'

import 'src/moebooru'
import 'src/moebooru/post_show_tabs'

import 'src/_classes/timeago'

import 'src/main_menu_dropdown'
import 'src/comment'
import 'src/init.autocomplete'
import 'src/init.cookie'
import 'src/init.menu'
import 'src/init.news'
import 'src/init.user_record'
import 'src/menu'
import 'src/menu_drag_drop'
import 'src/post'
import 'src/urls'
import 'src/vote'

import 'src/legacy/browser-img-pool'
import 'src/legacy/browser-post-loading'
import 'src/legacy/browser-thumb-view'
import 'src/legacy/browser-url-hash'
import 'src/legacy/browser-view'
import 'src/legacy/common'
import 'src/legacy/debug-window'
import 'src/legacy/history'
import 'src/legacy/inline_image'
import 'src/legacy/notes'
import 'src/legacy/pool'
import 'src/legacy/post'
import 'src/legacy/post-frame-editor'
import 'src/legacy/post-upload-form'
import 'src/legacy/post_mode_menu'
import 'src/legacy/post_tag_history'
import 'src/legacy/preload'
import 'src/legacy/similar-thumbnailing'
import 'src/legacy/tag_completion'
import 'src/legacy/touchscreen-web-app-helpers'
import 'src/legacy/user'

import 'src/boot'
