#!/usr/local/bin/ruby
if ARGV.empty?
  $stderr.puts "Usage: profiler 'Person.expensive_method(10)' [times]"
  exit(1)
end

# Keep the expensive require out of the profile.
$stderr.puts 'Loading Rails...'
require File.dirname(__FILE__) + '/../config/environment'

# Define a method to profile.
if ARGV[1] and ARGV[1].to_i > 1
  eval "def profile_me() #{ARGV[1]}.times { #{ARGV[0]} } end"
else
  eval "def profile_me() #{ARGV[0]} end"
end

# Use the ruby-prof extension if available.  Fall back to stdlib profiler.
begin
  require 'ruby-prof'
rescue LoadError
  $stderr.puts 'Using the standard Ruby profiler.'
  Profiler__.start_profile
  profile_me
  Profiler__.stop_profile
  Profiler__.print_profile($stderr)
  return 0
end

$stderr.puts 'Using the ruby-prof extension.'
RubyProf::measure_mode = RubyProf::WALL_TIME
RubyProf.start
profile_me
results = RubyProf.stop
printer = RubyProf::FlatPrinter.new(results)
printer.print(STDERR)
