#!/bin/sh

. /etc/lsb-release
echo "deb http://apt.postgresql.org/pub/repos/apt/ ${DISTRIB_CODENAME}-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list > /dev/null
curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y postgresql-12
sudo pg_ctlcluster 12 main start

mkdir -p public/data

cat <<EOF > config/database.yml
test:
  adapter: postgresql
  username: postgres
  database: moebooru_test
EOF

cat <<EOF > config/local_config.rb
CONFIG["server_host"] = "localhost"
CONFIG["admin_contact"] = "webmaster@#{CONFIG["server_host"]}"
CONFIG["memcache_servers"] = ["127.0.0.1:11211"]
EOF

bundle exec rails db:create
