import CheckAll from './_classes/check_all'
import Menu from './_classes/menu'
import MenuDragDrop from './_classes/menu_drag_drop'
import MenuDropdown from './_classes/menu_dropdown'
import NewsTicker from './_classes/news_ticker'
import PostShowTabs from './_classes/post_show_tabs'
import RelatedTags from './_classes/related_tags'
import Timeago from './_classes/timeago'
import UserRecord from './_classes/user_record'

window.checkAll = new CheckAll
window.menu = new Menu
window.menuDragDrop = new MenuDragDrop
window.menuDropdown = new MenuDropdown
window.newsTicker = new NewsTicker
window.postShowTabs = new PostShowTabs
window.relatedTags = new RelatedTags
window.timeago = new Timeago
window.userRecord = new UserRecord
