import CheckAll from './classes/check_all'
import Comment from './comment'
import Dmail from './classes/dmail'
import ImageCrop from './classes/image_crop'
import Favorite from './classes/favorite'
import Menu from './classes/menu'
import MenuDragDrop from './classes/menu_drag_drop'
import MenuDropdown from './classes/menu_dropdown'
import NewsTicker from './classes/news_ticker'
import PostShowTabs from './classes/post_show_tabs'
import RelatedTags from './classes/related_tags'
import Timeago from './classes/timeago'
import UserRecord from './classes/user_record'

window.imageCrop = new ImageCrop
window.checkAll = new CheckAll
window.comment = new Comment
window.dmail = new Dmail
window.favorite = new Favorite
window.menu = new Menu
window.menuDragDrop = new MenuDragDrop
window.menuDropdown = new MenuDropdown
window.newsTicker = new NewsTicker
window.postShowTabs = new PostShowTabs
window.relatedTags = new RelatedTags
window.timeago = new Timeago
window.userRecord = new UserRecord
