// Generated by CoffeeScript 2.7.0
let $, CheckAll;

$ = jQuery;

export default CheckAll = class CheckAll {
  constructor () {
    this._checkAll = this._checkAll.bind(this);
    this._target = this._target.bind(this);
    $(document).on('click', '.js-check_all', this._checkAll);
  }

  _checkAll (e) {
    e.preventDefault();
    return this._target(e.currentTarget.getAttribute('data-target')).attr('checked', true);
  }

  _target (name) {
    return $(`.js-check_all-target[data-target='${name}']`);
  }
};
