// Generated by CoffeeScript 2.7.0
var $, Comment, t;

$ = jQuery;

t = I18n.scopify('js.comment');

export default Comment = class Comment {
  constructor() {
    $(document).on('click', '.js-comment--destroy', this.destroy);
    $(document).on('click', '.js-comment--flag', this.flag);
    $(document).on('click', '.js-comment--quote', this.quote);
    $(document).on('click', '.js-comment--show-reply-form', this.showReplyForm);
    $(document).on('click', '.js-comment--spoiler', this.spoiler);
  }

  spoiler(e) {
    return $(e.currentTarget).hide().next('.spoilertext').show();
  }

  flag(e) {
    var id;
    e.preventDefault();
    if (!confirm(t('.flag_ask'))) {
      return;
    }
    id = e.currentTarget.dataset.commentId;
    notice(t('.flag_process'));
    return $.ajax({
      url: Moebooru.path('/comment/mark_as_spam.json'),
      type: 'post',
      data: {
        id: id,
        comment: {
          is_spam: 1
        }
      }
    }).done(function(resp) {
      return notice(t('.flag_notice'));
    }).fail(function(resp) {
      resp = $.parseJSON(resp.responseText);
      return notice(`${t('js.error')}${resp.reason}`);
    });
  }

  quote(e) {
    var id;
    e.preventDefault();
    id = e.currentTarget.dataset.commentId;
    return $.ajax({
      url: Moebooru.path('/comment/show.json'),
      type: 'get',
      data: {
        id: id
      }
    }).done(function(resp) {
      var body, replyBox, strippedBody;
      strippedBody = resp.body.replace(/\[quote\](?:.|\n|\r)+?\[\/quote\](?:\r\n|\r|\n)*/gm, '');
      body = `[quote]${resp.creator} ${t('js.said')}\n${strippedBody}\n[/quote]\n\n`;
      $(`#reply-${resp.post_id}`).show();
      $(`#respond-link-${resp.post_id}`).hide();
      replyBox = $(`#reply-text-${resp.post_id}`);
      replyBox.val(`${replyBox.val()}${body}`);
      return replyBox.focus();
    }).fail(function() {
      return notice(t('.quote_error'));
    });
  }

  destroy(e) {
    var id;
    e.preventDefault();
    if (!confirm(t('.delete_ask'))) {
      return;
    }
    id = e.currentTarget.dataset.commentId;
    return $.ajax({
      url: Moebooru.path('/comment/destroy.json'),
      type: 'post',
      data: {
        id: id
      }
    }).done(function(resp) {
      return document.location.reload();
    }).fail(function(resp) {
      resp = $.parseJSON(resp.responseText);
      return notice(`${t('.delete_error')}${resp.reason}`);
    });
  }

  showReplyForm(e) {
    var postId;
    e.preventDefault();
    postId = e.currentTarget.dataset.commentPostId;
    $(`#respond-link-${postId}`).hide();
    return $(`#reply-${postId}`).show().find('textarea').focus();
  }

};
