// Generated by CoffeeScript 2.7.0
import DragElement from 'src/classes/drag_element';

import {
  applyDrag,
  createDragBox
} from 'src/utils/drag_box';

import {
  frameDimensionsFromImage,
  frameDimensionsToImage
} from 'src/utils/frame_math';

let CornerDragger;

// Create the specified corner dragger.
export default CornerDragger = class CornerDragger {
  constructor (container, part, options) {
    let box, dragElementOptions, frameBox;
    this.container = container;
    this.part = part;
    this.options = options;
    box = this.container.querySelector('.frame-editor-popup-div');
    // Create a div inside each .frame-editor-popup-div floating on top of the image
    // to show the border of the frame.
    frameBox = document.createElement('div');
    frameBox.className = 'frame-editor-frame-box';
    createDragBox(frameBox);
    box.appendChild(frameBox);
    dragElementOptions = {
      snap_pixels: 0,
      ondown: (e) => {
        let element, frame, post;
        element = document.elementFromPoint(e.x, e.y);
        // If we clicked on a drag handle, use that handle.  Otherwise, choose the corner drag
        // handle for the corner we're in.
        if (element.classList.contains('frame-box-handle')) {
          this.dragging_mode = element._frameDragCursor;
        } else if (this.part === '.frame-editor-nw') {
          this.dragging_mode = 'nw-resize';
        } else if (this.part === '.frame-editor-ne') {
          this.dragging_mode = 'ne-resize';
        } else if (this.part === '.frame-editor-sw') {
          this.dragging_mode = 'sw-resize';
        } else if (this.part === '.frame-editor-se') {
          this.dragging_mode = 'se-resize';
        }
        post = Post.posts.get(this.post_id);
        frame = post.frames_pending[this.post_frame];
        this.dragging_anchor = frameDimensionsToImage(frame, this.image_dimensions, post);
        // When dragging a handle, hide the cursor to get it out of the way.
        this.dragger.overriden_drag_class = this.dragging_mode === 'move' ? null : 'hide-cursor';
        // Stop propagation of the event, so any other draggers in the chain don't start.  In
        // particular, when we're dragging inside the image, we need to stop WindowDragElementAbsolute.
        // Only do this if we're actually dragging, not if we aborted due to this.drag_to_create.
        e.latest_event.stopPropagation();
      },
      ondrag: (e) => {
        let base, dims, post, source_dims;
        post = Post.posts.get(this.post_id);
        // Invert the motion, since we're dragging the image around underneith the
        // crop frame instead of dragging the crop frame around.
        dims = applyDrag(this.dragging_mode, -e.aX, -e.aY, this.image_dimensions, this.dragging_anchor);
        // Scale the changed dimensions back to the source resolution and apply them
        // to the frame.
        source_dims = frameDimensionsFromImage(dims, this.image_dimensions, post);
        post.frames_pending[this.post_frame] = source_dims;
        if (typeof (base = this.options).onUpdate === 'function') {
          base.onUpdate();
        }
      }
    };
    this.dragger = new DragElement(box, dragElementOptions);
    this.update();
  }

  // Set the post to show in the corner dragger.  If post_id is null, clear any displayed
  // post.

  // When the post ID is set, the post frame is always cleared.
  set_post_id (post_id) {
    let img, post, url;
    this.post_id = post_id;
    this.post_frame = null;
    url = null;
    img = this.container.querySelector('img');
    if (post_id != null) {
      post = Post.posts.get(this.post_id);
      this.image_dimensions = {
        width: post.jpeg_width,
        height: post.jpeg_height
      };
      url = post.jpeg_url;
      img.width = this.image_dimensions.width;
      img.height = this.image_dimensions.height;
    }
    // Don't change the image if it's already set; it causes Chrome to reprocess
    // the image.
    if (img.src !== url) {
      img.src = url != null ? url : Vars.blankImage;
      if (url != null) {
        // Decoding in Chrome takes long enough to be visible.  Hourglass the cursor while it runs.
        document.documentElement.classList.add('hourglass');
        window.setTimeout(function () {
          return document.documentElement.classList.remove('hourglass');
        });
      }
    }
    this.update();
  }

  set_post_frame (post_frame) {
    this.post_frame = post_frame;
    this.update();
  }

  update () {
    let box, dims, div, frame, img, left, offset_height, offset_width, post, top;
    if ((this.post_id == null) || (this.post_frame == null)) {
      return;
    }
    post = Post.posts.get(this.post_id);
    frame = post.frames_pending[this.post_frame];
    dims = frameDimensionsToImage(frame, this.image_dimensions, post);
    div = this.container;
    // Update the drag/frame box.
    box = this.container.querySelector('.frame-editor-frame-box');
    box.style.left = dims.left + 'px';
    box.style.top = dims.top + 'px';
    box.style.width = dims.width + 'px';
    box.style.height = dims.height + 'px';
    // Recenter the corner box.
    top = dims.top;
    left = dims.left;
    if (this.part === '.frame-editor-ne' || this.part === '.frame-editor-se') {
      left += dims.width;
    }
    if (this.part === '.frame-editor-sw' || this.part === '.frame-editor-se') {
      top += dims.height;
    }
    offset_height = div.offsetHeight / 2;
    offset_width = div.offsetWidth / 2;
    /*
    if(this.part == ".frame-editor-nw" || this.part == ".frame-editor-ne") offset_height -= div.offsetHeight/4;
    if(this.part == ".frame-editor-sw" || this.part == ".frame-editor-se") offset_height += div.offsetHeight/4;
    if(this.part == ".frame-editor-nw" || this.part == ".frame-editor-sw") offset_width -= div.offsetWidth/4;
    if(this.part == ".frame-editor-ne" || this.part == ".frame-editor-se") offset_width += div.offsetWidth/4;
    */
    left -= offset_width;
    top -= offset_height;
    // If the region is small enough that we don't have enough to fill the corner
    // frames, push the frames inward so they line up.
    if (this.part === '.frame-editor-nw' || this.part === '.frame-editor-sw') {
      left = Math.min(left, dims.left + dims.width / 2 - div.offsetWidth);
    }
    if (this.part === '.frame-editor-ne' || this.part === '.frame-editor-se') {
      left = Math.max(left, dims.left + dims.width / 2);
    }
    if (this.part === '.frame-editor-nw' || this.part === '.frame-editor-ne') {
      top = Math.min(top, dims.top + dims.height / 2 - div.offsetHeight);
    }
    if (this.part === '.frame-editor-sw' || this.part === '.frame-editor-se') {
      top = Math.max(top, dims.top + dims.height / 2);
    }
    img = this.container.querySelector('.frame-editor-popup-div');
    img.style.marginTop = -top + 'px';
    img.style.marginLeft = -left + 'px';
  }
};
