// Generated by CoffeeScript 2.7.0
let $, Dmail, t;

$ = jQuery;

t = I18n.scopify('js.dmail');

export default Dmail = class Dmail {
  constructor () {
    $(document).on('click', '.js-dmail--respond', this.respond);
    $(document).on('click', '.js-dmail--expand', this.expand);
  }

  expand (e) {
    let id, parentId;
    e.preventDefault();
    parentId = e.currentTarget.dataset.dmailParentId;
    id = e.currentTarget.dataset.dmailId;
    notice(t('.fetch_prev_msg'));
    return $.ajax({
      url: Moebooru.path('/dmail/show_previous_messages'),
      type: 'get',
      data: {
        id,
        parent_id: parentId
      }
    }).done(function (data) {
      $('#previous-messages').html(data);
      $('#previous-messages').show();
      return notice(t('.prev_msg_loaded'));
    });
  }

  respond (e) {
    let strippedBody, to;
    e.preventDefault();
    to = e.currentTarget.dataset.dmailName;
    $('#dmail_to_name').val(to);
    strippedBody = $('#dmail_body').val().replace(/\[quote\](?:.|\n)+?\[\/quote\]\n*/gm, '');
    $('#dmail_body').val(`[quote]You said:\n${strippedBody}\n[/quote]\n\n`);
    return $('#response').show();
  }
};
