// Generated by CoffeeScript 2.7.0
var DragElement;

import {
  isWebkit
} from 'src/utils/browser';

// When element is dragged, the document moves around it.  If scroll_element is true, the
// element should be positioned (eg. position: absolute), and the element itself will be
// scrolled.
export default DragElement = class DragElement {
  constructor(element, options) {
    this.move_timer_update = this.move_timer_update.bind(this);
    this.mousemove_event = this.mousemove_event.bind(this);
    this.touchmove_event = this.touchmove_event.bind(this);
    this.mousedown_event = this.mousedown_event.bind(this);
    this.touchstart_event = this.touchstart_event.bind(this);
    this.pagehide_event = this.pagehide_event.bind(this);
    this.touchend_event = this.touchend_event.bind(this);
    this.mouseup_event = this.mouseup_event.bind(this);
    this.click_event = this.click_event.bind(this);
    this.dragstart_event = this.dragstart_event.bind(this);
    this.selectstart_event = this.selectstart_event.bind(this);
    $(document.body).addClassName('not-dragging');
    this.options = options || {};
    if (this.options.snap_pixels == null) {
      this.options.snap_pixels = 10;
    }
    this.ignore_mouse_events_until = null;
    this.element = element;
    this.dragging = false;
    this.drag_handlers = [];
    this.handlers = [];
    if (!options.no_mouse) {
      this.handlers.push(element.on('mousedown', this.mousedown_event));
      this.handlers.push(element.on('dragstart', this.dragstart_event));
    }
    if (!options.no_touch) {
      this.handlers.push(element.on('touchstart', this.touchstart_event));
      this.handlers.push(element.on('touchmove', this.touchmove_event));
    }
    if (!isWebkit) {
      this.handlers.push(element.on('click', this.click_event));
    }
    return;
  }

  destroy() {
    this.stop_dragging(null, true);
    this.handlers.each(function(h) {
      h.stop();
    });
    this.handlers = [];
  }

  move_timer_update() {
    var anchored_x, anchored_y, last_event_params, relative_x, relative_y, x, y;
    if (!this.options.ondrag) {
      return;
    }
    if (this.last_event_params == null) {
      return;
    }
    last_event_params = this.last_event_params;
    this.last_event_params = null;
    x = last_event_params.x;
    y = last_event_params.y;
    anchored_x = x - this.anchor_x;
    anchored_y = y - this.anchor_y;
    relative_x = x - this.last_x;
    relative_y = y - this.last_y;
    this.last_x = x;
    this.last_y = y;
    if (this.options.ondrag) {
      this.options.ondrag({
        dragger: this,
        x: x,
        y: y,
        aX: anchored_x,
        aY: anchored_y,
        dX: relative_x,
        dY: relative_y,
        latest_event: last_event_params.event
      });
    }
  }

  mousemove_event(event) {
    var scrollLeft, scrollTop, x, y;
    event.stop();
    scrollLeft = window.pageXOffset || document.documentElement.scrollLeft || document.body.scrollLeft;
    scrollTop = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop;
    x = event.pointerX() - scrollLeft;
    y = event.pointerY() - scrollTop;
    this.handle_move_event(event, x, y);
  }

  touchmove_event(event) {
    var i, t, touch, x, y;
    // Ignore touches other than the one we started with.
    touch = null;
    i = 0;
    while (i < event.changedTouches.length) {
      t = event.changedTouches[i];
      if (t.identifier === this.dragging_touch_identifier) {
        touch = t;
        break;
      }
      ++i;
    }
    if (touch == null) {
      return;
    }
    event.preventDefault();
    if (!window.navigator.standalone && touch.pageY > window.innerHeight - 10) {
      console.debug('Dragged off the bottom');
      this.stop_dragging(event, true);
      return;
    }
    x = touch.pageX;
    y = touch.pageY;
    this.handle_move_event(event, x, y);
  }

  handle_move_event(event, x, y) {
    var distance, snap_pixels;
    if (!this.dragging) {
      return;
    }
    if (!this.dragged) {
      distance = (x - this.anchor_x) ** 2 + (y - this.anchor_y) ** 2;
      snap_pixels = this.options.snap_pixels;
      snap_pixels *= snap_pixels;
      if (distance < snap_pixels) {
        return;
      }
    }
    if (!this.dragged) {
      if (this.options.onstartdrag) {
        // Call the onstartdrag callback.  If it returns true, cancel the drag.
        if (this.options.onstartdrag({
          handler: this,
          latest_event: event
        })) {
          this.dragging = false;
          return;
        }
      }
      this.dragged = true;
      $(document.body).addClassName(this.overriden_drag_class || 'dragging');
      $(document.body).removeClassName('not-dragging');
    }
    this.last_event_params = {
      x: x,
      y: y,
      event: event
    };
    this.move_timer_update();
  }

  mousedown_event(event) {
    var now, scrollLeft, scrollTop, x, y;
    if (!event.isLeftClick()) {
      return;
    }
    // Check if we're temporarily ignoring mouse events.
    if (this.ignore_mouse_events_until != null) {
      now = (new Date()).valueOf();
      if (now < this.ignore_mouse_events_until) {
        return;
      }
      this.ignore_mouse_events_until = null;
    }
    scrollLeft = window.pageXOffset || document.documentElement.scrollLeft || document.body.scrollLeft;
    scrollTop = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop;
    x = event.pointerX() - scrollLeft;
    y = event.pointerY() - scrollTop;
    this.start_dragging(event, false, x, y, 0);
  }

  touchstart_event(event) {
    var i, t, touch, x, y;
    // If we have multiple touches, find the first one that actually refers to us.
    touch = null;
    i = 0;
    while (i < event.changedTouches.length) {
      t = event.changedTouches[i];
      if (!this.element.contains(t.target)) {
        ++i;
        continue;
      }
      touch = t;
      break;
      ++i;
    }
    if (touch == null) {
      return;
    }
    x = touch.pageX;
    y = touch.pageY;
    this.start_dragging(event, true, x, y, touch.identifier);
  }

  start_dragging(event, touch, x, y, touch_identifier) {
    if (this.dragging_touch_identifier != null) {
      return;
    }
    /* If we've been started with a touch event, only listen for touch events.  If we've
     * been started with a mouse event, only listen for mouse events.  We may receive
     * both sets of events, and the anchor coordinates for the two may not be compatible.
        */
    this.drag_handlers.push(document.on('selectstart', this.selectstart_event));
    this.drag_handlers.push(Element.on(window, 'pagehide', this.pagehide_event));
    if (touch) {
      this.drag_handlers.push(document.on('touchend', this.touchend_event));
      this.drag_handlers.push(document.on('touchcancel', this.touchend_event));
      this.drag_handlers.push(document.on('touchmove', this.touchmove_event));
    } else {
      this.drag_handlers.push(document.on('mouseup', this.mouseup_event));
      this.drag_handlers.push(document.on('mousemove', this.mousemove_event));
    }
    this.dragging = true;
    this.dragged = false;
    this.dragging_by_touch = touch;
    this.dragging_touch_identifier = touch_identifier;
    this.anchor_x = x;
    this.anchor_y = y;
    this.last_x = this.anchor_x;
    this.last_y = this.anchor_y;
    if (this.options.ondown) {
      this.options.ondown({
        dragger: this,
        x: x,
        y: y,
        latest_event: event
      });
    }
  }

  pagehide_event(event) {
    this.stop_dragging(event, true);
  }

  touchend_event(event) {
    var i, t;
    // If our touch was released, stop the drag.
    i = 0;
    while (i < event.changedTouches.length) {
      t = event.changedTouches[i];
      if (t.identifier === this.dragging_touch_identifier) {
        this.stop_dragging(event, event.type === 'touchcancel');
        // Work around a bug on iPhone.  The mousedown and mouseup events are sent after
        // the touch is released, instead of when they should be (immediately following
        // touchstart and touchend).  This means we'll process each touch as a touch,
        // then immediately after as a mouse press, and fire ondown/onup events for each.

        // We can't simply ignore mouse presses if touch events are supported; some devices
        // will support both touches and mice and both types of events will always need to
        // be handled.

        // After a touch is released, ignore all mouse presses for a little while.  It's
        // unlikely that the user will touch an element, then immediately click it.
        this.ignore_mouse_events_until = (new Date()).valueOf() + 500;
        return;
      }
      ++i;
    }
  }

  mouseup_event(event) {
    if (!event.isLeftClick()) {
      return;
    }
    this.stop_dragging(event, false);
  }

  // If cancelling is true, we're stopping for a reason other than an explicit mouse/touch
  // release.
  stop_dragging(event, cancelling) {
    if (this.dragging) {
      this.dragging = false;
      $(document.body).removeClassName(this.overriden_drag_class || 'dragging');
      $(document.body).addClassName('not-dragging');
      if (this.options.onenddrag) {
        this.options.onenddrag(this);
      }
    }
    this.drag_handlers.each(function(h) {
      h.stop();
    });
    this.drag_handlers = [];
    this.dragging_touch_identifier = null;
    if (this.options.onup) {
      this.options.onup({
        dragger: this,
        latest_event: event,
        cancelling: cancelling
      });
    }
  }

  click_event(event) {
    // If this click was part of a drag, cancel the click.
    if (this.dragged) {
      event.stop();
    }
    this.dragged = false;
  }

  dragstart_event(event) {
    event.preventDefault();
  }

  selectstart_event(event) {
    // We need to stop selectstart to prevent drag selection in Chrome.  However, we need
    // to work around a bug: if we stop the event of an INPUT element, it'll prevent focusing
    // on that element entirely.  We shouldn't prevent selecting the text in the input box,
    // either.
    if (event.target.tagName !== 'INPUT') {
      event.stop();
    }
  }

};
