// Generated by CoffeeScript 2.7.0
var $, Favorite, userLink, usersLinks;

$ = jQuery;

userLink = function(id, name) {
  return `<a href='${Moebooru.path(`/user/show/${id}`)}'>${name}</a>`;
};

usersLinks = function(users) {
  return users.map(function(user) {
    return userLink(user.id, user.name);
  }).join(', ');
};

export default Favorite = class Favorite {
  constructor() {
    this.onShowMoreFavoritedBy = this.onShowMoreFavoritedBy.bind(this);
    $(document).on('click', '.js-favorite--show-more', this.onShowMoreFavoritedBy);
  }

  linkToUsers(users) {
    var html;
    if (users == null) {
      users = [];
    }
    if (users.length === 0) {
      return I18n.t('js.noone');
    }
    html = usersLinks(users.slice(0, 7));
    if (users.length > 6) {
      html += `<span id='remaining-favs' style='display: none;'>, ${usersLinks(users.slice(6))}</span>`;
      html += ` <span>(<a href='#' class='js-favorite--show-more'>${users.length - 6} more</a>)</span>`;
    }
    return html;
  }

  onShowMoreFavoritedBy(e) {
    e.preventDefault();
    $(e.target).closest('span').hide();
    return $('#remaining-favs').show();
  }

};
