// Generated by CoffeeScript 2.7.0
import DragElement from 'src/classes/drag_element';

import {
  isWebkit
} from 'src/utils/browser';

import {
  applyDrag,
  createDragBox
} from 'src/utils/drag_box';

import {
  frameDimensionsFromImage,
  frameDimensionsToImage
} from 'src/utils/frame_math';

import {
  clamp
} from 'src/utils/math';

import CornerDragger from './corner_dragger';

let $, FrameEditor;

$ = jQuery;

export default FrameEditor = class FrameEditor {
  constructor (container, image_container, popup_container, options) {
    let $container, div;
    this.container = container;
    this.image_container = image_container;
    this.popup_container = popup_container;
    this.options = options;
    this.show_corner_drag = true;
    this.image_frames = [];
    // Event handlers which are set only while the tag editor is open:
    this.open_handlers = [];
    // Set up the four parts of the corner dragger.
    this.corner_draggers = ['.frame-editor-nw', '.frame-editor-ne', '.frame-editor-sw', '.frame-editor-se'].map((part) => {
      let cornerDraggerOptions, target;
      target = this.popup_container.querySelector(part);
      cornerDraggerOptions = {
        onUpdate: () => {
          this.update_frame_in_list(this.editing_frame);
          this.update_image_frame(this.editing_frame);
        }
      };
      return new CornerDragger(target, part, cornerDraggerOptions);
    });
    // Create the main frame.  This sits on top of the image, receives mouse events and
    // holds the individual frames.
    div = document.createElement('div');
    div.className = 'frame-editor-main-frame';
    div.style.position = 'absolute';
    div.style.left = '0';
    div.style.top = '0';
    div.style.display = 'none';
    this.image_container.appendChild(div);
    this.main_frame = div;
    $container = $(this.container);
    // Frame editor buttons:
    $container.find('.frame-editor-add').on('click', (e) => {
      e.preventDefault();
      this.add_frame();
    });
    // Buttons in the frame table:
    $container.on('click', '.frame-label', (e) => {
      let frame_idx;
      e.preventDefault();
      frame_idx = e.currentTarget.closest('.frame-row').frame_idx;
      this.focus(frame_idx);
    });
    $container.on('click', '.frame-delete', (e) => {
      let frame_idx;
      e.preventDefault();
      frame_idx = e.currentTarget.closest('.frame-row').frame_idx;
      this.delete_frame(frame_idx);
    });
    $container.on('click', '.frame-up', (e) => {
      let frame_idx;
      e.preventDefault();
      frame_idx = e.currentTarget.closest('.frame-row').frame_idx;
      this.move_frame(frame_idx, frame_idx - 1);
    });
    $container.on('click', '.frame-down', (e) => {
      let frame_idx;
      e.preventDefault();
      frame_idx = e.currentTarget.closest('.frame-row').frame_idx;
      this.move_frame(frame_idx, frame_idx + 1);
    });
    $container.find('table').on('change', () => {
      this.form_data_changed();
    });
  }

  move_frame (frame_idx, frame_idx_target) {
    let editing_frame, frame, post;
    post = Post.posts.get(this.post_id);
    frame_idx_target = clamp(frame_idx_target, 0, post.frames_pending.length - 1);
    if (frame_idx === frame_idx_target) {
      return;
    }
    frame = post.frames_pending[frame_idx];
    post.frames_pending.splice(frame_idx, 1);
    post.frames_pending.splice(frame_idx_target, 0, frame);
    this.repopulate_table();
    // Reset the focus.  If the item that was moved was focused, focus on it in
    // its new position.
    editing_frame = this.editing_frame === frame_idx ? frame_idx_target : this.editing_frame;
    this.editing_frame = null;
    this.focus(editing_frame);
  }

  form_data_changed () {
    let _frame, i, j, len, post, ref;
    post = Post.posts.get(this.post_id);
    ref = post.frames_pending;
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      _frame = ref[i];
      this.update_frame_from_list(i);
    }
    this.update();
  }

  set_drag_to_create (enable) {
    this.drag_to_create = enable;
  }

  update_show_corner_drag () {
    let cornerDragger, j, len, ref, shown;
    shown = (this.post_id != null) && (this.editing_frame != null) && this.show_corner_drag;
    if (isWebkit) {
      // Work around a WebKit (maybe just a Chrome) issue.  Images are downloaded immediately, but
      // they're only decompressed the first time they're actually painted on screen.  This happens
      // late, after all style is applied: hiding with display: none, visibility: hidden or even
      // opacity: 0 causes the image to not be decoded until it's displayed, which causes a huge
      // UI hitch the first time the user drags a box.  Work around this by setting opacity very
      // small; it'll trick it into decoding the image, but it'll clip to 0 when rendered.
      if (shown) {
        this.popup_container.style.opacity = 1;
        this.popup_container.style.pointerEvents = '';
        this.popup_container.style.position = 'static';
      } else {
        this.popup_container.style.opacity = 0.001;
        // Make sure the invisible element doesn't interfere with the page; disable pointer-events
        // so it doesn't receive clicks, and set it to absolute so it doesn't affect the size of its
        // containing box.
        this.popup_container.style.pointerEvents = 'none';
        this.popup_container.style.position = 'absolute';
        this.popup_container.style.top = '0px';
        this.popup_container.style.right = '0px';
      }
      this.popup_container.style.display = '';
    } else {
      this.popup_container.style.display = shown ? '' : 'none';
    }
    ref = this.corner_draggers;
    for (j = 0, len = ref.length; j < len; j++) {
      cornerDragger = ref[j];
      cornerDragger.update();
    }
  }

  set_show_corner_drag (enable) {
    this.show_corner_drag = enable;
    this.update_show_corner_drag();
  }

  set_image_dimensions (width, height) {
    let editing_frame, post_id;
    editing_frame = this.editing_frame;
    post_id = this.post_id;
    this.close();
    this.image_dimensions = {
      width,
      height
    };
    this.main_frame.style.width = this.image_dimensions.width + 'px';
    this.main_frame.style.height = this.image_dimensions.height + 'px';
    if (post_id != null) {
      this.open(post_id);
      this.focus(editing_frame);
    }
  }

  // Like document.elementFromPoint, but returns an array of all elements at the given point.
  // If a top element is specified, stop if it's reached without including it in the list.
  elementArrayFromPoint (x, y, top) {
    let element, elements, j, len;
    elements = [];
    while (true) {
      element = document.elementFromPoint(x, y);
      if (element === top || element === document.documentElement) {
        break;
      }
      element.original_display = element.style.display;
      element.style.display = 'none';
      elements.push(element);
    }
    // Restore the elements we just hid.
    for (j = 0, len = elements.length; j < len; j++) {
      element = elements[j];
      element.style.display = element.original_display;
      element.original_display = null;
    }
    return elements;
  }

  is_opened () {
    return this.post_id != null;
  }

  // Open the frame editor if it isn't already, and focus on the specified frame.
  open (post_id) {
    let cornerDragger, j, len, onKeydownDocument, post, ref;
    if (this.image_dimensions == null) {
      throw 'Must call set_image_dimensions before open';
    }
    if (this.post_id != null) {
      return;
    }
    this.post_id = post_id;
    this.editing_frame = null;
    this.dragging_item = null;
    this.container.style.display = '';
    this.main_frame.style.display = '';
    this.update_show_corner_drag();
    post = Post.posts.get(this.post_id);
    ref = this.corner_draggers;
    // Tell the corner draggers which post we're working on now, so they'll start
    // loading the JPEG version immediately if necessary.  Otherwise, we'll start
    // loading it the first time we focus a frame, which will hitch the editor for
    // a while in Chrome.
    for (j = 0, len = ref.length; j < len; j++) {
      cornerDragger = ref[j];
      cornerDragger.set_post_id(this.post_id);
    }
    onKeydownDocument = (e) => {
      if (e.keyCode === Event.KEY_ESC) {
        this.discard();
      }
    };
    $(document).on('keydown', onKeydownDocument);
    this.open_handlers.push(() => {
      return $(document).off('keydown', onKeydownDocument);
    });
    // If we haven't done so already, make a backup of this post's frames.  We'll restore
    // from this later if the user cancels the edit.
    this.original_frames = JSON.stringify(post.frames_pending);
    this.repopulate_table();
    this.create_dragger();
    if (post.frames_pending.length > 0) {
      this.focus(0);
    }
    this.update();
  }

  create_dragger () {
    let dragElementOptions, ref;
    if ((ref = this.dragger) != null) {
      ref.destroy();
    }
    dragElementOptions = {
      ondown: (e) => {
        let clickedElement, clicked_elements, element, frame, frame_element, frame_idx, j, k, l, len, len1, len2, len3, m, post, ref1, ref2;
        post = Post.posts.get(this.post_id);
        ref1 = this.image_frames;
        // Figure out which element(s) we're clicking on.  The click may lie on a spot
        // where multiple frames overlap; make a list.

        // Temporarily enable pointerEvents on the frames, so elementFromPoint will
        // resolve them.
        for (j = 0, len = ref1.length; j < len; j++) {
          frame = ref1[j];
          frame.style.pointerEvents = 'all';
        }
        clicked_elements = this.elementArrayFromPoint(e.x, e.y, this.main_frame);
        ref2 = this.image_frames;
        for (k = 0, len1 = ref2.length; k < len1; k++) {
          frame = ref2[k];
          frame.style.pointerEvents = 'none';
        }
        // If we clicked on a handle, prefer it over frame bodies at the same spot.
        element = null;
        for (l = 0, len2 = clicked_elements.length; l < len2; l++) {
          clickedElement = clicked_elements[l];
          // If a handle was clicked, always prefer it.  Use the first handle we find,
          // so we prefer the corner handles (which are always on top) to edge handles.
          if (clickedElement.classList.contains('frame-box-handle')) {
            element = clickedElement;
            break;
          }
        }
        if (element == null) {
          for (m = 0, len3 = clicked_elements.length; m < len3; m++) {
            clickedElement = clicked_elements[m];
            if (!clickedElement.classList.contains('frame-editor-frame-box')) {
              clickedElement = clickedElement.closest('.frame-editor-frame-box');
            }
            if (this.image_frames.indexOf(clickedElement) === this.editing_frame) {
              element = clickedElement;
              break;
            }
          }
        }
        // Otherwise, just use the first item that was found.
        if (element == null) {
          element = clicked_elements[0];
        }
        // If a handle was clicked on, find the frame element that contains it.
        frame_element = element;
        if ((frame_element != null) && !frame_element.classList.contains('frame-editor-frame-box')) {
          frame_element = frame_element.closest('.frame-editor-frame-box');
        }
        if (frame_element != null) {
          this.dragging_new = false;
        } else {
          if (!this.drag_to_create) {
            return;
          }
          this.dragging_new = true;
        }
        // If the element we actually clicked on was one of the edge handles, set the drag
        // mode based on which one was clicked.
        if ((element != null) && element.classList.contains('frame-box-handle')) {
          this.dragging_mode = element._frameDragCursor;
        } else {
          this.dragging_mode = 'move';
        }
        if ((frame_element != null) && frame_element.classList.contains('frame-editor-frame-box')) {
          frame_idx = this.image_frames.indexOf(frame_element);
          this.dragging_idx = frame_idx;
          frame = post.frames_pending[this.dragging_idx];
          this.dragging_anchor = frameDimensionsToImage(frame, this.image_dimensions, post);
        }
        this.focus(this.dragging_idx);
        // If we're dragging a handle, override the drag class so the pointer will
        // use the handle pointer instead of the drag pointer.
        this.dragger.overriden_drag_class = this.dragging_mode === 'move' ? null : this.dragging_mode;
        this.dragger.options.snap_pixels = this.dragging_new ? 10 : 0;
        // Stop propagation of the event, so any other draggers in the chain don't start.  In
        // particular, when we're dragging inside the image, we need to stop WindowDragElementAbsolute.
        // Only do this if we're actually dragging, not if we aborted due to this.drag_to_create.
        e.latest_event.stopPropagation();
      },
      onup: (e) => {
        this.dragging_idx = null;
        this.dragging_anchor = null;
      },
      ondrag: (e) => {
        let dims, frame_offset, post, source_dims;
        post = Post.posts.get(this.post_id);
        dims = void 0;
        source_dims = void 0;
        if (this.dragging_new) {
          // Pick a dragging mode based on which way we were dragged.  This is a
          // little funny; we should probably be able to drag freely, not be fixed
          // to the first direction we drag.
          this.dragging_mode = e.aX > 0 && e.aY > 0 ? 'se-resize' : e.aX > 0 && e.aY < 0 ? 'ne-resize' : e.aX < 0 && e.aY > 0 ? 'sw-resize' : e.aX < 0 && e.aY < 0 ? 'nw-resize' : void 0;
          if (this.dragging_mode == null) {
            return;
          }
          this.dragging_new = false;
          // Create a new, empty frame.  When we get to the regular drag path below we'll
          // give it its real size, based on how far we've dragged so far.
          frame_offset = $(this.main_frame).offset();
          dims = {
            left: e.dragger.anchor_x - frame_offset.left,
            top: e.dragger.anchor_y - frame_offset.top,
            height: 0,
            width: 0
          };
          this.dragging_anchor = dims;
          source_dims = frameDimensionsFromImage(dims, this.image_dimensions, post);
          this.dragging_idx = this.add_frame(source_dims);
          post.frames_pending[this.editing_frame] = source_dims;
        }
        if (this.dragging_idx == null) {
          return;
        }
        dims = applyDrag(this.dragging_mode, e.aX, e.aY, this.image_dimensions, this.dragging_anchor);
        // Scale the changed dimensions back to the source resolution and apply them
        // to the frame.
        post.frames_pending[this.editing_frame] = frameDimensionsFromImage(dims, this.image_dimensions, post);
        this.update_frame_in_list(this.editing_frame);
        this.update_image_frame(this.editing_frame);
      }
    };
    this.dragger = new DragElement(this.main_frame, dragElementOptions);
  }

  repopulate_table () {
    let _frame, i, imageFrame, j, k, len, len1, post, ref, ref1, tbody;
    post = Post.posts.get(this.post_id);
    // Clear the table.
    tbody = this.container.querySelector('.frame-list tbody');
    while (tbody.firstChild != null) {
      tbody.removeChild(tbody.firstChild);
    }
    ref = this.image_frames;
    // Clear the image frames.
    for (j = 0, len = ref.length; j < len; j++) {
      imageFrame = ref[j];
      imageFrame.remove();
    }
    this.image_frames = [];
    ref1 = post.frames_pending;
    for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
      _frame = ref1[i];
      this.add_frame_to_list(i);
      this.create_image_frame();
      this.update_image_frame(i);
    }
  }

  update () {
    let _frame, i, j, len, post, ref;
    this.update_show_corner_drag();
    if (this.image_dimensions == null) {
      return;
    }
    post = Post.posts.get(this.post_id);
    if (post != null) {
      ref = post.frames_pending;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        _frame = ref[i];
        this.update_image_frame(i);
      }
    }
  }

  // If the frame editor is open, discard changes and close it.
  discard () {
    let post, post_id, revert_to;
    if (this.post_id == null) {
      return;
    }
    // Save revert_to, and close the editor before reverting, to make sure closing
    // the editor doesn't change anything.
    revert_to = this.original_frames;
    post_id = this.post_id;
    this.close();
    // Revert changes.
    post = Post.posts.get(post_id);
    post.frames_pending = JSON.parse(revert_to);
  }

  // Get the frames specifier for the post's frames.
  get_current_frames_spec () {
    return Post.posts.get(this.post_id).frames_pending.map(function (frame) {
      return `${frame.source_left}x${frame.source_top},${frame.source_width}x${frame.source_height}`;
    }).join(';');
  }

  // Return true if the frames have been changed.
  changed () {
    return Post.posts.get(this.post_id) !== this.get_current_frames_spec();
  }

  // Save changes to the post, if any.  If not null, call finished on completion.
  save (finished) {
    let frame, post, post_id, spec;
    if (this.post_id == null) {
      if (typeof finished === 'function') {
        finished();
      }
      return;
    }
    // Save the current post_id, so it's preserved when the AJAX completion function
    // below is run.
    post_id = this.post_id;
    post = Post.posts.get(post_id);
    frame = post.frames_pending;
    spec = this.get_current_frames_spec();
    if (spec === post.frames_pending_string) {
      if (typeof finished === 'function') {
        finished();
      }
      return;
    }
    Post.update_batch([
      {
        id: post_id,
        frames_pending_string: spec
      }
    ], (posts) => {
      if (this.post_id === post_id) {
        // The registered post has been changed, and we're still displaying it.  Grab the
        // new version, and updated original_frames so we no longer consider this post
        // changed.
        post = Post.posts.get(post_id);
        this.original_frames = JSON.stringify(post.frames_pending);
        // In the off-chance that the frames_pending that came back differs from what we
        // requested, update the display.
        this.update();
      }
      if (typeof finished === 'function') {
        finished();
      }
    });
  }

  create_image_frame () {
    let div;
    div = document.createElement('div');
    div.className = 'frame-editor-frame-box';
    // Disable pointer-events on the image frame, so the handle cursors always
    // show up even when an image frame lies on top of it.
    div.style.pointerEvents = 'none';
    // div.style.opacity=0.1;
    this.main_frame.appendChild(div);
    this.image_frames.push(div);
    createDragBox(div);
  }

  update_image_frame (frame_idx) {
    let cornerDragger, dimensions, div, frame, j, len, post, ref;
    post = Post.posts.get(this.post_id);
    frame = post.frames_pending[frame_idx];
    // If the focused frame is being modified, update the corner dragger as well.
    if (frame_idx === this.editing_frame) {
      ref = this.corner_draggers;
      for (j = 0, len = ref.length; j < len; j++) {
        cornerDragger = ref[j];
        cornerDragger.update();
      }
    }
    dimensions = frameDimensionsToImage(frame, this.image_dimensions, post);
    div = this.image_frames[frame_idx];
    div.style.left = `${dimensions.left}px`;
    div.style.top = `${dimensions.top}px`;
    div.style.width = `${dimensions.width}px`;
    div.style.height = `${dimensions.height}px`;
    div.classList.toggle('focused-frame-box', frame_idx === this.editing_frame);
  }

  // Append the given frame to the editor list.
  add_frame_to_list (frame_idx) {
    let html, tbody, tr;
    tbody = this.container.querySelector('.frame-list tbody');
    tr = document.createElement('tr');
    tr.className = `frame-row frame-${frame_idx}`;
    tr.frame_idx = frame_idx;
    tbody.appendChild(tr);
    html = '<td><span class=\'frame-label\'>Frame ' + frame_idx + '</span></td>';
    html += '<td><input class=\'frame-left frame-dims\' size=4></td>';
    html += '<td><input class=\'frame-top frame-dims\' size=4></td>';
    html += '<td><input class=\'frame-width frame-dims\' size=4></td>';
    html += '<td><input class=\'frame-height frame-dims\' size=4></td>';
    html += '<td><a class=\'frame-delete frame-button-box\' href=\'#\'>X</a></td>';
    html += '<td><a class=\'frame-up frame-button-box\' href=\'#\'>⇡</a></td>';
    html += '<td><a class=\'frame-down frame-button-box\' href=\'#\'>⇣</a></td>';
    tr.innerHTML = html;
    this.update_frame_in_list(frame_idx);
  }

  // Update the fields of frame_idx in the table.
  update_frame_in_list (frame_idx) {
    let frame, post, tr;
    post = Post.posts.get(this.post_id);
    frame = post.frames_pending[frame_idx];
    tr = this.container.querySelector(`.frame-list tbody .frame-${frame_idx}`);
    tr.querySelector('.frame-left').value = frame.source_left;
    tr.querySelector('.frame-top').value = frame.source_top;
    tr.querySelector('.frame-width').value = frame.source_width;
    tr.querySelector('.frame-height').value = frame.source_height;
  }

  // Commit changes in the frame list to the frame.
  update_frame_from_list (frame_idx) {
    let frame, post, tr;
    post = Post.posts.get(this.post_id);
    frame = post.frames_pending[frame_idx];
    tr = this.container.querySelector(`.frame-list tbody .frame-${frame_idx}`);
    frame.source_left = tr.querySelector('.frame-left').value;
    frame.source_top = tr.querySelector('.frame-top').value;
    frame.source_width = tr.querySelector('.frame-width').value;
    frame.source_height = tr.querySelector('.frame-height').value;
  }

  // Add a new default frame to the end of the list, update the table, and edit the new frame.
  add_frame (new_frame) {
    let post;
    post = Post.posts.get(this.post_id);
    if (new_frame == null) {
      new_frame = {
        source_top: post.height * 1 / 4,
        source_left: post.width * 1 / 4,
        source_width: post.width / 2,
        source_height: post.height / 2
      };
    }
    post.frames_pending.push(new_frame);
    this.add_frame_to_list(post.frames_pending.length - 1);
    this.create_image_frame();
    this.update_image_frame(post.frames_pending.length - 1);
    this.focus(post.frames_pending.length - 1);
    return post.frames_pending.length - 1;
  }

  // Delete the specified frame.
  delete_frame (frame_idx) {
    let post, switch_to_frame;
    post = Post.posts.get(this.post_id);
    // If we're editing this frame, switch to a nearby one.
    switch_to_frame = null;
    if (this.editing_frame === frame_idx) {
      switch_to_frame = this.editing_frame;
      this.focus(null);
      // If we're deleting the bottom item on the list, switch to the item above it instead.
      if (frame_idx === post.frames_pending.length - 1) {
        --switch_to_frame;
      }
      // If that put it over the top, we're deleting the only item.  Focus no item.
      if (switch_to_frame < 0) {
        switch_to_frame = null;
      }
    }
    // Remove the frame from the array.
    post.frames_pending.splice(frame_idx, 1);
    // Renumber the table.
    this.repopulate_table();
    // Focus switch_to_frame, if any.
    this.focus(switch_to_frame);
  }

  focus (post_frame) {
    let cornerDragger, j, len, ref;
    if (this.editing_frame === post_frame) {
      return;
    }
    if (this.editing_frame != null) {
      this.container.querySelector(`.frame-${this.editing_frame}`).classList.remove('frame-focused');
    }
    this.editing_frame = post_frame;
    if (this.editing_frame != null) {
      this.container.querySelector(`.frame-${this.editing_frame}`).classList.add('frame-focused');
    }
    ref = this.corner_draggers;
    for (j = 0, len = ref.length; j < len; j++) {
      cornerDragger = ref[j];
      cornerDragger.set_post_frame(this.editing_frame);
    }
    this.update();
  }

  // Close the frame editor.  Local changes are not saved or reverted.
  close () {
    let base, cornerDragger, dispose, j, k, len, len1, ref, ref1, ref2, tbody;
    if (this.post_id == null) {
      return;
    }
    this.post_id = null;
    this.editing_frame = null;
    ref = this.corner_draggers;
    for (j = 0, len = ref.length; j < len; j++) {
      cornerDragger = ref[j];
      cornerDragger.set_post_id(null);
    }
    ref1 = this.open_handlers;
    for (k = 0, len1 = ref1.length; k < len1; k++) {
      dispose = ref1[k];
      dispose();
    }
    this.open_handlers = [];
    if ((ref2 = this.dragger) != null) {
      ref2.destroy();
    }
    this.dragger = null;
    this.container.hide();
    this.main_frame.hide();
    this.update_show_corner_drag();
    // Clear the row table.
    tbody = this.container.querySelector('.frame-list tbody');
    while (tbody.firstChild) {
      tbody.removeChild(tbody.firstChild);
    }
    this.original_frames = null;
    this.update();
    if (typeof (base = this.options).onClose === 'function') {
      base.onClose(this);
    }
  }
};
