// Generated by CoffeeScript 2.7.0
var $, History;

$ = jQuery;

export default History = class History {
  constructor() {
    this.doc_mouseup = this.doc_mouseup.bind(this);
    this.last_click = -1;
    this.checked = [];
    this.dragging = false;
  }

  init() {
    // Watch mousedown events on the table itself, so clicking between table rows
    // and dragging doesn't misbehave.
    $('#history').on('mousedown', (event) => {
      if (!event.shiftKey) {
        // Clear last_click, so dragging will extend from the next position
        // crossed instead of the previous position clicked.
        this.last_click = -1;
      }
      this.mouse_is_down();
      event.stopPropagation();
      return event.preventDefault();
    });
    return this.update();
  }

  add_change(change_id, group_by_type, group_by_id, ids, user_id) {
    var row;
    row = $(`#r${change_id}`);
    this.checked.push({
      id: change_id,
      ids: ids,
      group_by_type: group_by_type,
      group_by_id: group_by_id,
      user_id: user_id,
      on: false,
      row: row
    });
    row.on('mousedown', (e) => {
      return this.mousedown(change_id, e);
    });
    row.on('mouseover', (e) => {
      return this.mouseover(change_id, e);
    });
    row.find('.id').on('click', (event) => {
      return this.id_click(change_id);
    });
    row.find('.author').on('click', (event) => {
      return this.author_click(change_id);
    });
    return row.find('.change').on('click', (event) => {
      return this.change_click(change_id);
    });
  }

  update() {
    var entry, j, len, ref, row;
    ref = this.checked;
    // Set selected flags on selected rows, and remove them from unselected rows.
    for (j = 0, len = ref.length; j < len; j++) {
      entry = ref[j];
      row = entry.row;
      if (entry.on) {
        row.addClass('selected');
      } else {
        row.removeClass('selected');
      }
    }
    if (this.count_selected() > 0) {
      $('#undo').removeClass('footer-disabled');
      return $('#redo').removeClass('footer-disabled');
    } else {
      $('#undo').addClass('footer-disabled');
      return $('#redo').addClass('footer-disabled');
    }
  }

  id_click(id) {
    var entry;
    id = this.get_row_by_id(id);
    entry = this.checked[id];
    return $('#search').val(`${entry.group_by_type.toLowerCase()}:${entry.group_by_id}`);
  }

  author_click(id) {
    id = this.get_row_by_id(id);
    return $('#search').val(`user:${this.checked[id].user_id}`);
  }

  change_click(id) {
    id = this.get_row_by_id(id);
    return $('#search').val(`change:${this.checked[id].id}`);
  }

  count_selected() {
    var entry, j, len, ref, ret;
    ret = 0;
    ref = this.checked;
    for (j = 0, len = ref.length; j < len; j++) {
      entry = ref[j];
      if (entry.on) {
        ret++;
      }
    }
    return ret;
  }

  get_first_selected_row() {
    var entry, i, j, len, ref;
    ref = this.checked;
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      entry = ref[i];
      if (entry.on) {
        return i;
      }
    }
    // nothing found, return null
    return null;
  }

  get_row_by_id(id) {
    var entry, i, j, len, ref;
    ref = this.checked;
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      entry = ref[i];
      if (entry.id.toString() === id.toString()) {
        return i;
      }
    }
    // nothing found, return -1
    return -1;
  }

  set(first, last, isOn) {
    var entry, j, len, ref, results;
    first = parseInt(first, 10);
    last = parseInt(last, 10);
    if (last < first) {
      [first, last] = [last, first];
    }
    ref = this.checked.slice(first, +last + 1 || 9e9);
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      entry = ref[j];
      results.push(entry.on = isOn);
    }
    return results;
  }

  doc_mouseup(event) {
    this.dragging = false;
    return $(document).off('mouseup', this.doc_mouseup);
  }

  mouse_is_down() {
    this.dragging = true;
    return $(document).on('mouseup', this.doc_mouseup);
  }

  mousedown(id, event) {
    var first, i, isOn, last;
    // only for primary click
    if (event.which !== 1) {
      return;
    }
    this.mouse_is_down();
    i = this.get_row_by_id(id);
    // no row found?
    if (i === -1) {
      return;
    }
    first = null;
    last = null;
    if (this.last_click !== -1 && event.shiftKey) {
      first = this.last_click;
      last = i;
    } else {
      first = last = this.last_click = i;
      this.checked[i].on = !this.checked[i].on;
    }
    isOn = this.checked[first].on;
    if (!event.ctrlKey) {
      this.set(0, this.checked.length - 1, false);
    }
    this.set(first, last, isOn);
    this.update();
    event.stopPropagation();
    return event.preventDefault();
  }

  mouseover(id, event) {
    var first, i, last, this_click;
    i = this.get_row_by_id(id);
    if (i === -1) {
      return;
    }
    if (this.last_click === -1) {
      this.last_click = i;
    }
    if (!this.dragging) {
      return;
    }
    this.set(0, this.checked.length - 1, false);
    first = this.last_click;
    last = i;
    this_click = i;
    this.set(first, last, true);
    return this.update();
  }

  undo(redo) {
    var entry, j, len, list, ref;
    if (this.count_selected() === 0) {
      return;
    }
    list = [];
    ref = this.checked;
    for (j = 0, len = ref.length; j < len; j++) {
      entry = ref[j];
      if (entry.on) {
        list = list.concat(entry.ids);
      }
    }
    if (redo) {
      notice('Reapplying...');
    } else {
      notice('Undoing...');
    }
    return $.ajax('/history/undo.json', {
      method: 'POST',
      dataType: 'json',
      data: {
        id: list.join(','),
        redo: redo ? 1 : 0
      }
    }).done(function(resp) {
      var mainMessage, text;
      text = resp.errors;
      if (resp.successful > 0) {
        mainMessage = `Changes ${redo ? 'reapplied' : 'undone'}.`;
        text.unshift(mainMessage);
      }
      return notice(text.join('<br>'));
    }).fail(function(resp) {
      return notice(`Error: ${resp.reason}`);
    });
  }

};
