// Generated by CoffeeScript 2.7.0
var $, ImageCrop, convertCropperToForm, convertFormToCropper,
  hasProp = {}.hasOwnProperty;

$ = jQuery;

import Cropper from 'cropperjs';

convertCropperToForm = function(cropper) {
  var coord, cropperData, form, formParsed, rect, value;
  rect = cropper.getCanvasData();
  cropperData = cropper.getData();
  formParsed = {
    left: cropperData.x / rect.width,
    right: (cropperData.x + cropperData.width) / rect.width,
    top: cropperData.y / rect.height,
    bottom: (cropperData.y + cropperData.height) / rect.height
  };
  form = {};
  for (coord in formParsed) {
    if (!hasProp.call(formParsed, coord)) continue;
    value = formParsed[coord];
    form[coord] = value.toFixed(4);
  }
  return form;
};

convertFormToCropper = function(cropper, form) {
  var base, coord, formParsed, parsed, rect, validForm, value;
  rect = cropper.getCanvasData();
  formParsed = {};
  validForm = true;
  for (coord in form) {
    if (!hasProp.call(form, coord)) continue;
    value = form[coord];
    parsed = parseFloat(value);
    if (parsed === 0) {
      validForm = false;
      break;
    } else {
      formParsed[coord] = parsed;
    }
  }
  if (validForm) {
    return {
      x: formParsed.left * rect.width,
      width: (formParsed.right - formParsed.left) * rect.width,
      y: formParsed.top * rect.height,
      height: (formParsed.bottom - formParsed.top) * rect.height
    };
  } else {
    base = Math.min(rect.width, rect.height) / 4;
    return {
      x: base,
      width: base,
      y: base,
      height: base
    };
  }
};

export default ImageCrop = class ImageCrop {
  constructor() {
    // to allow submitting the form by pressing enter
    this.focusSubmit = this.focusSubmit.bind(this);
    this.initialize = this.initialize.bind(this);
    this.onCropend = this.onCropend.bind(this);
    this.onReady = this.onReady.bind(this);
    this.onWindowChange = this.onWindowChange.bind(this);
    this.positionPreview = this.positionPreview.bind(this);
    $(this.initialize);
  }

  focusSubmit() {
    var ref;
    return (ref = this.submit) != null ? ref.focus({
      preventScroll: true
    }) : void 0;
  }

  initialize() {
    var options;
    this.form = document.querySelector('.js-image-crop');
    if (this.form == null) {
      return;
    }
    this.image = this.form.querySelector('.js-image-crop--image');
    this.preview = this.form.querySelector('.js-image-crop--preview');
    this.submit = this.form.querySelector('input[type="submit"]');
    options = {
      checkCrossOrigin: false,
      movable: false,
      preview: this.preview,
      rotatable: false,
      scalable: false,
      zoomable: false
    };
    this.image.addEventListener('cropend', this.onCropend);
    this.image.addEventListener('ready', this.onReady);
    this.cropper = new Cropper(this.image, options);
    if (this.preview != null) {
      this.previewContainer = document.querySelector('.js-image-crop--preview-container');
      $(window).on('resize scroll', this.onWindowChange);
      this.positionPreview();
    }
    return this.focusSubmit();
  }

  onCropend(e) {
    var coord, ref, value;
    ref = convertCropperToForm(this.cropper);
    for (coord in ref) {
      if (!hasProp.call(ref, coord)) continue;
      value = ref[coord];
      this.form.querySelector(`#${coord}`).value = value;
    }
    return this.focusSubmit();
  }

  onReady() {
    var coord, form, i, len, ref;
    form = {};
    ref = ['left', 'right', 'top', 'bottom'];
    for (i = 0, len = ref.length; i < len; i++) {
      coord = ref[i];
      form[coord] = this.form.querySelector(`#${coord}`).value;
    }
    return this.cropper.setData(convertFormToCropper(this.cropper, form));
  }

  onWindowChange() {
    return requestAnimationFrame(this.positionPreview);
  }

  positionPreview() {
    var imageRect, left, maxRight, previewRect, right, top;
    previewRect = this.previewContainer.getBoundingClientRect();
    imageRect = this.form.getBoundingClientRect();
    maxRight = document.body.clientWidth;
    // try to position it outside the image
    left = imageRect.right + 10;
    right = left + previewRect.width;
    // if it overflows, keep it inside the window but never outside the image itself
    if (right > maxRight) {
      left = Math.min(imageRect.right, maxRight) - previewRect.width - 10;
    }
    // stick to the top when scrolled down
    top = Math.max(0, imageRect.top) + 10;
    this.previewContainer.style.left = `${left}px`;
    return this.previewContainer.style.top = `${top}px`;
  }

};
