// Generated by CoffeeScript 2.7.0
var $, MenuDropdown;

$ = jQuery;

export default MenuDropdown = class MenuDropdown {
  constructor() {
    this.hide = this.hide.bind(this);
    this.onDocumentClick = this.onDocumentClick.bind(this);
    this.onToggle = this.onToggle.bind(this);
    $(document).on('click', '.submenu-button', this.onToggle);
    $(document).on('click', this.onDocumentClick);
  }

  hide() {
    if (this.current == null) {
      return;
    }
    this.current.$menu.hide();
    return this.current = null;
  }

  onDocumentClick(e) {
    if (this.current == null) {
      return;
    }
    if (((e != null ? e.target : void 0) != null) && $(e.target).closest(this.current.link).length > 0) {
      return;
    }
    return this.hide();
  }

  onToggle(e) {
    var $menu, link, openLink, ref;
    e.preventDefault();
    link = e.currentTarget;
    openLink = (ref = this.current) != null ? ref.link : void 0;
    this.hide();
    if (openLink === link) {
      return;
    }
    $menu = $(link).siblings('.submenu');
    $menu.show();
    return this.current = {link, $menu};
  }

};
