// Generated by CoffeeScript 2.7.0
var $, MenuDragDrop;

$ = jQuery;

export default MenuDragDrop = class MenuDragDrop {
  constructor() {
    this.initialize = this.initialize.bind(this);
    this.menuLinksEnter = this.menuLinksEnter.bind(this);
    this.startSubmenuEnter = this.startSubmenuEnter.bind(this);
    this.doDragDrop = this.doDragDrop.bind(this);
    this.endDragDrop = this.endDragDrop.bind(this);
    this.mouseup = this.mouseup.bind(this);
    this.mousedown = this.mousedown.bind(this);
    $(this.initialize);
  }

  initialize() {
    this.menuLinks = $('#main-menu > ul > li > a');
    this.submenus = this.menuLinks.siblings('.submenu');
    this.submenuLinks = this.submenus.find('a');
    this.which = null;
    this.dragStartTarget = null;
    this.dragStartSubmenu = null;
    this.dragStarted = false;
    this.menuLinks.on('mousedown', this.mousedown);
    return this.menuLinks.on('dragstart', function() {
      return false;
    });
  }

  menuLinksEnter(e) {
    var submenu;
    submenu = $(e.currentTarget).siblings('.submenu');
    this.submenus.hide();
    this.dragStartSubmenu.css('opacity', '');
    return submenu.show();
  }

  startSubmenuEnter(e) {
    this.dragStartSubmenu.off('mousemove', this.startSubmenuEnter);
    return this.dragStartSubmenu.css('opacity', '');
  }

  submenuLinkEnter(e) {
    return $(e.currentTarget).addClass('hover');
  }

  submenuLinksLeave(e) {
    return $(e.currentTarget).removeClass('hover');
  }

  doDragDrop() {
    this.dragStartTarget.off('mouseleave', this.doDragDrop);
    this.submenus.hide();
    this.dragStartSubmenu.css('opacity', '0.4').show();
    this.dragStartSubmenu.on('mousemove', this.startSubmenuEnter);
    this.menuLinks.on('mouseenter', this.menuLinksEnter);
    this.submenuLinks.on('mouseenter', this.submenuLinksEnter);
    this.submenuLinks.on('mouseleave', this.submenuLinksLeave);
    return this.dragStarted = true;
  }

  endDragDrop() {
    this.submenus.css('opacity', '').hide();
    this.dragStartSubmenu.off('mousemove', this.startSubmenuEnter);
    this.menuLinks.off('mouseenter', this.menuLinksEnter);
    this.submenuLinks.off('mouseenter', this.submenuLinksEnter);
    this.submenuLinks.off('mouseleave', this.submenuLinksLeave);
    this.submenuLinks.removeClass('hover');
    return this.dragStarted = false;
  }

  mouseup(e) {
    var target;
    $(document).off('mouseup', this.mouseup);
    this.dragStartTarget.off('mouseleave', this.doDragDrop);
    if (this.dragStarted) {
      this.endDragDrop();
    }
    target = $(e.target);
    // only trigger click if it's submenu link and the button didn't change.
    // A different, normal click will be triggered if it's different button.
    if (this.submenus.find(target).length > 0 && this.which === e.which) {
      if (this.which === 2) {
        // if started with middle click, open the target in a new window.
        target.attr('target', '_blank');
      }
      target[0].click();
      return target.attr('target', null);
    }
  }

  mousedown(e) {
    var ref;
    this.which = e.which;
    if ((ref = this.which) !== 1 && ref !== 2) {
      return;
    }
    this.dragStartTarget = $(e.currentTarget);
    this.dragStartSubmenu = this.dragStartTarget.siblings('.submenu');
    $(document).on('mouseup', this.mouseup);
    return this.dragStartTarget.on('mouseleave', this.doDragDrop);
  }

};
