// Generated by CoffeeScript 2.7.0
import Mousetrap from 'mousetrap';

let $, Menu;

$ = jQuery;

export default Menu = class Menu {
  constructor () {
    this.initialize = this.initialize.bind(this);
    this.setPostModerateCount = this.setPostModerateCount.bind(this);
    this.setHighlight = this.setHighlight.bind(this);
    this.showHelpItem = this.showHelpItem.bind(this);
    this.syncForumMenu = this.syncForumMenu.bind(this);
    $(this.initialize);
  }

  initialize () {
    this.menu = $('#main-menu');
    if (this.menu.length > 0) {
      this.setHighlight();
      this.setPostModerateCount();
      this.syncForumMenu();
      this.showHelpItem();
    }
    $(document).on('click', '#login-link', function (e) {
      e.preventDefault();
      return User.run_login(false, function () {
        Cookie.put('notice', 'You have been logged in.');
        return document.location.reload();
      });
    });
    $(document).on('click', '#forum-mark-all-read', function (e) {
      e.preventDefault();
      return Forum.markAllRead();
    });
    return $(document).on('click', '#main-menu .search-link', (e) => {
      e.preventDefault();
      this.showSearchBox(e.currentTarget);
    });
  }

  setPostModerateCount () {
    let link, pending;
    pending = parseInt(Cookies.get('mod_pending'));
    if (!(pending > 0)) {
      return;
    }
    link = this.menu.find('.moderate');
    return link.text(`${link.text()} (${pending})`).addClass('bolded');
  }

  setHighlight () {
    return this.menu.find(`.${this.menu.data('controller')}`).addClass('current-menu');
  }

  showHelpItem () {
    return this.menu.find(`.help-item.${this.menu.data('controller')}`).show();
  }

  showSearchBox (elem) {
    let hide, search_box, search_text_box, show, submenu;
    submenu = $(elem).parents('.submenu');
    search_box = submenu.siblings('.search-box');
    search_text_box = search_box.find('[type="text"]');
    hide = function (e) {
      search_box.hide();
      search_box.removeClass('is_modal');
      search_text_box.removeClass('mousetrap');
    };
    show = function () {
      let document_click_event;
      $('.submenu').hide();
      search_box.show();
      search_box.addClass('is_modal');
      search_text_box.addClass('mousetrap').focus();
      document_click_event = function (e) {
        if ($(e.target).parents('.is_modal').length === 0 && !$(e.target).hasClass('is_modal')) {
          hide(e);
          $(document).off('mousedown', '*', document_click_event);
        }
      };
      $(document).on('mousedown', '*', document_click_event);
      Mousetrap.bind('esc', hide);
    };
    return show();
  }

  syncForumMenu (reload = false) {
    let create_forum_item, forum_items_start, forum_menu_items, forum_submenu, last_read;
    if (reload) {
      $.get(Moebooru.path('/forum.json'), {
        latest: 1
      }, (resp) => {
        this.forumMenuItems = resp;
        return this.syncForumMenu(false);
      });
      return;
    }
    if (this.forumMenuItems == null) {
      this.forumMenuItems = JSON.parse(document.getElementById('forum-posts-latest').text);
    }
    last_read = JSON.parse(document.getElementById('forum-post-last-read-at').text);
    forum_menu_items = this.forumMenuItems;
    forum_submenu = $('li.forum ul.submenu', this.menu);
    forum_items_start = forum_submenu.find('.forum-items-start').show();
    create_forum_item = function (post_data) {
      return $('<li/>', {
        html: $('<a/>', {
          href: Moebooru.path('/forum/show/' + post_data.id + '?page=' + post_data.pages),
          text: post_data.title,
          title: post_data.title,
          class: post_data.updated_at > last_read ? 'unread-topic' : null
        })
      });
    };
    // Reset latest topics.
    forum_items_start.nextAll().remove();
    if (forum_menu_items.length > 0) {
      $.each(forum_menu_items, function (_i, post_data) {
        forum_submenu.append(create_forum_item(post_data));
        forum_items_start.show();
      });
      // Set correct class based on read/unread.
      if (forum_menu_items.first().updated_at > last_read) {
        $('#forum-link').addClass('forum-update');
        return $('#forum-mark-all-read').show();
      } else {
        $('#forum-link').removeClass('forum-update');
        return $('#forum-mark-all-read').hide();
      }
    }
  }
};
