// Generated by CoffeeScript 2.7.0
var Navigator;

import DragElement from 'src/classes/drag_element';

export default Navigator = class Navigator {
  constructor(container, target) {
    this.mouseover_event = this.mouseover_event.bind(this);
    this.mouseout_event = this.mouseout_event.bind(this);
    this.mousedown_event = this.mousedown_event.bind(this);
    this.enddrag = this.enddrag.bind(this);
    this.ondrag = this.ondrag.bind(this);
    this.container = container;
    this.target = target;
    this.hovering = false;
    this.autohide = false;
    this.img = this.container.down('.image-navigator-img');
    this.container.show();
    this.handlers = [];
    this.handlers.push(this.container.on('mousedown', this.mousedown_event));
    this.handlers.push(this.container.on('mouseover', this.mouseover_event));
    this.handlers.push(this.container.on('mouseout', this.mouseout_event));
    this.dragger = new DragElement(this.container, {
      snap_pixels: 0,
      onenddrag: this.enddrag,
      ondrag: this.ondrag
    });
  }

  set_image(image_url, width, height) {
    this.img.src = image_url;
    this.img.width = width;
    return this.img.height = height;
  }

  enable(enabled) {
    return this.container.show(enabled);
  }

  mouseover_event(e) {
    if (this.container.contains(e.relatedTarget)) {
      return;
    }
    console.debug(`over ${e.target.className}, ${this.container.className}, ${this.container.contains(e.target)}`);
    this.hovering = true;
    return this.update_visibility();
  }

  mouseout_event(e) {
    if (this.container.contains(e.relatedTarget)) {
      return;
    }
    console.debug(`out ${e.target.className}`);
    this.hovering = false;
    return this.update_visibility();
  }

  mousedown_event(e) {
    var coords, x, y;
    x = e.pointerX();
    y = e.pointerY();
    coords = this.get_normalized_coords(x, y);
    return this.center_on_position(coords);
  }

  enddrag(e) {
    this.shift_lock_anchor = null;
    this.locked_to_x = null;
    return this.update_visibility();
  }

  ondrag(e) {
    var coords;
    coords = this.get_normalized_coords(e.x, e.y);
    if (e.latest_event.shiftKey !== (this.shift_lock_anchor != null)) {
      // The shift key has been pressed or released.
      if (e.latest_event.shiftKey) {
        // The shift key was just pressed.  Remember the position we were at when it was
        // pressed.
        this.shift_lock_anchor = [coords[0], coords[1]];
      } else {
        // The shift key was released.
        this.shift_lock_anchor = null;
        this.locked_to_x = null;
      }
    }
    return this.center_on_position(coords);
  }

  image_position_changed(percent_x, percent_y, height_percent, width_percent) {
    var cursor;
    // When the image is moved or the visible area is resized, update the cursor rectangle.
    cursor = this.container.down('.navigator-cursor');
    return cursor.setStyle({
      top: this.img.height * (percent_y - (height_percent / 2)) + 'px',
      left: this.img.width * (percent_x - (width_percent / 2)) + 'px',
      width: this.img.width * width_percent + 'px',
      height: this.img.height * height_percent + 'px'
    });
  }

  get_normalized_coords(x, y) {
    var offset;
    offset = this.img.cumulativeOffset();
    x -= offset.left;
    y -= offset.top;
    x /= this.img.width;
    y /= this.img.height;
    return [x, y];
  }

  // x and y are absolute window coordinates.
  center_on_position(coords) {
    var change_x, change_y;
    if (this.shift_lock_anchor) {
      if (this.locked_to_x == null) {
        // Only change the coordinate with the greater delta.
        change_x = Math.abs(coords[0] - this.shift_lock_anchor[0]);
        change_y = Math.abs(coords[1] - this.shift_lock_anchor[1]);
        // Only lock to moving vertically or horizontally after we've moved a small distance
        // from where shift was pressed.
        if (change_x > 0.1 || change_y > 0.1) {
          this.locked_to_x = change_x > change_y;
        }
      }
      // If we've chosen an axis to lock to, apply it.
      if (this.locked_to_x != null) {
        if (this.locked_to_x) {
          coords[1] = this.shift_lock_anchor[1];
        } else {
          coords[0] = this.shift_lock_anchor[0];
        }
      }
    }
    coords[0] = Math.max(0, Math.min(coords[0], 1));
    coords[1] = Math.max(0, Math.min(coords[1], 1));
    return this.target.fire('viewer:center-on', {
      x: coords[0],
      y: coords[1]
    });
  }

  set_autohide(autohide) {
    this.autohide = autohide;
    return this.update_visibility();
  }

  update_visibility() {
    var box, visible;
    box = this.container.down('.image-navigator-box');
    visible = !this.autohide || this.hovering || this.dragger.dragging;
    return box.style.visibility = visible ? 'visible' : 'hidden';
  }

  destroy() {
    this.dragger.destroy();
    this.handlers.each(function(h) {
      return h.stop();
    });
    this.dragger = this.handlers = null;
    return this.container.hide();
  }

};
