// Generated by CoffeeScript 2.7.0
var $, NewsTicker, cookieKey;

$ = jQuery;

cookieKey = 'hide-news-ticker';

export default NewsTicker = class NewsTicker {
  constructor() {
    this.initialize = this.initialize.bind(this);
    this.onCloseLink = this.onCloseLink.bind(this);
    $(this.initialize);
  }

  initialize() {
    this.$newsTicker = $('#news-ticker');
    this.newsDate = this.$newsTicker.attr('data-date');
    if (this.$newsTicker.attr('data-news-hide') === '1') {
      return;
    }
    this.$newsTicker.find('.close-link').click(this.onCloseLink);
    if (Cookies.get(cookieKey) !== this.newsDate) {
      return this.$newsTicker.show();
    }
  }

  onCloseLink(e) {
    e.preventDefault();
    this.$newsTicker.hide();
    return Cookies.set(cookieKey, this.newsDate, {
      expires: 365
    });
  }

};
