// Generated by CoffeeScript 2.7.0
var NotesManager;

export default NotesManager = class NotesManager {
  static image() {
    return document.querySelector('.js-notes-manager--image');
  }

  static ratio() {
    var currentWidth, fullWidth, image;
    image = NotesManager.image();
    if (image == null) {
      return null;
    }
    currentWidth = image.width;
    fullWidth = image.getAttribute('large_width');
    if (fullWidth === 0) {
      return currentWidth;
    } else {
      return currentWidth / fullWidth;
    }
  }

  constructor() {
    this.show = this.show.bind(this);
    this.hide = this.hide.bind(this);
    this.find = this.find.bind(this);
    this.toggle = this.toggle.bind(this);
    this.updateNoteCount = this.updateNoteCount.bind(this);
    this.createButtonClick = this.createButtonClick.bind(this);
    this.create = this.create.bind(this);
    this.getInsertionPosition = this.getInsertionPosition.bind(this);
    this.zindex = 0;
    this.counter = -1;
    this.all = [];
    this.display = true;
    this.debug = false;
    jQuery(document).on('click', '.js-notes-manager--toggle', this.toggle);
    jQuery(document).on('click', '.js-notes-manager--create', this.createButtonClick);
  }

  show() {
    if (this.debug) {
      console.debug('notesManager.show');
    }
    $('note-container').show();
  }

  hide() {
    if (this.debug) {
      console.debug('notesManager.hide');
    }
    $('note-container').hide();
  }

  find(id) {
    var i, item, len, ref;
    if (this.debug) {
      console.debug('notesManager.find');
    }
    ref = this.all;
    for (i = 0, len = ref.length; i < len; i++) {
      item = ref[i];
      if (item.id === id) {
        return item;
      }
    }
    return null;
  }

  toggle(e) {
    if (this.debug) {
      console.debug('notesManager.toggle');
    }
    if (e.currentTarget.getAttribute('data-drag-element') === '1') {
      return;
    }
    this.display = !this.display;
    if (this.display) {
      this.show();
    } else {
      this.hide();
    }
  }

  updateNoteCount() {
    var label;
    if (this.debug) {
      console.debug('notesManager.updateNoteCount');
    }
    if (this.all.length > 0) {
      label = '';
      if (this.all.length === 1) {
        label = 'note';
      } else {
        label = 'notes';
      }
      $('note-count').innerHTML = 'This post has <a href="/note/history?post_id=' + this.post_id + '">' + this.all.length + ' ' + label + '</a>';
    } else {
      $('note-count').innerHTML = '';
    }
  }

  createButtonClick(e) {
    e.preventDefault();
    return User.run_login(false, this.create);
  }

  create() {
    var html, insertion_position, left, note, top;
    if (this.debug) {
      console.debug('notesManager.create');
    }
    this.show();
    insertion_position = this.getInsertionPosition(true);
    top = insertion_position[0];
    left = insertion_position[1];
    html = '';
    html += '<div class="note-box unsaved" style="width: 150px; height: 150px; ';
    html += 'top: ' + top + 'px; ';
    html += 'left: ' + left + 'px;" ';
    html += 'id="note-box-' + this.counter + '">';
    html += '<div class="note-corner" id="note-corner-' + this.counter + '"></div>';
    html += '</div>';
    html += '<div class="note-body" title="Click to edit" id="note-body-' + this.counter + '"></div>';
    $('note-container').insert({
      bottom: html
    });
    note = new Note(this.counter, true, '');
    this.all.push(note);
    this.counter -= 1;
  }

  getInsertionPosition(scale) {
    var image, ratio, rect, res;
    if (this.debug) {
      console.debug('notesManager.getInsertionPosition');
    }
    if (scale == null) {
      scale = false;
    }
    image = this.constructor.image();
    if (image == null) {
      return [0, 0];
    }
    rect = image.getBoundingClientRect();
    res = [rect.top, rect.left];
    // Position the edit box 20px from top left of the image while making sure
    // it's also inside the screen. When either left or top side is outside
    // the screen, the visible part of it starts from its top (or left) rect
    // but on the other direction (hence negative sign).
    res = res.map(function(x) {
      return -Math.min(x, 0) + 20;
    });
    if (scale) {
      ratio = this.constructor.ratio();
      res = res.map(function(x) {
        return x / ratio;
      });
    }
    return res;
  }

};
