// Generated by CoffeeScript 2.7.0
var Note;

import ClipRange from './clip_range';

import NotesManager from './notes_manager';

// The following are instance methods and variables
export default Note = class Note {
  constructor(id, is_new, raw_body) {
    var p;
    this.showEditBox = this.showEditBox.bind(this);
    this.bodyShow = this.bodyShow.bind(this);
    this.bodyHideTimer = this.bodyHideTimer.bind(this);
    this.bodyHide = this.bodyHide.bind(this);
    this.dragStart = this.dragStart.bind(this);
    this.dragStop = this.dragStop.bind(this);
    this.drag = this.drag.bind(this);
    this.editDragStart = this.editDragStart.bind(this);
    this.editDragStop = this.editDragStop.bind(this);
    this.editDrag = this.editDrag.bind(this);
    this.resizeStart = this.resizeStart.bind(this);
    this.resizeStop = this.resizeStop.bind(this);
    this.resize = this.resize.bind(this);
    this.save = this.save.bind(this);
    this.cancel = this.cancel.bind(this);
    this.remove = this.remove.bind(this);
    this.history = this.history.bind(this);
    if (notesManager.debug) {
      console.debug('Note#initialize (id=%d)', id);
    }
    this.id = id;
    this.is_new = is_new;
    this.document_observers = [];
    // Cache the elements
    this.elements = {
      box: $('note-box-' + this.id),
      corner: $('note-corner-' + this.id),
      body: $('note-body-' + this.id),
      image: $('image')
    };
    // Cache the dimensions
    this.fullsize = {
      left: this.elements.box.offsetLeft,
      top: this.elements.box.offsetTop,
      width: this.elements.box.clientWidth,
      height: this.elements.box.clientHeight
    };
    // Store the original values (in case the user clicks Cancel)
    this.old = {
      raw_body: raw_body,
      formatted_body: this.elements.body.innerHTML
    };
    for (p in this.fullsize) {
      this.old[p] = this.fullsize[p];
    }
    // Make the note translucent
    if (is_new) {
      this.elements.box.setOpacity(0.2);
    } else {
      this.elements.box.setOpacity(0.5);
    }
    if (is_new && raw_body === '') {
      this.bodyfit = true;
      this.elements.body.style.height = '100px';
    }
    // Attach the event listeners
    this.elements.box.observe('mousedown', this.dragStart);
    this.elements.box.observe('mouseout', this.bodyHideTimer);
    this.elements.box.observe('mouseover', this.bodyShow);
    this.elements.corner.observe('mousedown', this.resizeStart);
    this.elements.body.observe('mouseover', this.bodyShow);
    this.elements.body.observe('mouseout', this.bodyHideTimer);
    this.elements.body.observe('click', this.showEditBox);
    this.adjustScale();
  }

  textValue() {
    if (notesManager.debug) {
      console.debug('Note#textValue (id=%d)', this.id);
    }
    return this.old.raw_body.strip();
  }

  hideEditBox(e) {
    var boxid, editBox;
    if (notesManager.debug) {
      console.debug('Note#hideEditBox (id=%d)', this.id);
    }
    editBox = $('edit-box');
    if (editBox != null) {
      boxid = editBox.noteid;
      $('edit-box').stopObserving();
      $('note-save-' + boxid).stopObserving();
      $('note-cancel-' + boxid).stopObserving();
      $('note-remove-' + boxid).stopObserving();
      $('note-history-' + boxid).stopObserving();
      $('edit-box').remove();
    }
  }

  showEditBox(e) {
    var html, insertionPosition, left, top;
    if (notesManager.debug) {
      console.debug('Note#showEditBox (id=%d)', this.id);
    }
    this.hideEditBox(e);
    insertionPosition = notesManager.getInsertionPosition();
    top = insertionPosition[0];
    left = insertionPosition[1];
    html = '';
    html += '<div id="edit-box" style="top: ' + top + 'px; left: ' + left + 'px; position: absolute; visibility: visible; z-index: 100; background: white; border: 1px solid black; padding: 12px;">';
    html += '<form onsubmit="return false;" style="padding: 0; margin: 0;">';
    html += '<textarea rows="7" id="edit-box-text" style="width: 350px; margin: 2px 2px 12px 2px;">' + this.textValue() + '</textarea>';
    html += '<input type="submit" value="Save" name="save" id="note-save-' + this.id + '">';
    html += '<input type="submit" value="Cancel" name="cancel" id="note-cancel-' + this.id + '">';
    html += '<input type="submit" value="Remove" name="remove" id="note-remove-' + this.id + '">';
    html += '<input type="submit" value="History" name="history" id="note-history-' + this.id + '">';
    html += '</form>';
    html += '</div>';
    $('note-container').insert({
      bottom: html
    });
    $('edit-box').noteid = this.id;
    $('edit-box').observe('mousedown', this.editDragStart);
    $('note-save-' + this.id).observe('click', this.save);
    $('note-cancel-' + this.id).observe('click', this.cancel);
    $('note-remove-' + this.id).observe('click', this.remove);
    $('note-history-' + this.id).observe('click', this.history);
    $('edit-box-text').focus();
  }

  bodyShow(e) {
    var dw, h, hi, i, l, last, lo, w, x;
    if (notesManager.debug) {
      console.debug('Note#bodyShow (id=%d)', this.id);
    }
    if (this.dragging) {
      return;
    }
    if (this.hideTimer) {
      clearTimeout(this.hideTimer);
      this.hideTimer = null;
    }
    if (notesManager.noteShowingBody === this) {
      return;
    }
    if (notesManager.noteShowingBody) {
      notesManager.noteShowingBody.bodyHide();
    }
    notesManager.noteShowingBody = this;
    if (notesManager.zindex >= 9) {
      // don't use more than 10 layers (+1 for the body, which will always be above all notes)
      notesManager.zindex = 0;
      i = 0;
      while (i < notesManager.all.length) {
        notesManager.all[i].elements.box.style.zIndex = 0;
        ++i;
      }
    }
    this.elements.box.style.zIndex = ++notesManager.zindex;
    this.elements.body.style.zIndex = 10;
    this.elements.body.style.top = 0 + 'px';
    this.elements.body.style.left = 0 + 'px';
    dw = document.documentElement.scrollWidth;
    this.elements.body.style.visibility = 'hidden';
    this.elements.body.style.display = 'block';
    if (!this.bodyfit) {
      this.elements.body.style.height = 'auto';
      this.elements.body.style.minWidth = '140px';
      w = null;
      h = null;
      lo = null;
      hi = null;
      x = null;
      last = null;
      w = this.elements.body.offsetWidth;
      h = this.elements.body.offsetHeight;
      if (w / h < 1.6180339887) {
        // for tall notes (lots of text), find more pleasant proportions
        lo = 140;
        hi = 400;
        while (true) {
          last = w;
          x = (lo + hi) / 2;
          this.elements.body.style.minWidth = x + 'px';
          w = this.elements.body.offsetWidth;
          h = this.elements.body.offsetHeight;
          if (w / h < 1.6180339887) {
            lo = x;
          } else {
            hi = x;
          }
          if (!(lo < hi && w > last)) {
            break;
          }
        }
      } else if (this.elements.body.scrollWidth <= this.elements.body.clientWidth) {
        // for short notes (often a single line), make the box no wider than necessary
        // scroll test necessary for Firefox
        lo = 20;
        hi = w;
        while (true) {
          x = (lo + hi) / 2;
          this.elements.body.style.minWidth = x + 'px';
          if (this.elements.body.offsetHeight > h) {
            lo = x;
          } else {
            hi = x;
          }
          if (!(hi - lo > 4)) {
            break;
          }
        }
        if (this.elements.body.offsetHeight > h) {
          this.elements.body.style.minWidth = hi + 'px';
        }
      }
      if (Prototype.Browser.IE) {
        // IE7 adds scrollbars if the box is too small, obscuring the text
        if (this.elements.body.offsetHeight < 35) {
          this.elements.body.style.minHeight = '35px';
        }
        if (this.elements.body.offsetWidth < 47) {
          this.elements.body.style.minWidth = '47px';
        }
      }
      this.bodyfit = true;
    }
    this.elements.body.style.top = this.elements.box.offsetTop + this.elements.box.clientHeight + 5 + 'px';
    // keep the box within the document's width
    l = 0;
    e = this.elements.box;
    l += e.offsetLeft;
    while (e = e.offsetParent) {
      l += e.offsetLeft;
    }
    l += this.elements.body.offsetWidth + 10 - dw;
    if (l > 0) {
      this.elements.body.style.left = this.elements.box.offsetLeft - l + 'px';
    } else {
      this.elements.body.style.left = this.elements.box.offsetLeft + 'px';
    }
    this.elements.body.style.visibility = 'visible';
  }

  bodyHideTimer(e) {
    if (notesManager.debug) {
      console.debug('Note#bodyHideTimer (id=%d)', this.id);
    }
    this.hideTimer = setTimeout(this.bodyHide, 250);
  }

  bodyHide(e) {
    if (notesManager.debug) {
      console.debug('Note#bodyHide (id=%d)', this.id);
    }
    this.elements.body.hide();
    if (notesManager.noteShowingBody === this) {
      notesManager.noteShowingBody = null;
    }
  }

  addDocumentObserver(name, func) {
    document.observe(name, func);
    this.document_observers.push([name, func]);
  }

  clearDocumentObservers(name, handler) {
    var i, observer;
    i = 0;
    while (i < this.document_observers.length) {
      observer = this.document_observers[i];
      document.stopObserving(observer[0], observer[1]);
      ++i;
    }
    this.document_observers = [];
  }

  dragStart(e) {
    if (notesManager.debug) {
      console.debug('Note#dragStart (id=%d)', this.id);
    }
    this.addDocumentObserver('mousemove', this.drag);
    this.addDocumentObserver('mouseup', this.dragStop);
    this.addDocumentObserver('selectstart', function() {
      return false;
    });
    this.cursorStartX = e.pointerX();
    this.cursorStartY = e.pointerY();
    this.boxStartX = this.elements.box.offsetLeft;
    this.boxStartY = this.elements.box.offsetTop;
    this.boundsX = new ClipRange(5, this.elements.image.clientWidth - this.elements.box.clientWidth - 5);
    this.boundsY = new ClipRange(5, this.elements.image.clientHeight - this.elements.box.clientHeight - 5);
    this.dragging = true;
    this.bodyHide();
  }

  dragStop(e) {
    if (notesManager.debug) {
      console.debug('Note#dragStop (id=%d)', this.id);
    }
    this.clearDocumentObservers();
    this.cursorStartX = null;
    this.cursorStartY = null;
    this.boxStartX = null;
    this.boxStartY = null;
    this.boundsX = null;
    this.boundsY = null;
    this.dragging = false;
    this.bodyShow();
  }

  adjustScale() {
    var p, ratio;
    if (notesManager.debug) {
      console.debug('Note#adjustScale (id=%d)', this.id);
    }
    ratio = NotesManager.ratio();
    for (p in this.fullsize) {
      this.elements.box.style[p] = this.fullsize[p] * ratio + 'px';
    }
  }

  drag(e) {
    var left, ratio, top;
    left = this.boxStartX + e.pointerX() - this.cursorStartX;
    top = this.boxStartY + e.pointerY() - this.cursorStartY;
    left = this.boundsX.clip(left);
    top = this.boundsY.clip(top);
    this.elements.box.style.left = left + 'px';
    this.elements.box.style.top = top + 'px';
    ratio = NotesManager.ratio();
    this.fullsize.left = left / ratio;
    this.fullsize.top = top / ratio;
    e.stop();
  }

  editDragStart(e) {
    var node;
    if (notesManager.debug) {
      console.debug('Note#editDragStart (id=%d)', this.id);
    }
    node = e.element().nodeName;
    if (node !== 'FORM' && node !== 'DIV') {
      return;
    }
    this.addDocumentObserver('mousemove', this.editDrag);
    this.addDocumentObserver('mouseup', this.editDragStop);
    this.addDocumentObserver('selectstart', function() {
      return false;
    });
    this.elements.editBox = $('edit-box');
    this.cursorStartX = e.pointerX();
    this.cursorStartY = e.pointerY();
    this.editStartX = this.elements.editBox.offsetLeft;
    this.editStartY = this.elements.editBox.offsetTop;
    this.dragging = true;
  }

  editDragStop(e) {
    if (notesManager.debug) {
      console.debug('Note#editDragStop (id=%d)', this.id);
    }
    this.clearDocumentObservers();
    this.cursorStartX = null;
    this.cursorStartY = null;
    this.editStartX = null;
    this.editStartY = null;
    this.dragging = false;
  }

  editDrag(e) {
    var left, top;
    left = this.editStartX + e.pointerX() - this.cursorStartX;
    top = this.editStartY + e.pointerY() - this.cursorStartY;
    this.elements.editBox.style.left = left + 'px';
    this.elements.editBox.style.top = top + 'px';
    e.stop();
  }

  resizeStart(e) {
    if (notesManager.debug) {
      console.debug('Note#resizeStart (id=%d)', this.id);
    }
    this.cursorStartX = e.pointerX();
    this.cursorStartY = e.pointerY();
    this.boxStartWidth = this.elements.box.clientWidth;
    this.boxStartHeight = this.elements.box.clientHeight;
    this.boxStartX = this.elements.box.offsetLeft;
    this.boxStartY = this.elements.box.offsetTop;
    this.boundsX = new ClipRange(10, this.elements.image.clientWidth - this.boxStartX - 5);
    this.boundsY = new ClipRange(10, this.elements.image.clientHeight - this.boxStartY - 5);
    this.dragging = true;
    this.clearDocumentObservers();
    this.addDocumentObserver('mousemove', this.resize);
    this.addDocumentObserver('mouseup', this.resizeStop);
    e.stop();
    this.bodyHide();
  }

  resizeStop(e) {
    if (notesManager.debug) {
      console.debug('Note#resizeStop (id=%d)', this.id);
    }
    this.clearDocumentObservers();
    this.boxCursorStartX = null;
    this.boxCursorStartY = null;
    this.boxStartWidth = null;
    this.boxStartHeight = null;
    this.boxStartX = null;
    this.boxStartY = null;
    this.boundsX = null;
    this.boundsY = null;
    this.dragging = false;
    e.stop();
  }

  resize(e) {
    var height, ratio, width;
    width = this.boxStartWidth + e.pointerX() - this.cursorStartX;
    height = this.boxStartHeight + e.pointerY() - this.cursorStartY;
    width = this.boundsX.clip(width);
    height = this.boundsY.clip(height);
    this.elements.box.style.width = width + 'px';
    this.elements.box.style.height = height + 'px';
    ratio = NotesManager.ratio();
    this.fullsize.width = width / ratio;
    this.fullsize.height = height / ratio;
    e.stop();
  }

  save(e) {
    var p, params;
    e.preventDefault();
    if (notesManager.debug) {
      console.debug('Note#save (id=%d)', this.id);
    }
    for (p in this.fullsize) {
      this.old[p] = this.fullsize[p];
    }
    this.old.raw_body = $('edit-box-text').value;
    this.old.formatted_body = this.textValue();
    // FIXME: this is not quite how the note will look (filtered elems, <tn>...). the user won't input a <script> that only damages him, but it might be nice to "preview" the <tn> here
    this.elements.body.update(this.textValue());
    this.hideEditBox(e);
    this.bodyHide();
    this.bodyfit = false;
    params = {
      id: this.id,
      note: {
        x: this.old.left,
        y: this.old.top,
        width: this.old.width,
        height: this.old.height,
        body: this.old.raw_body
      }
    };
    if (this.is_new) {
      params.note.post_id = notesManager.post_id;
    }
    notice('Saving note...');
    jQuery.ajax('/note/update.json', {
      data: params,
      dataType: 'json',
      method: 'POST'
    }).done((resp) => {
      notice('Note saved');
      if (resp.old_id < 0) {
        this.is_new = false;
        this.id = resp.new_id;
        this.elements.box.id = `note-box-${this.id}`;
        this.elements.body.id = `note-body-${this.id}`;
        this.elements.corner.id = `note-corner-${this.id}`;
      }
      this.elements.body.innerHTML = resp.formatted_body;
      this.elements.box.setOpacity(0.5);
      return this.elements.box.removeClassName('unsaved');
    }).fail((xhr) => {
      var ref, ref1;
      notice(`Error: ${(ref = (ref1 = xhr.responseJSON) != null ? ref1.reason : void 0) != null ? ref : 'unknown error'}`);
      return this.elements.box.addClassName('unsaved');
    });
  }

  cancel(e) {
    var p, ratio;
    if (notesManager.debug) {
      console.debug('Note#cancel (id=%d)', this.id);
    }
    this.hideEditBox(e);
    this.bodyHide();
    ratio = NotesManager.ratio();
    for (p in this.fullsize) {
      this.fullsize[p] = this.old[p];
      this.elements.box.style[p] = this.fullsize[p] * ratio + 'px';
    }
    this.elements.body.innerHTML = this.old.formatted_body;
    e.stop();
  }

  removeCleanup() {
    var allTemp, i;
    if (notesManager.debug) {
      console.debug('Note#removeCleanup (id=%d)', this.id);
    }
    this.elements.box.remove();
    this.elements.body.remove();
    allTemp = [];
    i = 0;
    while (i < notesManager.all.length) {
      if (notesManager.all[i].id !== this.id) {
        allTemp.push(notesManager.all[i]);
      }
      ++i;
    }
    notesManager.all = allTemp;
    notesManager.updateNoteCount();
  }

  remove(e) {
    e.preventDefault();
    if (notesManager.debug) {
      console.debug('Note#remove (id=%d)', this.id);
    }
    this.hideEditBox(e);
    this.bodyHide();
    if (this.is_new) {
      this.removeCleanup();
      notice('Note removed');
    } else {
      notice('Removing note...');
      jQuery.ajax('/note/update.json', {
        data: {
          id: this.id,
          note: {
            is_active: 0
          }
        },
        dataType: 'json',
        method: 'POST'
      }).done(() => {
        notice('Note removed');
        return this.removeCleanup();
      }).fail((xhr) => {
        var ref, ref1;
        return notice(`Error: ${(ref = (ref1 = xhr.responseJSON) != null ? ref1.reason : void 0) != null ? ref : 'unknown error'}`);
      });
    }
  }

  history(e) {
    if (notesManager.debug) {
      console.debug('Note#history (id=%d)', this.id);
    }
    this.hideEditBox(e);
    if (this.is_new) {
      notice('This note has no history');
    } else {
      location.href = '/history?search=notes:' + this.id;
    }
    e.stop();
  }

};
