// Generated by CoffeeScript 2.7.0
let $, Pool;

$ = jQuery;

export default Pool = class Pool {
  constructor () {
    this.register = this.register.bind(this);
    this.register_pools = this.register_pools.bind(this);
    this.change_sequence = this.change_sequence.bind(this);
    this.pools = {};
  }

  register (pool) {
    return this.pools[pool.id] = pool;
  }

  register_pools (pools) {
    let i, len, pool, results;
    if (pools == null) {
      return;
    }
    results = [];
    for (i = 0, len = pools.length; i < len; i++) {
      pool = pools[i];
      results.push(this.register(pool));
    }
    return results;
  }

  register_pool_posts (pool_posts, posts) {
    let i, len, pool_post, post, results;
    // pool_post is an array of individual posts in pools.  It contains only data for posts
    // listed in posts.

    // This means that a pool_post not existing in pool_posts only indicates the post is
    // no longer in the pool only if that post is listed in posts.

    // We don't need to clear the pool_posts entry in posts, because the posts registered
    // by this function are always newly registered via Post.register_resp; pool_posts is
    // already empty.
    results = [];
    for (i = 0, len = pool_posts.length; i < len; i++) {
      pool_post = pool_posts[i];
      post = Post.posts.get(pool_post.post_id);
      if (post == null) {
        continue;
      }
      if (post.pool_posts == null) {
        post.pool_posts = {};
      }
      results.push(post.pool_posts[pool_post.pool_id] = pool_post);
    }
    return results;
  }

  can_edit_pool (pool) {
    if (!User.is_member_or_higher()) {
      return false;
    }
    return pool.is_public || pool.user_id === User.get_current_user_id();
  }

  add_post (post_id, pool_id) {
    notice('Adding to pool...');
    return $.ajax('/pool/add_post.json', {
      method: 'POST',
      data: {
        post_id,
        pool_id
      },
      dataType: 'json'
    }).done(function () {
      return notice('Post added to pool');
    }).fail(function (xhr) {
      let reason, ref, ref1;
      reason = (ref = (ref1 = xhr.responseJSON) != null ? ref1.reason : void 0) != null ? ref : 'unknown error';
      return notice(`Error: ${reason}`);
    });
  }

  remove_post (post_id, pool_id) {
    let callback;
    callback = function () {
      notice('Post removed from pool');
      $(`#p${post_id}`).addClass('deleted');
      return $(`#pool${pool_id}`).remove();
    };
    return Post.make_request('/pool/remove_post.json', {
      post_id,
      pool_id
    }, callback);
  }

  transfer_post (old_post_id, new_post_id, pool_id, sequence) {
    let callback;
    callback = function () {
      notice('Pool post transferred to parent');
      // We might be on the parent or child, which will do different things to
      // the pool status display.  Just reload the page.
      return document.location.reload();
    };
    return Post.update_batch([
      {
        id: old_post_id,
        tags: `-pool:${pool_id}`,
        old_tags: ''
      },
      {
        id: new_post_id,
        tags: `pool:${pool_id}:${sequence}`,
        old_tags: ''
      }
    ], callback);
  }

  detach_post (post_id, pool_id, is_parent) {
    let callback;
    callback = function () {
      notice('Post detached');
      if (is_parent) {
        return $(`#pool-detach-${pool_id}-${post_id}`).remove();
      } else {
        return $(`#pool-${pool_id}`).remove();
      }
    };
    return Post.update_batch([
      {
        id: post_id,
        tags: `-pool:${pool_id}`,
        old_tags: ''
      }
    ], callback);
  }

  post_pretty_sequence (sequence) {
    if (sequence.match(/^\d/)) {
      return `#${sequence}`;
    } else {
      return '"' + sequence + '"';
    }
  }

  change_sequence (post_id, pool_id, old_sequence) {
    let callback, new_sequence;
    new_sequence = prompt('Please enter the new page number:', old_sequence);
    if (new_sequence == null) {
      return;
    }
    if (new_sequence.indexOf(' ') !== -1) {
      notice('Invalid page number');
      return;
    }
    callback = () => {
      notice('Post updated');
      return $(`#pool-seq-${pool_id}`).text(this.post_pretty_sequence(new_sequence));
    };
    return Post.update_batch([
      {
        id: post_id,
        tags: `pool:${pool_id}:${new_sequence}`,
        old_tags: ''
      }
    ], callback);
  }
};
