// Generated by CoffeeScript 2.7.0
let PostUploadForm;

export default PostUploadForm = class PostUploadForm {
  constructor (form, progress) {
    let SupportsFormData, XHRLevel2;
    this.document_keydown_event = this.document_keydown_event.bind(this);
    this.click_cancel = this.click_cancel.bind(this);
    this.form_submit_event = this.form_submit_event.bind(this);
    XHRLevel2 = 'XMLHttpRequest' in window && ((new XMLHttpRequest()).upload != null);
    SupportsFormData = 'FormData' in window;
    if (!XHRLevel2 || !SupportsFormData) {
      return;
    }
    this.form_element = form;
    this.cancel_element = this.form_element.down('.cancel');
    this.progress = progress;
    this.document_title = document.documentElement.down('TITLE');
    this.document_title_orig = this.document_title.textContent;
    this.current_request = null;
    this.form_element.on('submit', this.form_submit_event);
    this.cancel_element.on('click', this.click_cancel);
    document.on('keydown', this.document_keydown_event);
  }

  set_progress (f) {
    let percent;
    percent = f * 100;
    this.progress.down('.upload-progress-bar-fill').style.width = percent + '%';
    this.document_title.textContent = this.document_title_orig + ' (' + percent.toFixed(0) + '%)';
  }

  request_starting () {
    this.form_element.down('.submit').hide();
    this.cancel_element.show();
    this.progress.show();
    document.documentElement.addClassName('progress');
  }

  request_ending () {
    this.form_element.down('.submit').show();
    this.cancel_element.hide();
    this.progress.hide();
    this.document_title.textContent = this.document_title_orig;
    document.documentElement.removeClassName('progress');
  }

  document_keydown_event (e) {
    let key;
    key = e.charCode;
    if (!key) {
      key = e.keyCode;
    }
    // Opera
    if (key !== Event.KEY_ESC) {
      return;
    }
    this.cancel();
  }

  click_cancel (e) {
    e.stop();
    this.cancel();
  }

  form_submit_event (e) {
    let formData, onprogress, post_file;
    // This submit may have been stopped by User.run_login_onsubmit.
    if (e.stopped) {
      return;
    }
    if (this.current_request != null) {
      e.preventDefault();
      return;
    }
    $('post-exists').hide();
    $('post-upload-error').hide();
    // If the files attribute isn't supported, or we have no file (source upload), use regular
    // form submission.
    post_file = $('post_file');
    if ((post_file.files == null) || post_file.files.length === 0) {
      return;
    }
    e.stop();
    this.set_progress(0);
    this.request_starting();
    formData = new FormData(this.form_element);
    onprogress = (e) => {
      let done, progress, total;
      done = e.loaded;
      total = e.total;
      progress = total > 0 ? done / total : 1;
      return this.set_progress(progress);
    };
    this.current_request = jQuery.ajax('/post/create.json', {
      contentType: false,
      data: formData,
      dataType: 'json',
      method: 'POST',
      processData: false,
      xhr: () => {
        let xhr;
        xhr = new XMLHttpRequest();
        xhr.upload.addEventListener('progress', onprogress);
        return xhr;
      }
    }).always(() => {
      this.current_request = null;
      return this.request_ending();
    }).done((json) => {
      // If a post/similar link was given and similar results exists, go to them.  Otherwise,
      // go to the new post.
      return window.location.href = json.similar_location && json.has_similar_hits ? json.similar_location : json.location;
    }).fail((xhr) => {
      let a, errorLabel, json, ref;
      json = xhr.responseJSON;
      if ((json != null) && json.location) {
        a = document.querySelector('#post-exists-link');
        a.text = `post #${json.post_id}`;
        a.href = json.location;
        document.querySelector('#post-exists').style.display = '';
        return;
      }
      errorLabel = document.querySelector('#post-upload-error');
      errorLabel.text = (ref = json != null ? json.reason : void 0) != null ? ref : 'unknown error';
      return errorLabel.style.display = '';
    });
  }

  // Cancel the running request, if any.
  cancel () {
    if (this.current_request == null) {
      return;
    }
    // Don't clear this.current_request; it'll be done by the onComplete callback.
    this.current_request.abort();
  }
};
