// Generated by CoffeeScript 2.7.0
var PostModeMenu, get_style_for_mode;

get_style_for_mode = function(s) {
  if (s === 'view') {
    return {
      background: ''
    };
  } else if (s === 'edit') {
    return {
      background: '#3A3'
    };
  } else if (s === 'rating-q') {
    return {
      background: '#AAA'
    };
  } else if (s === 'rating-s') {
    return {
      background: '#6F6'
    };
  } else if (s === 'rating-e') {
    return {
      background: '#F66'
    };
  } else if (s === 'vote') {
    return {
      background: '#FAA'
    };
  } else if (s === 'lock-rating') {
    return {
      background: '#AA3'
    };
  } else if (s === 'lock-note') {
    return {
      background: '#3AA'
    };
  } else if (s === 'approve') {
    return {
      background: '#26A'
    };
  } else if (s === 'flag') {
    return {
      background: '#F66'
    };
  } else if (s === 'add-to-pool') {
    return {
      background: '#26A'
    };
  } else if (s === 'apply-tag-script') {
    return {
      background: '#A3A'
    };
  } else if (s === 'reparent-quick') {
    return {
      background: '#CCA'
    };
  } else if (s === 'remove-from-pool') {
    return {
      background: '#CCA'
    };
  } else if (s === 'reparent') {
    return {
      background: '#0C0'
    };
  } else if (s === 'dupe') {
    return {
      background: '#0C0'
    };
  } else {
    return {
      background: '#AFA'
    };
  }
};

export default PostModeMenu = class PostModeMenu {
  constructor() {
    this.dragging_active = false;
    this.dragging_from_post = null;
    this.dragging_hash = null;
    this.dragging_list = null;
    this.mode = 'view';
  }

  init(pool_id) {
    var ref, ref1;
    // If pool_id isn't null, it's the pool that we're currently searching for.
    this.pool_id = pool_id;
    if (Cookie.get('mode') === '') {
      Cookie.put('mode', 'view');
      if ((ref = $('mode')) != null) {
        ref.value = 'view';
      }
    } else {
      if ((ref1 = $('mode')) != null) {
        ref1.value = Cookie.get('mode');
      }
    }
    this.vote_score = Cookie.get('vote');
    if (this.vote_score === '') {
      this.vote_score = 1;
      Cookie.put('vote', this.vote_score);
    } else {
      this.vote_score = +this.vote_score;
    }
    Post.posts.each((p) => {
      var post, post_id, span;
      post_id = p[0];
      post = p[1];
      span = $('p' + post.id);
      if (span == null) {
        return;
      }
      // Use post_id here, not post, since the post object can be replaced later after updates.
      span.down('A').observe('click', (e) => {
        this.click(e, post_id);
      });
      span.down('A').observe('mousedown', (e) => {
        this.post_mousedown(e, post_id);
      });
      span.down('A').observe('mouseover', (e) => {
        this.post_mouseover(e, post_id);
      });
      span.down('A').observe('mouseout', (e) => {
        this.post_mouseout(e, post_id);
      });
      span.down('A').observe('mouseup', (e) => {
        this.post_mouseup(e, post_id);
      });
    });
    document.observe('mouseup', (e) => {
      this.post_mouseup(e, null);
    });
    Event.observe(window, 'pagehide', (e) => {
      this.post_end_drag();
    });
    this.change();
  }

  set_vote(score) {
    this.vote_score = score;
    Cookie.put('vote', this.vote_score);
    Post.update_vote_widget('vote-menu', this.vote_score);
  }

  change() {
    var s;
    if (!$('mode')) {
      return;
    }
    s = $F('mode');
    Cookie.put('mode', s, 7);
    this.mode = s;
    if (s !== 'edit') {
      $('quick-edit').hide();
    }
    if (s !== 'apply-tag-script') {
      $('edit-tag-script').hide();
      Post.reset_tag_script_applied();
    }
    if (s === 'vote') {
      Post.update_vote_widget('vote-menu', this.vote_score);
      $('vote-score').show();
    } else if (s === 'apply-tag-script') {
      $('edit-tag-script').show();
      $('edit-tag-script').focus();
    }
  }

  click(event, post_id) {
    var s;
    s = $('mode');
    if (!s) {
      return;
    }
    if (s.value === 'view') {
      return true;
    }
    if (s.value === 'edit') {
      post_quick_edit.show(post_id);
    } else if (s.value === 'vote') {
      Post.vote(post_id, this.vote_score);
    } else if (s.value === 'rating-q') {
      Post.update_batch([
        {
          id: post_id,
          rating: 'questionable'
        }
      ]);
    } else if (s.value === 'rating-s') {
      Post.update_batch([
        {
          id: post_id,
          rating: 'safe'
        }
      ]);
    } else if (s.value === 'rating-e') {
      Post.update_batch([
        {
          id: post_id,
          rating: 'explicit'
        }
      ]);
    } else if (s.value === 'reparent') {
      if (post_id === window.id) {
        return false;
      }
      TagScript.run(post_id, 'parent:' + id);
    } else if (s.value === 'dupe') {
      if (post_id === window.id) {
        return false;
      }
      TagScript.run(post_id, 'duplicate parent:' + window.id);
    } else if (s.value === 'lock-rating') {
      Post.update_batch([
        {
          id: post_id,
          is_rating_locked: '1'
        }
      ]);
    } else if (s.value === 'lock-note') {
      Post.update_batch([
        {
          id: post_id,
          is_note_locked: '1'
        }
      ]);
    } else if (s.value === 'flag') {
      Post.flag(post_id);
    } else if (s.value === 'approve') {
      Post.approve(post_id);
    } else if (s.value === 'add-to-pool') {
      Pool.add_post(post_id, 0);
    } else if (s.value === 'remove-from-pool') {
      Pool.remove_post(post_id, this.pool_id);
    }
    event.stopPropagation();
    event.preventDefault();
  }

  post_add_to_hovered_list(post_id) {
    var element;
    element = element = $$('#p' + post_id + ' > .directlink');
    if (element.length > 0) {
      element[0].addClassName('tag-script-applied');
      Post.applied_list.push(element[0]);
    }
    if (!this.dragging_hash.get(post_id)) {
      this.dragging_hash.set(post_id, true);
      this.dragging_list.push(post_id);
    }
  }

  post_mousedown(event, post_id) {
    if (event.button !== 0) {
      return;
    }
    if (this.mode === 'reparent-quick') {
      this.dragging_from_post = post_id;
      this.post_begin_drag();
    } else if (this.mode === 'apply-tag-script') {
      Post.reset_tag_script_applied();
      this.dragging_from_post = post_id;
      this.dragging_list = new Array();
      this.dragging_hash = new Hash();
      this.post_add_to_hovered_list(post_id);
    } else {
      return;
    }
    // Prevent the mousedown from being processed; this keeps it from turning into
    // a real drag action, which will suppress our mouseover/mouseout messages.  We
    // only do this when the tag script is enabled, so we don't mess with regular
    // clicks.
    event.preventDefault();
    event.stopPropagation();
  }

  post_begin_drag(type) {
    document.body.addClassName('dragging-to-post');
  }

  post_end_drag() {
    document.body.removeClassName('dragging-to-post');
    this.dragging_from_post = null;
  }

  post_mouseup(event, post_id) {
    var tag_script;
    if (event.button !== 0) {
      return;
    }
    if (!this.dragging_from_post) {
      return;
    }
    if (this.mode === 'reparent-quick') {
      if (post_id) {
        notice('Updating post');
        Post.update_batch([
          {
            id: this.dragging_from_post,
            parent_id: post_id
          }
        ]);
      }
      this.post_end_drag();
      return;
    } else if (this.mode === 'apply-tag-script') {
      if (post_id) {
        return;
      }
      // We clicked or dragged some posts to apply a tag script; process it.
      tag_script = TagScript.TagEditArea.value;
      TagScript.run(this.dragging_list, tag_script);
      this.dragging_from_post = null;
      this.dragging_active = false;
      this.dragging_list = null;
      this.dragging_hash = null;
    }
  }

  post_mouseover(event, post_id) {
    var post, style;
    post = $('p' + post_id);
    style = get_style_for_mode(this.mode);
    post.down('span').setStyle(style);
    if (this.mode !== 'apply-tag-script') {
      return;
    }
    if (!this.dragging_from_post) {
      return;
    }
    if (post_id !== this.dragging_from_post) {
      this.dragging_active = true;
    }
    this.post_add_to_hovered_list(post_id);
  }

  post_mouseout(event, post_id) {
    var post;
    post = $('p' + post_id);
    post.down('span').setStyle({
      background: ''
    });
  }

  apply_tag_script_to_all_posts() {
    var post_ids, tag_script;
    tag_script = TagScript.TagEditArea.value;
    post_ids = Post.posts.inject([], function(list, pair) {
      list.push(pair[0]);
      return list;
    });
    TagScript.run(post_ids, tag_script);
  }

};
