// Generated by CoffeeScript 2.7.0
var PostQuickEdit;

export default PostQuickEdit = class PostQuickEdit {
  constructor(selector) {
    this.onCancelClick = this.onCancelClick.bind(this);
    this.onInputKeydown = this.onInputKeydown.bind(this);
    this.onSubmit = this.onSubmit.bind(this);
    this.container = document.querySelector(selector);
    this.container.querySelector('form').addEventListener('submit', this.onSubmit);
    this.container.querySelector('.cancel').addEventListener('click', this.onCancelClick);
    this.container.querySelector('#post_tags').addEventListener('keydown', this.onInputKeydown);
  }

  hide() {
    $(this.container).hide();
    return Post.hover_info_pin(null);
  }

  onCancelClick(e) {
    e.preventDefault();
    this.hide();
  }

  onInputKeydown(e) {
    switch (e.keyCode) {
      case 13: // enter
        this.onSubmit(e);
        break;
      case 27: // escape
        e.preventDefault();
        this.hide();
    }
  }

  onSubmit(e) {
    var postData;
    e.preventDefault();
    this.hide();
    postData = {
      id: this.postId,
      tags: this.container.querySelector('#post_tags').value,
      old_tags: this.oldTags
    };
    Post.update_batch([postData], function() {
      return notice('Post updated');
    });
  }

  show(postId) {
    var inputBox, post;
    Post.hover_info_pin(postId);
    post = Post.posts.get(postId);
    this.postId = postId;
    this.oldTags = post.tags.join(' ');
    $(this.container).show();
    inputBox = this.container.querySelector('#post_tags');
    inputBox.value = `${this.oldTags} rating:${post.rating.substr(0, 1)} `;
    return inputBox.focus();
  }

};
