// Generated by CoffeeScript 2.7.0
let $, PostShowTabs;

$ = jQuery;

export default PostShowTabs = class PostShowTabs {
  constructor () {
    this.initialize = this.initialize.bind(this);
    this.showEditTab = this.showEditTab.bind(this);
    this.showCommentsTab = this.showCommentsTab.bind(this);
    $(this.initialize);
  }

  initialize () {
    this.editTab = $('#edit');
    this.commentsTab = $('#comments');
    $('.js-posts-show-edit-tab').click(this.showEditTab);
    $('.js-posts-show-comments-tab').click(this.showCommentsTab);
    if ($('.js-posts-show-edit-tab').length > 0 && $('.js-posts-show-comments-tab').length > 0 && Cookies.get('show_defaults_to_edit') === '1' && window.location.hash !== '#comments' && !window.location.hash.match(/^#c[0-9]+$/)) {
      this.editTab.show();
      return this.commentsTab.hide();
    }
  }

  showEditTab (e) {
    e.preventDefault();
    this.editTab.show();
    this.commentsTab.hide();
    Cookies.set('show_defaults_to_edit', 1);
    return $('#post_tags').focus();
  }

  showCommentsTab (e) {
    e.preventDefault();
    this.editTab.hide();
    this.commentsTab.show();
    Cookies.set('show_defaults_to_edit', 0);
    return $('#comments textarea').focus();
  }
};
