// Generated by CoffeeScript 2.7.0
import PreloadContainer from './preload_container';

let $, PreloadPosts;

$ = jQuery;

// Parse `.js-preload-posts` and preload the specified non-blacklisted posts
// The JSON should be an array of object `{ id, url }`.
export default PreloadPosts = class PreloadPosts {
  constructor () {
    this.exec = this.exec.bind(this);
    this.getUrlsFromDocument = this.getUrlsFromDocument.bind(this);
    this.getUrlsFromJson = this.getUrlsFromJson.bind(this);
    this.urls = new Set();
    $(() => {
      return this.exec();
    });
  }

  exec () {
    let container;
    this.getUrlsFromDocument();
    if (this.urls.size === 0) {
      return;
    }
    container = new PreloadContainer();
    this.urls.forEach((url) => {
      return container.preload(url);
    });
    return this.urls.clear();
  }

  getUrlsFromDocument () {
    let i, len, postsJson, ref, results;
    ref = document.querySelectorAll('.js-preload-posts');
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      postsJson = ref[i];
      this.getUrlsFromJson(JSON.parse(postsJson.text));
      results.push(postsJson.remove());
    }
    return results;
  }

  getUrlsFromJson (json) {
    let i, len, post, results;
    results = [];
    for (i = 0, len = json.length; i < len; i++) {
      post = json[i];
      if (!Post.is_blacklisted(post.id)) {
        results.push(this.urls.add(post.url));
      }
    }
    return results;
  }
};
