// Generated by CoffeeScript 2.7.0
import {
  removeImageElement
} from 'src/utils/image';

let PreloadContainer;

export default PreloadContainer = class PreloadContainer {
  constructor () {
    this.cancelPreload = this.cancelPreload.bind(this);
    this.destroy = this.destroy.bind(this);
    this.getAll = this.getAll.bind(this);
    this.onImageCompleteEvent = this.onImageCompleteEvent.bind(this);
    this.preload = this.preload.bind(this);
    this.container = document.createElement('div');
    this.container.style.display = 'none';
    document.body.appendChild(this.container);
  }

  cancelPreload (img) {
    return removeImageElement(img);
  }

  destroy () {
    return this.container.remove();
  }

  getAll () {
    return this.container.children;
  }

  onImageCompleteEvent (event) {
    let element;
    // TODO: change to native .remove() once PrototypeJS is removed
    element = event.target;
    if (element.parentNode != null) {
      return element.remove();
    }
  }

  preload (url) {
    let img;
    img = document.createElement('img');
    img.addEventListener('load', this.onImageCompleteEvent);
    img.addEventListener('error', this.onImageCompleteEvent);
    img.src = url;
    this.container.appendChild(img);
    return img;
  }
};
