// Generated by CoffeeScript 2.7.0
var $, RelatedTags;

$ = jQuery;

export default RelatedTags = class RelatedTags {
  constructor() {
    this.recentTags = this.recentTags.bind(this);
    this.myTags = this.myTags.bind(this);
    this.initialize = this.initialize.bind(this);
    this.parseTags = this.parseTags.bind(this);
    this.getTags = this.getTags.bind(this);
    this.refreshList = this.refreshList.bind(this);
    this.highlightList = this.highlightList.bind(this);
    this.buildList = this.buildList.bind(this);
    this.fetchStart = this.fetchStart.bind(this);
    this.fetchArtistSuccess = this.fetchArtistSuccess.bind(this);
    this.fetchSuccess = this.fetchSuccess.bind(this);
    this.toggleTag = this.toggleTag.bind(this);
    this.run = this.run.bind(this);
    $(this.initialize);
  }

  recentTags() {
    return this.parseTags(Cookies.get("recent_tags"));
  }

  myTags() {
    return this.parseTags(Cookies.get("my_tags"));
  }

  artistSource() {
    return $("#post_source").val();
  }

  source() {
    return $("#post_tags");
  }

  target() {
    return $("#related");
  }

  tagUrl(tag) {
    return Moebooru.path(`/post?tags=${encodeURIComponent(tag)}`);
  }

  initialize() {
    var $autoload;
    if (!(this.source().length && this.target().length)) {
      return;
    }
    $("[data-toggle='related-tags']").click(this.run);
    this.target().on("click", "a", this.toggleTag);
    this.source().on("input keyup", this.highlightList);
    $autoload = $(".js-related-tags--autoload");
    if ($autoload.length) {
      return $autoload.click();
    } else {
      return this.refreshList();
    }
  }

  parseTags(tagsString) {
    return (tagsString || "").match(/\S+/g) || [];
  }

  getTags() {
    var selectFrom, selectTo, selectionEnd, selectionStart, source, tags;
    source = this.source();
    selectFrom = source[0].selectionStart;
    selectTo = source[0].selectionEnd;
    tags = source.val();
    if (tags.length !== 0 && selectFrom !== 0 && selectFrom !== tags.length) {
      selectionStart = tags.slice(0, selectFrom).lastIndexOf(" ");
      selectionEnd = tags.indexOf(" ", selectTo);
      if (selectionStart === -1) {
        selectionStart = 0;
      }
      if (selectionEnd === -1) {
        selectionEnd = void 0;
      }
      tags = tags.slice(selectionStart, selectionEnd);
    }
    return tags;
  }

  refreshList(extra) {
    var buf, tags, title;
    buf = this.target().empty();
    if (this.myTags().length) {
      buf.append(this.buildList("My Tags", this.myTags()));
    }
    if (this.recentTags().length) {
      buf.append(this.buildList("Recent Tags", this.recentTags()));
    }
    for (title in extra) {
      tags = extra[title];
      if (tags.length > 0) {
        buf.append(this.buildList(title, tags));
      }
    }
    return this.highlightList();
  }

  highlightList() {
    var highlightedTags, i, j, len, len1, ref, ref1, results, t, tagLink;
    highlightedTags = {};
    ref = this.parseTags(this.source().val());
    for (i = 0, len = ref.length; i < len; i++) {
      t = ref[i];
      highlightedTags[t] = true;
    }
    ref1 = document.querySelectorAll('.js-related_tags--tag_link');
    results = [];
    for (j = 0, len1 = ref1.length; j < len1; j++) {
      tagLink = ref1[j];
      if (highlightedTags[tagLink.dataset.tag] != null) {
        results.push(tagLink.classList.add('highlighted'));
      } else {
        results.push(tagLink.classList.remove('highlighted'));
      }
    }
    return results;
  }

  buildList(title, tags) {
    var $tagLink, buf, i, len, ref, tag, tagName, tagsList;
    buf = $("<div>").addClass("tag-column");
    buf.append($("<h6>").text(title.replace(/_/g, " ")));
    tagsList = $("<ul>");
    ref = tags.sort();
    for (i = 0, len = ref.length; i < len; i++) {
      tag = ref[i];
      tagName = tag.replace(/_/g, " ");
      $tagLink = $("<a>").text(tagName).attr({
        href: this.tagUrl(tag)
      }).attr('data-tag', tag).addClass('js-related_tags--tag_link');
      tagsList.append($('<li>').append($tagLink));
    }
    return buf.append(tagsList);
  }

  fetchStart() {
    return this.target().html($("<em>").text("Fetching..."));
  }

  fetchArtistSuccess(data) {
    var artist;
    return this.refreshList({
      "Artist": (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = data.length; i < len; i++) {
          artist = data[i];
          results.push(artist.name);
        }
        return results;
      })()
    });
  }

  fetchSuccess(data) {
    var name, tag, tags, tagsCollection;
    tagsCollection = {};
    for (name in data) {
      tags = data[name];
      tagsCollection[name] = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = tags.length; i < len; i++) {
          tag = tags[i];
          results.push(tag[0]);
        }
        return results;
      })();
    }
    return this.refreshList(tagsCollection);
  }

  toggleTag(e) {
    var currentTags, jumpToEnd, newVal, tagName;
    e.preventDefault();
    tagName = $(e.target).text().replace(/\s/g, "_");
    currentTags = this.source().val();
    jumpToEnd = this.source()[0].selectionStart === currentTags.length;
    if ($(e.target).hasClass("highlighted")) {
      newVal = currentTags.replace(tagName, "");
    } else {
      newVal = `${currentTags} ${tagName}`;
    }
    newVal = `${newVal.trim().replace(/\s/g, " ")} `;
    if (newVal === " ") {
      newVal = "";
    }
    this.source().val(newVal);
    if (jumpToEnd) {
      this.source()[0].selectionStart = newVal.length;
    }
    this.highlightList();
    return this.source().focus();
  }

  run(e) {
    var data, doneCallback, source, tags, type, url;
    e.preventDefault();
    tags = this.getTags();
    type = $(e.target).data("type");
    if (type === "artist-url") {
      source = this.artistSource() || "";
      if (!(source.length && source.match(/^https?:\/\//))) {
        return;
      }
      url = Moebooru.path("/artist.json");
      data = {
        url: source,
        limit: 10
      };
      doneCallback = this.fetchArtistSuccess;
    } else {
      if (type === "all") {
        type = null;
      }
      if (!tags.length) {
        return;
      }
      url = Moebooru.path("/tag/related.json");
      data = {
        type: type,
        tags: tags
      };
      doneCallback = this.fetchSuccess;
    }
    this.fetchStart();
    return $.ajax(url, {
      data: data
    }).done(doneCallback);
  }

};
