// Generated by CoffeeScript 2.7.0
import DragElement from 'src/classes/drag_element';

let SwipeHandler;

export default SwipeHandler = class SwipeHandler {
  constructor (element) {
    this.startdrag = this.startdrag.bind(this);
    this.ondrag = this.ondrag.bind(this);
    this.element = element;
    this.dragger = new DragElement(element, {
      ondrag: this.ondrag,
      onstartdrag: this.startdrag
    });
  }

  startdrag () {
    this.swiped_horizontal = false;
    this.swiped_vertical = false;
  }

  ondrag (e) {
    if (!this.swiped_horizontal) {
      // XXX: need a guessed DPI
      if (Math.abs(e.aX) > 100) {
        this.element.fire('swipe:horizontal', {
          right: e.aX > 0
        });
        this.swiped_horizontal = true;
      }
    }
    if (!this.swiped_vertical) {
      if (Math.abs(e.aY) > 100) {
        this.element.fire('swipe:vertical', {
          down: e.aY > 0
        });
        this.swiped_vertical = true;
      }
    }
  }

  destroy () {
    this.dragger.destroy();
  }
};
