// Generated by CoffeeScript 2.7.0
// From a tag string, eg. "1`tagme`alias`alias2`", retrieve the tag name "tagme".
let TagCompletion, get_tag_from_string, join_data, split_data;

get_tag_from_string = function (tag_string) {
  let m;
  m = tag_string.match(/\d+`([^`]*)`.*/);
  if (!m) {
    throw 'Unparsable cached tag: \'' + tag_string + '\'';
  }
  return m[1];
};

// Like string.split, but rather than each item of data being separated by the separator,
// each item of data ends in the separator; that is, the final item is followed by the
// separator.

// "a b c " -> ["a", "b", "c"].

// If the final item doesn't end in the separator, throw an exception.
split_data = function (str, separator) {
  let result;
  result = str.split(separator);
  if (result.length !== 0) {
    if (result[result.length - 1] !== '') {
      throw 'String doesn\'t end in separator';
    }
    result.pop();
  }
  return result;
};

join_data = function (items, separator) {
  if (items.length === 0) {
    return '';
  }
  return items.join(separator) + separator;
};

// The tag blob looks like this:

// 1:tagme 2:fixed

// where the initial number is the tag type, and a space after each tag is guaranteed, including
// after the final one.  Spaces and colons are disallowed in tags, so they don't need escaping.
// This can be searched quickly with regexes:

// ':tagme '   - whole tag match
// ':tag'      - tag prefix match
// ':t[^ ]*g'  - substring match
// ':[^ ]*me '  - suffix match
// ':[^ ]*t[^ ]*g[^ ]*m' - ordered character match
export default TagCompletion = class TagCompletion {
  constructor () {
    let current_version;
    this.init = this.init.bind(this);
    /*
     * If cached data is available, load it.  If the cached data is out of date, run an
     * update asynchronously.  Return true if data is available and tag completions may
     * be done, whether or not the data is current.  Call onComplete when up-to-date tag
     * data is available; if the current cached data is known to be current, it will be
     * called before this function returns.
     *
     * If this is called multiple times before the tag load completes, the data will only be loaded
     * once, but all callbacks will be called.
     */
    this.load_data = this.load_data.bind(this);
    // When form is submitted, call add_recent_tags_from_update for the given tags and old_tags
    // fields.
    this.observe_tag_changes_on_submit = this.observe_tag_changes_on_submit.bind(this);
    // Update the cached types of all known tags in tag_data and recent_tags.
    this.update_tag_types_for_list = this.update_tag_types_for_list.bind(this);
    this.update_tag_types = this.update_tag_types.bind(this);
    this.create_tag_search_regex = this.create_tag_search_regex.bind(this);
    this.retrieve_tag_search = this.retrieve_tag_search.bind(this);
    // Mark a tag as recently used.  Recently used tags are matched before other tags.
    this.add_recent_tag = this.add_recent_tag.bind(this);
    // Remove the tag from the recent tag list.
    this.remove_recent_tag = this.remove_recent_tag.bind(this);
    // Add as recent tags all tags which are in tags and not in old_tags.  If this is from an
    // edit form, old_tags must be the hidden old_tags value in the edit form; if this is
    // from a search form, old_tags must be null.
    this.add_recent_tags_from_update = this.add_recent_tags_from_update.bind(this);
    // Contents matches (t*g*m -> tagme) are lower priority than other results.  Within
    // each search type (recent and main), sort them to the bottom.
    this.reorder_search_results = this.reorder_search_results.bind(this);
    // Return an array of completions for a tag.  Tag types of returned tags will be
    // registered in Post.tag_types, if necessary.

    // options = {
    //   max_results: 10
    // }

    // [["tag1", "tag2", "tag3"], 1]

    // The value 1 is the number of results from the beginning which come from recent_tags,
    // rather than tag_data.
    this.complete_tag = this.complete_tag.bind(this);
    // Don't load the tag data out of localStorage until it's needed.
    this.loading = false;
    this.loaded = false;
    // If the data format is out of date, clear it.
    current_version = '5';
    if (localStorage.tag_data_format !== current_version) {
      delete localStorage.tag_data;
      delete localStorage.tag_data_version;
      delete localStorage.recent_tags;
      localStorage.tag_data_format = current_version;
    }
    // Pull in recent tags.  This is entirely local data and not too big, so always load it.
    this.recent_tags = localStorage.recent_tags || '';
    this.load_data_complete_callbacks = [];
    this.rapid_backspaces_received = 0;
    this.updates_deferred = false;
  }

  init (current_version) {
    if (this.loaded) {
      return;
    }
    this.most_recent_tag_data_version = current_version;
  }

  load_data (onComplete) {
    let complete;
    // If we're already fully loaded, just run the callback and return.
    if (this.loaded) {
      if (typeof onComplete === 'function') {
        onComplete();
      }
      return this.tag_data != null;
    }
    // Add the callback to the list.
    if (onComplete != null) {
      this.load_data_complete_callbacks.push(onComplete);
    }
    // If we're already loading, let the existing request finish; it'll run the callback.
    if (this.loading) {
      return this.tag_data != null;
    }
    this.loading = true;
    complete = () => {
      let callback, callbacks, i, len, results1;
      this.loading = false;
      this.loaded = true;
      // Now that we have the tag types loaded, update any tag types that we have loaded.
      this.update_tag_types();
      callbacks = this.load_data_complete_callbacks;
      this.load_data_complete_callbacks = [];
      results1 = [];
      for (i = 0, len = callbacks.length; i < len; i++) {
        callback = callbacks[i];
        results1.push(callback());
      }
      return results1;
    };
    // If we have data available, load it.
    if (localStorage.tag_data != null) {
      this.tag_data = localStorage.tag_data;
      if (!(typeof this.most_recent_tag_data_version === 'function' ? this.most_recent_tag_data_version(localStorage.tag_data_version === this.most_recent_tag_data_version) : void 0)) {
        // console.log("Already on most recent tag data version");
        complete();
        return this.tag_data != null;
      }
    }
    // Request the tag data from the server.  Tell the server the data version we already
    // have.
    jQuery.ajax({
      url: '/tag/summary.json',
      data: {
        version: localStorage.tag_data_version
      },
      dataType: 'json'
    }).done((json) => {
      if (json.unchanged) {
        // If unchanged is true, tag_data_version is already current; this means we weren't told
        // the current data revision to start with but we're already up to date.
        // console.log("Tag data unchanged")
        this.tag_data = localStorage.tag_data;
      } else {
        // We received new tag data; save it.
        // console.log("Storing new tag data")
        this.tag_data = json.data;
        localStorage.tag_data = this.tag_data;
        localStorage.tag_data_version = json.version;
      }
      return complete();
    });
    return this.tag_data != null;
  }

  observe_tag_changes_on_submit (form, tags_field, old_tags_field) {
    return form.on('submit', (e) => {
      return this.add_recent_tags_from_update(tags_field.value, old_tags_field != null ? old_tags_field.value : void 0);
    });
  }

  update_tag_types_for_list (tags, allow_add) {
    let idx, split_tags, tag_map;
    tag_map = {};
    // Make a mapping of tags to indexes.
    split_tags = split_data(tags, ' ');
    idx = 0;
    split_tags.each(function (tag) {
      let tag_name;
      if (tag === '') {
        return;
      }
      tag_name = get_tag_from_string(tag);
      tag_map[tag_name] = idx;
      ++idx;
    });
    /*
     * For each known tag type, mark the type in the tag cache.  We receive this info when
     * we download the tag types, so this is just updating any changes.
     *
     * This is set up to iterate only over known types, and not over the entire list of
     * tags, so when we have a lot of tags we minimize the amount of work we have to do
     * on every tag.
     */
    Post.tag_types.each(function (tag_and_type) {
      let existing_tag, m, new_tag_string, tag, tag_idx, tag_string, tag_type, tag_type_idx;
      tag = tag_and_type[0];
      tag_type = tag_and_type[1];
      tag_type_idx = Post.tag_type_names.indexOf(tag_type);
      if (tag_type_idx === -1) {
        throw 'Unknown tag type ' + tag_type;
      }
      if (!(tag in tag_map)) {
        // This tag is known in Post.tag_types, but isn't a known tag.  If allow_add is true,
        // add it to the end.  This is for updating new tags that have shown up on the server,
        // not for adding new recent tags.
        if (allow_add) {
          tag_string = tag_type_idx + '`' + tag + '`';
          split_tags.push(tag_string);
        }
      } else {
        // This is a known tag; this is the usual case.  Parse out the complete tag from the
        // original string, and update the tag type index.
        tag_idx = tag_map[tag];
        existing_tag = split_tags[tag_idx];
        m = existing_tag.match(/\d+(`.*)/);
        new_tag_string = tag_type_idx + m[1];
        split_tags[tag_idx] = new_tag_string;
      }
    });
    return join_data(split_tags, ' ');
  }

  update_tag_types () {
    if (!this.loaded) {
      return;
    }
    // Update both tag_data and recent_tags; only add new entries to tag_data.
    this.tag_data = this.update_tag_types_for_list(this.tag_data, true);
    localStorage.tag_data = this.tag_data;
    this.recent_tags = this.update_tag_types_for_list(this.recent_tags, false);
    localStorage.recent_tags = this.recent_tags;
  }

  create_tag_search_regex (tag, options) {
    let first, last, letters, regex_parts, regex_string, s;
    // Split the tag by character.
    letters = tag.split('');
    // We can do a few search methods:

    // 1: Ordinary prefix search.
    // 2: Name search. "aaa_bbb" -> "aaa*_bbb*|bbb*_aaa*".
    // 3: Contents search; "tgm" -> "t*g*m*" -> "tagme".  The first character is still always
    // matched exactly.

    // Avoid running multiple expressions.  Instead, combine these into a single one, then run
    // each part on the results to determine which type of result it is.  Always show prefix and
    // name results before contents results.
    regex_parts = [];
    // Allow basic word prefix matches.  "tag" matches at the beginning of any word
    // in a tag, eg. both "tagme" and "dont_tagme".

    // Add the regex for ordinary prefix matches.
    s = '(([^`]*_)?';
    letters.each(function (letter) {
      let escaped_letter;
      escaped_letter = RegExp.escape(letter);
      s += escaped_letter;
    });
    s += ')';
    regex_parts.push(s);
    // Allow "fir_las" to match both "first_last" and "last_first".
    if (tag.indexOf('_') !== -1) {
      first = tag.split('_', 1)[0];
      last = tag.slice(first.length + 1);
      first = RegExp.escape(first);
      last = RegExp.escape(last);
      s = '(';
      s += '(' + first + '[^`]*_' + last + ')';
      s += '|';
      s += '(' + last + '[^`]*_' + first + ')';
      s += ')';
      regex_parts.push(s);
    }
    if (!options.top_results_only && letters.length < 12) {
      s = '(';
      letters.each(function (letter) {
        let escaped_letter;
        escaped_letter = RegExp.escape(letter);
        s += escaped_letter;
        s += '[^`]*';
      });
      s += ')';
      regex_parts.push(s);
    }
    // The space is included in the result, so the result tags can be matched with the
    // same regexes, for in reorder_search_results.

    // (\d)+  match the alias ID                      1`
    // [^ ]*: start at the beginning of any alias     1`foo`bar`
    // ... match ...
    // [^`]*` all matches are prefix matches          1`foo`bar`tagme`
    // [^ ]*  match any remaining aliases             1`foo`bar`tagme`tag_me`
    regex_string = regex_parts.join('|');
    regex_string = '(\\d+)[^ ]*`(' + regex_string + ')[^`]*`[^ ]* ';
    return new RegExp(regex_string, options.global ? 'g' : '');
  }

  retrieve_tag_search (re, source, options) {
    let m, max_results, results, tag;
    results = [];
    max_results = 10;
    if (options.max_results != null) {
      max_results = options.max_results;
    }
    while (results.length < max_results) {
      m = re.exec(source);
      if (!m) {
        break;
      }
      tag = m[0];
      // Ignore this tag.  We need a better way to blackhole tags.
      if (tag.indexOf(':deletethistag:') !== -1) {
        continue;
      }
      if (results.indexOf(tag) === -1) {
        results.push(tag);
      }
    }
    return results;
  }

  add_recent_tag (tag) {
    let max_recent_tags_size, purge_at, tag_entry, tag_type, tag_type_idx;
    // Don't add tags that will make the data unparsable.
    if (tag.indexOf(' ') !== -1 || tag.indexOf('`') !== -1) {
      throw 'Invalid recent tag: ' + tag;
    }
    this.remove_recent_tag(tag);
    // Look up the tag type if we know it.
    tag_type = Post.tag_types.get(tag) || 'general';
    tag_type_idx = Post.tag_type_names.indexOf(tag_type);
    // We should know all tag types.
    if (tag_type_idx === -1) {
      throw 'Unknown tag type: ' + tag_type;
    }
    // Add the tag to the front.  Always append a space, not just between entries.
    tag_entry = tag_type_idx + '`' + tag + '` ';
    this.recent_tags = tag_entry + this.recent_tags;
    // If the recent tags list is too big, remove data from the end.
    max_recent_tags_size = 1024 * 16;
    if (this.recent_tags.length > max_recent_tags_size * 10 / 9) {
      // Be sure to leave the trailing space in place.
      purge_at = this.recent_tags.indexOf(' ', max_recent_tags_size);
      if (purge_at !== -1) {
        this.recent_tags = this.recent_tags.slice(0, purge_at + 1);
      }
    }
    localStorage.recent_tags = this.recent_tags;
  }

  remove_recent_tag (tag) {
    let escaped_tag, re;
    escaped_tag = RegExp.escape(tag);
    re = new RegExp('\\d`' + escaped_tag + '` ', 'g');
    this.recent_tags = this.recent_tags.replace(re, '');
    localStorage.recent_tags = this.recent_tags;
  }

  add_recent_tags_from_update (tags, old_tags) {
    tags = tags.split(' ');
    if (old_tags != null) {
      old_tags = old_tags.split(' ');
    }
    tags.each((tag) => {
      // Ignore invalid tags.
      if (tag.indexOf('`') !== -1) {
        return;
      }
      // Ignore rating shortcuts.
      if ('sqe'.indexOf(tag) !== -1) {
        return;
      }
      // Ignore tags that the user didn't just add.
      if (old_tags && old_tags.indexOf(tag) !== -1) {
        return;
      }
      if ((old_tags == null) && tag.indexOf(':') === -1) {
        if (this.tag_data.indexOf('`' + tag + '`') === -1) {
          return;
        }
      }
      return this.add_recent_tag(tag);
    });
  }

  reorder_search_results (tag, results) {
    let bottom_results, re, top_results;
    re = this.create_tag_search_regex(tag, {
      top_results_only: true,
      global: false
    });
    top_results = [];
    bottom_results = [];
    results.each(function (tag) {
      if (re.test(tag)) {
        top_results.push(tag);
      } else {
        bottom_results.push(tag);
      }
    });
    return top_results.concat(bottom_results);
  }

  complete_tag (tag, options) {
    let final_aliases, final_results, main_results, re, recent_result_count, recent_results, results, tag_types;
    if (this.tag_data == null) {
      throw 'Tag data isn\'t loaded';
    }
    if (options == null) {
      options = {};
    }
    if (tag === '') {
      return [[], 0];
    }
    // Make a list of all results; this will be ordered recent tags first, other tags
    // sorted by tag count.  Request more results than we need, since we'll reorder
    // them below before cutting it off.
    re = this.create_tag_search_regex(tag, {
      global: true
    });
    recent_results = this.retrieve_tag_search(re, this.recent_tags, {
      max_results: 100
    });
    main_results = this.retrieve_tag_search(re, this.tag_data, {
      max_results: 100
    });
    recent_results = this.reorder_search_results(tag, recent_results);
    main_results = this.reorder_search_results(tag, main_results);
    recent_result_count = recent_results.length;
    results = recent_results.concat(main_results);
    // Hack: if the search is one of the ratings shortcuts, put that at the top, even though
    // it's not a real tag.
    if ('sqe'.indexOf(tag) !== -1) {
      results.unshift('0`' + tag + '` ');
    }
    results = results.slice(0, options.max_results != null ? options.max_results : 10);
    recent_result_count = Math.min(results.length, recent_result_count);
    // Strip the "1`" tag type prefix off of each result.
    final_results = [];
    tag_types = {};
    final_aliases = [];
    results.each(function (tag) {
      let aliases, m, tag_type;
      m = tag.match(/(\d+)`([^`]*)`(([^ ]*)`)? /);
      if (!m) {
        throw `Unparsable cached tag: '${tag}'`;
      }
      tag = m[2];
      tag_type = Post.tag_type_names[m[1]];
      aliases = m[4];
      if (m[4]) {
        aliases = aliases.split('`');
      } else {
        aliases = [];
      }
      tag_types[tag] = tag_type;
      if (final_results.indexOf(tag) === -1) {
        final_results.push(tag);
        final_aliases.push(aliases);
      }
    });
    // Register tag types of results with Post.
    Post.register_tags(tag_types, true);
    return [final_results, recent_result_count, final_aliases];
  }
};
