// Generated by CoffeeScript 2.7.0
var TagScript;

export default TagScript = class TagScript {
  constructor() {
    var TagEditArea;
    TagEditArea = null;
  }

  load() {
    this.TagEditArea.value = Cookie.get('tag-script');
  }

  save() {
    Cookie.put('tag-script', this.TagEditArea.value);
  }

  init(element, x) {
    this.TagEditArea = element;
    this.load();
    this.TagEditArea.observe('change', (e) => {
      this.save();
    });
    this.TagEditArea.observe('focus', function(e) {
      Post.reset_tag_script_applied();
    });
    // This mostly keeps the tag script field in sync between windows, but it
    // doesn't work in Opera, which sends focus events before blur events.
    Event.on(window, 'unload', () => {
      this.save();
    });
    document.observe('focus', (e) => {
      this.load();
    });
  }

  parse(script) {
    return script.match(/\[.+?\]|\S+/g);
  }

  test(tags, predicate) {
    var is_true, split_pred;
    split_pred = predicate.match(/\S+/g);
    is_true = true;
    split_pred.each(function(x) {
      if (x[0] === '-') {
        if (tags.include(x.substr(1, 100))) {
          is_true = false;
          throw $break;
        }
      } else {
        if (!tags.include(x)) {
          is_true = false;
          throw $break;
        }
      }
    });
    return is_true;
  }

  process(tags, command) {
    var match;
    if (command.match(/^\[if/)) {
      match = command.match(/\[if\s+(.+?)\s*,\s*(.+?)\]/);
      if (this.test(tags, match[1])) {
        return this.process(tags, match[2]);
      } else {
        return tags;
      }
    } else if (command === '[reset]') {
      return [];
    } else if (command[0] === '-' && command.indexOf('-pool:') !== 0) {
      return tags.reject(function(x) {
        return x === command.substr(1, 100);
      });
    } else {
      tags.push(command);
      return tags;
    }
  }

  run(post_ids, tag_script, finished) {
    var commands, posts;
    if (!Object.isArray(post_ids)) {
      post_ids = $A([post_ids]);
    }
    commands = this.parse(tag_script) || [];
    posts = new Array();
    post_ids.each((post_id) => {
      var old_tags, post;
      post = Post.posts.get(post_id);
      old_tags = post.tags.join(' ');
      commands.each((x) => {
        post.tags = this.process(post.tags, x);
      });
      posts.push({
        id: post_id,
        old_tags: old_tags,
        tags: post.tags.join(' ')
      });
    });
    notice('Updating ' + posts.length + (post_ids.length === 1 ? ' post' : ' posts'));
    Post.update_batch(posts, finished);
  }

};
