// Generated by CoffeeScript 2.7.0
import {
  isVisible,
  stringToDom
} from 'src/utils/dom';

let TagCompletionBox, createCompletionBox;

createCompletionBox = function () {
  let ret, types;
  ret = document.createElement('div');
  ret.className = 'tag-completion-box';
  ret.tabIndex = -1;
  types = document.createElement('ul');
  types.className = 'color-tag-types';
  ret.appendChild(types);
  return ret;
};

export default TagCompletionBox = class TagCompletionBox {
  constructor (input_field) {
    this.input_mouse = this.input_mouse.bind(this);
    this.input_keydown = this.input_keydown.bind(this);
    this.focus_element = this.focus_element.bind(this);
    this.select_next = this.select_next.bind(this);
    this.show = this.show.bind(this);
    this.hide = this.hide.bind(this);
    this.click_result = this.click_result.bind(this);
    this.get_input_word_offset = this.get_input_word_offset.bind(this);
    // Replace the tag under the cursor.
    this.set_current_word = this.set_current_word.bind(this);
    this.update = this.update.bind(this);
    this.input_field = input_field;
    this.last_value = this.input_field.value;
    // Disable browser autocomplete.
    this.input_field.setAttribute('autocomplete', 'off');
    this.completion_box = createCompletionBox();
    document.body.appendChild(this.completion_box);
    document.on('mousedown', (event) => {
      if (this.input_field.contains(event.target) || this.completion_box.contains(event.target)) {
        return;
      }
      this.hide();
    });
    this.input_field.on('mousedown', this.input_mouse);
    this.input_field.on('mouseup', this.input_mouse);
    this.input_field.parentNode.addEventListener('keydown', this.input_keydown, true);
    // need to use addEventListener for this since Prototype is broken
    this.completion_box.on('mouseover', '.completed-tag', (event, element) => {
      this.focus_element(element);
    });
    this.completion_box.on('click', 'li', this.click_result);
    this.hide();
  }

  input_mouse (event) {
    this.update.defer();
  }

  input_keydown (event) {
    let backspaceTimeoutFn, deferTimeoutFn, focused;
    if (event.target !== this.input_field) {
      return;
    }
    // Handle backspaces even when hidden.
    if (event.keyCode === Event.KEY_BACKSPACE) {
      /*
       * If the user holds down backspace to delete tags, don't spend time updating the
       * autocomplete; if it's too slow it may slow down the input.  However, we don't
       * want to always delay autocomplete on backspace; it looks unresponsive.
       *
       * Count the number of backspaces we receive less than 100ms apart.  Defer updates
       * after we receive two or more in rapid succession, so we'll defer when backspace
       * is held down but not when being depressed.
       *
       * Note that this is done this way rather than by tracking the pressed state with
       * keydown/keyup, because this way we don't need to deal with lost keyup events if
       * focus is lost while the key is pressed.  There's no way to become desynced this way.
       */
      ++this.rapid_backspaces_received;
      clearTimeout(this.backspace_timeout);
      backspaceTimeoutFn = () => {
        return this.rapid_backspaces_received = 0;
      };
      this.backspace_timeout = setTimeout(backspaceTimeoutFn, 100);
      if (this.rapid_backspaces_received > 1) {
        this.updates_deferred = true;
        clearTimeout(this.defer_timeout);
        deferTimeoutFn = () => {
          this.updates_deferred = false;
          return this.update();
        };
        this.defer_timeout = setTimeout(deferTimeoutFn, 100);
      }
    }
    if (!this.shown) {
      this.update.defer();
      return;
    }
    if (event.keyCode === Event.KEY_DOWN) {
      event.stop();
      this.select_next(true);
    } else if (event.keyCode === Event.KEY_UP) {
      event.stop();
      this.select_next(false);
    } else if (event.keyCode === Event.KEY_ESC) {
      event.stop();
      this.hide();
    } else if (event.keyCode === Event.KEY_RETURN) {
      focused = this.completion_box.down('.focused');
      if (focused) {
        event.stop();
        this.set_current_word(focused.result_tag);
      } else {
        this.hide();
      }
    } else {
      this.update.defer();
    }
  }

  focus_element (element) {
    let previous;
    if (element == null) {
      throw 'Can\'t select no element';
    }
    previous = this.completion_box.down('.focused');
    if (previous) {
      previous.removeClassName('focused');
    }
    if (element) {
      element.addClassName('focused');
    }
  }

  select_next (next) {
    let focused, new_focus, siblings;
    focused = this.completion_box.down('.focused');
    siblings = next ? focused.nextSiblings() : focused.previousSiblings();
    new_focus = Prototype.Selector.find(siblings, '.completed-tag', 0);
    if (new_focus == null) {
      new_focus = this.completion_box.down(next ? '.completed-tag' : '.completed-tag:last-child');
    }
    this.focus_element(new_focus);
  }

  show () {
    let offset;
    this.shown = true;
    offset = this.input_field.cumulativeOffset();
    this.completion_box.style.top = offset.top + this.input_field.offsetHeight + 'px';
    this.completion_box.style.left = offset.left + 'px';
    this.completion_box.style.minWidth = this.input_field.offsetWidth + 'px';
  }

  hide () {
    this.shown = false;
    this.current_tag = null;
    this.completion_box.hide();
  }

  click_result (event, element) {
    event.stop();
    if (event.target.hasClassName('remove-recent-tag')) {
      TagCompletion.remove_recent_tag(element.result_tag);
      this.update(true);
      return;
    }
    this.set_current_word(element.result_tag);
  }

  get_input_word_offset (field) {
    let end_idx, start_idx, text;
    text = field.value;
    start_idx = text.lastIndexOf(' ', field.selectionStart - 1);
    if (start_idx === -1) {
      start_idx = 0;
    } else {
      ++start_idx;
    }
    // skip the space itself
    end_idx = text.indexOf(' ', field.selectionStart);
    if (end_idx === -1) {
      end_idx = text.length;
    }
    return {
      start: start_idx,
      end: end_idx
    };
  }

  set_current_word (tag) {
    let after, before, cursor_position, offset, tag_text, text;
    offset = this.get_input_word_offset(this.input_field);
    text = this.input_field.value;
    before = text.substr(0, offset.start);
    after = text.substr(offset.end);
    tag_text = tag;
    // If there's only whitespace after the tag, remove it.  We'll add a single space
    // below.
    if (after.match(/^ +$/)) {
      after = '';
    }
    // If we're at the end of the string, or if there's only whitespace after the tag,
    // insert a space after the tag.
    if (after === '') {
      tag_text += ' ';
    }
    this.input_field.value = before + tag_text + after;
    // Position the cursor at the end of the tag we just inserted.
    cursor_position = before.length + tag_text.length;
    this.input_field.selectionStart = this.input_field.selectionEnd = cursor_position;
    TagCompletion.add_recent_tag(tag);
    this.hide();
  }

  update (force) {
    let aliases, data_available, h, i, li, offset, recent_result_count, span, tag, tag_aliases, tag_type, tags, tags_and_recent_count, ul;
    if (this.updates_deferred && !force) {
      return;
    }
    if (TagCompletion.tag_data == null) {
      // If this returns true, we'll display with the data we have now.  If this happens,
      // don't update during the callback; it's bad UI to be changing the list out from
      // under the user at a seemingly random time.
      data_available = TagCompletion.load_data(() => {
        if (data_available) {
          return;
        }
        // After the load completes, force an update, even though the tag we're completing
        // hasn't changed; the tag data may have.
        this.current_tag = null;
        this.update();
      });
      if (!data_available) {
        return;
      }
    }
    // Figure out the tag the cursor is on.
    offset = this.get_input_word_offset(this.input_field);
    tag = this.input_field.value.substr(offset.start, offset.end - offset.start);
    if (tag === this.current_tag && !force) {
      return;
    }
    this.hide();
    // Don't show the autocomplete unless the contents actually change, so we can still
    // navigate multiline tag input boxes with the arrow keys.
    if (this.last_value === this.input_field.value && !force) {
      return;
    }
    this.last_value = this.input_field.value;
    this.current_tag = tag;
    if (!isVisible(this.input_field)) {
      return;
    }
    tags_and_recent_count = TagCompletion.complete_tag(tag);
    tags = tags_and_recent_count[0];
    tag_aliases = tags_and_recent_count[2];
    recent_result_count = tags_and_recent_count[1];
    if (tags.length === 0) {
      return;
    }
    if (tags.length === 1 && tags[0] === tag) {
      return;
    }
    // There's only one result, and it's the tag already in the field; don't
    // show the list.
    this.show();
    // Clear any old results.
    ul = this.completion_box.down('UL');
    this.completion_box.hide();
    while (ul.firstChild) {
      ul.removeChild(ul.firstChild);
    }
    i = 0;
    while (i < tags.length) {
      tag = tags[i];
      li = document.createElement('LI');
      li.className = 'completed-tag';
      li.textContent = tag;
      ul.appendChild(li);
      // If we have any aliases, show the first one.
      aliases = tag_aliases[i];
      if (aliases.length > 0) {
        span = document.createElement('span');
        span.className = 'completed-tag-alias';
        span.textContent = aliases[0];
        li.appendChild(span);
      }
      tag_type = Post.tag_types.get(tag);
      li.className += ' tag-type-' + tag_type;
      if (i < recent_result_count) {
        li.className += ' recent-tag';
        h = '<a class=\'remove-recent-tag\' href=\'#\'>X</a>\'';
        li.appendChild(stringToDom(h));
      }
      li.result_tag = tag;
      ++i;
    }
    this.completion_box.show();
    // Focus the first item.
    this.focus_element(this.completion_box.down('.completed-tag'));
  }
};
