// Generated by CoffeeScript 2.7.0
var ThumbnailView;

import DragElement from 'src/classes/drag_element';

import {
  sortArrayByDistance
} from 'src/utils/array';

import {
  isTouchscreen
} from 'src/utils/browser';

import PreloadContainer from './preload_container';

// Handle the thumbnail view, and navigation for the main view.

// Handle a large number (thousands) of entries cleanly.  Thumbnail nodes are created
// as needed, and destroyed when they scroll off screen.  This gives us constant
// startup time, loads thumbnails on demand, allows preloading thumbnails in advance
// by creating more nodes in advance, and keeps memory usage constant.
export default ThumbnailView = class ThumbnailView {
  constructor(container, view) {
    var width;
    this.window_resize_event = this.window_resize_event.bind(this);
    // Show the given posts.  If extending is true, post_ids are meant to extend a previous
    // search; attempt to continue where we left off.
    this.loaded_posts_event = this.loaded_posts_event.bind(this);
    this.container_ondrag = this.container_ondrag.bind(this);
    this.container_mouseover_event = this.container_mouseover_event.bind(this);
    this.container_mouseout_event = this.container_mouseout_event.bind(this);
    this.hashchange_post_id = this.hashchange_post_id.bind(this);
    // Track the mouse cursor when it's within the container.
    this.container_mousemove_event = this.container_mousemove_event.bind(this);
    this.document_mouse_wheel_event = this.document_mouse_wheel_event.bind(this);
    this.set_thumb_dimensions = this.set_thumb_dimensions.bind(this);
    // Handle clicks and doubleclicks on thumbnails.  These events are handled by
    // the container, so we don't need to put event handlers on every thumb.
    this.container_click_event = this.container_click_event.bind(this);
    this.container_dblclick_event = this.container_dblclick_event.bind(this);
    this.displayed_image_loaded_event = this.displayed_image_loaded_event.bind(this);
    this.container = container;
    this.view = view;
    this.post_ids = [];
    this.post_frames = [];
    this.expanded_post_idx = null;
    this.centered_post_idx = null;
    this.centered_post_offset = 0;
    this.last_mouse_x = 0;
    this.last_mouse_y = 0;
    this.thumb_container_shown = true;
    this.allow_wrapping = true;
    this.thumb_preload_container = new PreloadContainer();
    this.unused_thumb_pool = [];
    // The [first, end) range of posts that are currently inside .post-browser-posts.
    this.posts_populated = [0, 0];
    document.on('DOMMouseScroll', this.document_mouse_wheel_event);
    document.on('mousewheel', this.document_mouse_wheel_event);
    document.on('viewer:displayed-image-loaded', this.displayed_image_loaded_event);
    document.on('viewer:set-active-post', (e) => {
      var post_id_and_frame;
      post_id_and_frame = [e.memo.post_id, e.memo.post_frame];
      this.set_active_post(post_id_and_frame, e.memo.lazy, e.memo.center_thumbs);
    });
    document.on('viewer:show-next-post', (e) => {
      this.show_next_post(e.memo.prev);
    });
    document.on('viewer:scroll', (e) => {
      this.scroll(e.memo.left);
    });
    document.on('viewer:set-thumb-bar', (e) => {
      if (e.memo.toggle) {
        this.show_thumb_bar(!this.thumb_container_shown);
      } else {
        this.show_thumb_bar(e.memo.set);
      }
    });
    document.on('viewer:loaded-posts', this.loaded_posts_event);
    UrlHash.observe('post-id', this.hashchange_post_id);
    UrlHash.observe('post-frame', this.hashchange_post_id);
    new DragElement(this.container, {
      ondrag: this.container_ondrag
    });
    Element.on(window, 'resize', this.window_resize_event);
    this.container.on('mousemove', this.container_mousemove_event);
    this.container.on('mouseover', this.container_mouseover_event);
    this.container.on('mouseout', this.container_mouseout_event);
    this.container.on('click', this.container_click_event);
    this.container.on('dblclick', '.post-thumb,.browser-thumb-hover-overlay', this.container_dblclick_event);
    // Prevent the default behavior of left-clicking on the expanded thumbnail overlay.  It's
    // handled by container_click_event.
    this.container.down('.browser-thumb-hover-overlay').on('click', (event) => {
      if (event.isLeftClick()) {
        event.preventDefault();
      }
    });
    // For Android browsers, we're set to 150 DPI, which (in theory) scales us to a consistent UI size
    // based on the screen DPI.  This means that we can determine the physical screen size from the
    // window resolution: 150x150 is 1"x1".  Set a thumbnail scale based on this.  On a 320x480 HVGA
    // phone screen the thumbnails are about 2x too big, so set thumb_scale to 0.5.

    // For iOS browsers, there's no way to set the viewport based on the DPI, so it's fixed at 1x.
    // (Note that on Retina screens the browser lies: even though we request 1x, it's actually at
    // 0.5x and our screen dimensions work as if we're on the lower-res iPhone screen.  We can mostly
    // ignore this.)  CSS inches aren't implemented (the DPI is fixed at 96), so that doesn't help us.
    // Fall back on special-casing individual iOS devices.
    this.config = {};
    if (navigator.userAgent.indexOf('iPad') !== -1) {
      this.config.thumb_scale = 1.0;
    } else if (navigator.userAgent.indexOf('iPhone') !== -1 || navigator.userAgent.indexOf('iPod') !== -1) {
      this.config.thumb_scale = 0.5;
    } else if (navigator.userAgent.indexOf('Android') !== -1) {
      // We may be in landscape or portrait; use out the narrower dimension.
      width = Math.min(window.innerWidth, window.innerHeight);
      // Scale a 320-width screen to 0.5, up to 1.0 for a 640-width screen.  Remember
      // that this width is already scaled by the DPI of the screen due to target-densityDpi,
      // so these numbers aren't actually real pixels, and this scales based on the DPI
      // and size of the screen rather than the pixel count.
      this.config.thumb_scale = width / 640;
      console.debug('Unclamped thumb scale: ' + this.config.thumb_scale);
      // Clamp to [0.5,1.0].
      this.config.thumb_scale = Math.min(this.config.thumb_scale, 1.0);
      this.config.thumb_scale = Math.max(this.config.thumb_scale, 0.5);
      console.debug('startup, window size: ' + window.innerWidth + 'x' + window.innerHeight);
    } else {
      // Unknown device, or not a mobile device.
      this.config.thumb_scale = 1.0;
    }
    console.debug('Thumb scale: ' + this.config.thumb_scale);
    this.config_changed();
    // Send the initial viewer:thumb-bar-changed event.
    this.thumb_container_shown = false;
    this.show_thumb_bar(true);
    return;
  }

  window_resize_event(e) {
    if (e.stopped) {
      return;
    }
    if (this.thumb_container_shown) {
      this.center_on_post_for_scroll(this.centered_post_idx);
    }
  }

  loaded_posts_event(event) {
    var _frame, center_on_post_idx, frameIdx, i, initial_post_id, initial_post_id_and_frame, j, k, len, len1, old_centered_post_idx, old_post_ids, post, postId, post_id_search_order, post_id_to_search, post_ids, ref, results_mode;
    post_ids = event.memo.post_ids;
    old_post_ids = this.post_ids;
    old_centered_post_idx = this.centered_post_idx;
    this.remove_all_posts();
    // Filter blacklisted posts.
    post_ids = post_ids.reject(Post.is_blacklisted);
    this.post_ids = [];
    this.post_frames = [];
    for (j = 0, len = post_ids.length; j < len; j++) {
      postId = post_ids[j];
      post = Post.posts.get(postId);
      if (post.frames.length > 0) {
        ref = post.frames;
        for (frameIdx = k = 0, len1 = ref.length; k < len1; frameIdx = ++k) {
          _frame = ref[frameIdx];
          this.post_ids.push(postId);
          this.post_frames.push(frameIdx);
        }
      } else {
        this.post_ids.push(postId);
        this.post_frames.push(-1);
      }
    }
    this.allow_wrapping = !event.memo.can_be_extended_further;
    // Show the results box or "no results".  Do this before updating the results box to make sure
    // the results box isn't hidden when we update, which will make offsetLeft values inside it zero
    // and break things.  If the reason we have no posts is because we didn't do a search at all,
    // don't show no-results.
    this.container.down('.post-browser-no-results').show((event.memo.tags != null) && this.post_ids.length === 0);
    this.container.down('.post-browser-posts').show(this.post_ids.length !== 0);
    if (event.memo.extending) {
      // We're extending a previous search with more posts.  The new post list we get may
      // not line up with the old one: the post we're focused on may no longer be in the
      // search, or may be at a different index.

      // Find a nearby post in the new results.  Start searching at the post we're already
      // centered on.  If that doesn't match, move outwards from there.  Only look forward
      // a little bit, or we may match a post that was never seen and jump forward too far
      // in the results.
      post_id_search_order = sortArrayByDistance(old_post_ids.slice(0, old_centered_post_idx + 3), old_centered_post_idx);
      initial_post_id = null;
      i = 0;
      while (i < post_id_search_order.length) {
        post_id_to_search = post_id_search_order[i];
        post = Post.posts.get(post_id_to_search);
        if (post != null) {
          initial_post_id = post.id;
          break;
        }
        ++i;
      }
      console.debug('center-on-' + initial_post_id);
      if (initial_post_id == null) {
        this.centered_post_offset = 0;
        initial_post_id = new_post_ids[0];
      }
      center_on_post_idx = this.post_ids.indexOf(initial_post_id);
      this.center_on_post_for_scroll(center_on_post_idx);
    } else {
      // A new search has completed.

      // results_mode can be one of the following:

      // "center-on-first"
      // Don't change the active post.  Center the results on the first result.  This is used
      // when performing a search by clicking on a tag, where we don't want to center on the
      // post we're on (since it'll put us at some random spot in the results when the user
      // probably wants to browse from the beginning), and we don't want to change the displayed
      // post either.

      // "center-on-current"
      // Don't change the active post.  Center the results on the existing current item,
      // if possible.  This is used when we want to show a new search without disrupting the
      // shown post, such as the "child posts" link in post info, and when loading the initial
      // URL hash when we start up.

      // "jump-to-first"
      // Set the active post to the first result, and center on it.  This is used after making
      // a search in the tags box.
      results_mode = event.memo.load_options.results_mode || 'center-on-current';
      initial_post_id_and_frame = void 0;
      if (results_mode === 'center-on-first' || results_mode === 'jump-to-first') {
        initial_post_id_and_frame = [this.post_ids[0], this.post_frames[0]];
      } else {
        initial_post_id_and_frame = this.get_current_post_id_and_frame();
      }
      center_on_post_idx = this.get_post_idx(initial_post_id_and_frame);
      if (center_on_post_idx == null) {
        center_on_post_idx = 0;
      }
      this.centered_post_offset = 0;
      this.center_on_post_for_scroll(center_on_post_idx);
      // If no post is currently displayed and we just completed a search, set the current post.
      // This happens when first initializing; we wait for the first search to complete to retrieve
      // info about the post we're starting on, instead of making a separate query.
      if (results_mode === 'jump-to-first' || (this.view.wanted_post_id == null)) {
        this.set_active_post(initial_post_id_and_frame, false, false, true);
      }
    }
    if (event.memo.tags == null) {
      // If tags is null then no search has been done, which means we're on a URL
      // with a post ID and no search, eg. "/post/browse#12345".  Hide the thumb
      // bar, so we'll just show the post.
      this.show_thumb_bar(false);
    }
  }

  container_ondrag(e) {
    this.centered_post_offset -= e.dX;
    this.center_on_post_for_scroll(this.centered_post_idx);
  }

  container_mouseover_event(event) {
    var li;
    li = $(event.target);
    if (!li.hasClassName('.post-thumb')) {
      li = li.up('.post-thumb');
    }
    if (li) {
      this.expand_post(li.post_idx);
    }
  }

  container_mouseout_event(event) {
    var target;
    // If the mouse is leaving the hover overlay, hide it.
    target = $(event.target);
    if (!target.hasClassName('.browser-thumb-hover-overlay')) {
      target = target.up('.browser-thumb-hover-overlay');
    }
    if (target) {
      this.expand_post(null);
    }
  }

  hashchange_post_id() {
    var new_post_idx, post_frame, post_id, post_id_and_frame;
    post_id_and_frame = this.get_current_post_id_and_frame();
    if (post_id_and_frame[0] == null) {
      return;
    }
    // If we're already displaying this post, ignore the hashchange.  Don't center on the
    // post if this is just a side-effect of clicking a post, rather than the user actually
    // changing the hash.
    post_id = post_id_and_frame[0];
    post_frame = post_id_and_frame[1];
    if (post_id === this.view.displayed_post_id && post_frame === this.view.displayed_post_frame) {
      return;
    }
    //    debug("ignored-hashchange");
    new_post_idx = this.get_post_idx(post_id_and_frame);
    this.centered_post_offset = 0;
    this.center_on_post_for_scroll(new_post_idx);
    this.set_active_post(post_id_and_frame, false, false, true);
  }

  // Search for the given post ID and frame in the current search results, and return its
  // index.  If the given post isn't in post_ids, return null.
  get_post_idx(post_id_and_frame) {
    var post_frame, post_frame_idx, post_id, post_idx;
    post_id = post_id_and_frame[0];
    post_frame = post_id_and_frame[1];
    post_idx = this.post_ids.indexOf(post_id);
    if (post_idx === -1) {
      return null;
    }
    if (post_frame === -1) {
      return post_idx;
    }
    // A post-frame is specified.  Search for a matching post-id and post-frame.  We assume
    // here that all frames for a post are grouped together in post_ids.
    post_frame_idx = post_idx;
    while (post_frame_idx < this.post_ids.length && this.post_ids[post_frame_idx] === post_id) {
      if (this.post_frames[post_frame_idx] === post_frame) {
        return post_frame_idx;
      }
      ++post_frame_idx;
    }
    // We found a matching post, but not a matching frame.  Return the post.
    return post_idx;
  }

  // Return the post and frame that's currently being displayed in the main view, based
  // on the URL hash.  If no post is displayed and no search results are available,
  // return [null, null].
  get_current_post_id_and_frame() {
    var post_frame, post_id;
    post_id = UrlHash.get('post-id');
    if (post_id == null) {
      if (this.post_ids.length === 0) {
        return [null, null];
      } else {
        return [this.post_ids[0], this.post_frames[0]];
      }
    }
    post_id = parseInt(post_id);
    post_frame = UrlHash.get('post-frame');
    if (post_frame == null) {
      post_frame = this.view.get_default_post_frame(post_id);
    }
    return [post_id, post_frame];
  }

  container_mousemove_event(e) {
    var x, y;
    x = e.pointerX() - document.documentElement.scrollLeft;
    y = e.pointerY() - document.documentElement.scrollTop;
    this.last_mouse_x = x;
    this.last_mouse_y = y;
  }

  document_mouse_wheel_event(event) {
    var val;
    event.stop();
    val = void 0;
    if (event.wheelDelta) {
      val = event.wheelDelta;
    } else if (event.detail) {
      val = -event.detail;
    }
    if (this.thumb_container_shown) {
      document.fire('viewer:scroll', {
        left: val >= 0
      });
    } else {
      document.fire('viewer:show-next-post', {
        prev: val >= 0
      });
    }
  }

  // Set the post that's shown in the view.  The thumbs will be centered on the post
  // if center_thumbs is true.  See BrowserView.prototype.set_post for an explanation
  // of no_hash_change.
  set_active_post(post_id_and_frame, lazy, center_thumbs, no_hash_change, replace_history) {
    var post_idx;
    if (post_id_and_frame[0] == null) {
      return;
    }
    this.view.set_post(post_id_and_frame[0], post_id_and_frame[1], lazy, no_hash_change, replace_history);
    if (center_thumbs) {
      post_idx = this.get_post_idx(post_id_and_frame);
      this.centered_post_offset = 0;
      this.center_on_post_for_scroll(post_idx);
    }
  }

  set_active_post_idx(post_idx, lazy, center_thumbs, no_hash_change, replace_history) {
    var post_frame, post_id;
    if (post_idx == null) {
      return;
    }
    post_id = this.post_ids[post_idx];
    post_frame = this.post_frames[post_idx];
    this.set_active_post([post_id, post_frame], lazy, center_thumbs, no_hash_change, replace_history);
  }

  show_next_post(prev) {
    var add, current_idx, new_idx, wrapped;
    if (this.post_ids.length === 0) {
      return;
    }
    current_idx = this.get_post_idx([this.view.wanted_post_id, this.view.wanted_post_frame]);
    if (current_idx == null) {
      current_idx = 0;
    }
    add = prev ? -1 : +1;
    if (this.post_frames[current_idx] !== this.view.wanted_post_frame && add === +1) {
      // We didn't find an exact match for the frame we're displaying, which usually means
      // we viewed a post frame, and then the user changed the view to the main post, and
      // the main post isn't in the thumbnails.

      // It's strange to be on the main post, to hit pgdn, and to end up on the second frame
      // because the nearest match was the first frame.  Instead, we should end up on the first
      // frame.  To do that, just don't add anything to the index.
      console.debug('Snapped the display to the nearest frame');
      if (add === +1) {
        add = 0;
      }
    }
    new_idx = current_idx;
    new_idx += add;
    new_idx += this.post_ids.length;
    new_idx %= this.post_ids.length;
    wrapped = prev && new_idx > current_idx || !prev && new_idx < current_idx;
    if (wrapped) {
      if (!this.allow_wrapping) {
        return;
      }
      if (!this.thumb_container_shown && prev) {
        notice('Continued from the end');
      } else if (!this.thumb_container_shown && !prev) {
        notice('Starting over from the beginning');
      }
    }
    this.set_active_post_idx(new_idx, true, true, false, true);
  }

  // Scroll the thumbnail view left or right.  Don't change the displayed post.
  scroll(left) {
    var new_idx;
    if (!this.thumb_container_shown) {
      return;
    }
    new_idx = this.centered_post_idx;
    // If we're not centered on the post, and we're moving towards the center,
    // don't jump past the post.
    if (this.centered_post_offset > 0 && left) {

    // do nothing
    } else if (this.centered_post_offset < 0 && !left) {

    } else {
      // do nothing
      new_idx += left ? -1 : +1;
    }
    // Snap to the nearest post.
    this.centered_post_offset = 0;
    // Wrap the new index.
    if (new_idx < 0) {
      if (!this.allow_wrapping) {
        new_idx = 0;
      } else {
        new_idx = this.post_ids.length - 1;
      }
    } else if (new_idx >= this.post_ids.length) {
      if (!this.allow_wrapping) {
        new_idx = this.post_ids.length - 1;
      } else {
        new_idx = 0;
      }
    }
    this.center_on_post_for_scroll(new_idx);
  }

  // Hide the hovered post, if any, call center_on_post(post_idx), then hover over the correct post again.
  center_on_post_for_scroll(post_idx) {
    var element, li;
    if (this.thumb_container_shown) {
      this.expand_post(null);
    }
    this.center_on_post(post_idx);
    // Now that we've re-centered, we need to expand the correct image.  Usually, we can just
    // wait for the mouseover event to fire, since we hid the expanded thumb overlay and the
    // image underneith it is now under the mouse.  However, browsers are badly broken here.
    // Opera doesn't fire mouseover events when the element under the cursor is hidden.  FF
    // fires the mouseover on hide, but misses the mouseout when the new overlay is shown, so
    // the next time it's hidden mouseover events are lost.

    // Explicitly figure out which item we're hovering over and expand it.
    if (this.thumb_container_shown) {
      element = document.elementFromPoint(this.last_mouse_x, this.last_mouse_y);
      element = $(element);
      if (element) {
        li = element.up('.post-thumb');
        if (li) {
          this.expand_post(li.post_idx);
        }
      }
    }
  }

  remove_post(right) {
    var item, node, node_to_remove;
    if (this.posts_populated[0] === this.posts_populated[1]) {
      return false;
    }
    // none to remove
    node = this.container.down('.post-browser-posts');
    if (right) {
      --this.posts_populated[1];
      node_to_remove = node.lastChild;
    } else {
      ++this.posts_populated[0];
      node_to_remove = node.firstChild;
    }
    // Remove the thumbnail that's no longer visible, and put it in unused_thumb_pool
    // so we can reuse it later.  This won't grow out of control, since we'll always use
    // an item from the pool if available rather than creating a new one.
    item = node.removeChild(node_to_remove);
    this.unused_thumb_pool.push(item);
    return true;
  }

  remove_all_posts() {
    var results;
    results = [];
    while (this.remove_post(true)) {
      continue;
    }
    return results;
  }

  // Add the next thumbnail to the left or right side.
  add_post_to_display(right) {
    var node, post_idx_to_populate, thumb;
    node = this.container.down('.post-browser-posts');
    if (right) {
      post_idx_to_populate = this.posts_populated[1];
      if (post_idx_to_populate === this.post_ids.length) {
        return false;
      }
      ++this.posts_populated[1];
      thumb = this.create_thumb(post_idx_to_populate);
      node.insertBefore(thumb, null);
    } else {
      if (this.posts_populated[0] === 0) {
        return false;
      }
      --this.posts_populated[0];
      post_idx_to_populate = this.posts_populated[0];
      thumb = this.create_thumb(post_idx_to_populate);
      node.insertBefore(thumb, node.firstChild);
    }
    return true;
  }

  // Fill the container so post_idx is visible.
  populate_post(post_idx) {
    var node, thumb;
    if (this.is_post_idx_shown(post_idx)) {
      return;
    }
    // If post_idx is on the immediate border of what's already displayed, add it incrementally, and
    // we'll cull extra posts later.  Otherwise, clear all of the posts and populate from scratch.
    if (post_idx === this.posts_populated[1]) {
      this.add_post_to_display(true);
      return;
    } else if (post_idx === this.posts_populated[0]) {
      this.add_post_to_display(false);
      return;
    }
    // post_idx isn't on the boundary, so we're jumping posts rather than scrolling.
    // Clear the container and start over.
    this.remove_all_posts();
    node = this.container.down('.post-browser-posts');
    thumb = this.create_thumb(post_idx);
    node.appendChild(thumb);
    this.posts_populated[0] = post_idx;
    this.posts_populated[1] = post_idx + 1;
  }

  is_post_idx_shown(post_idx) {
    if (post_idx >= this.posts_populated[1]) {
      return false;
    }
    return post_idx >= this.posts_populated[0];
  }

  // Return the total width of all thumbs to the left or right of post_idx, not
  // including itself.
  get_width_adjacent_to_post(post_idx, right) {
    var center_post_right_edge, post, right_edge, rightmost_node;
    post = $('p' + post_idx);
    if (right) {
      rightmost_node = post.parentNode.lastChild;
      if (rightmost_node === post) {
        return 0;
      }
      right_edge = rightmost_node.offsetLeft + rightmost_node.offsetWidth;
      center_post_right_edge = post.offsetLeft + post.offsetWidth;
      return right_edge - center_post_right_edge;
    } else {
      return post.offsetLeft;
    }
  }

  // Center the thumbnail strip on post_idx.  If post_id isn't in the display, do nothing.
  // Fire viewer:need-more-thumbs if we're scrolling near the edge of the list.
  center_on_post(post_idx) {
    var added, center_on_position, current_post_center, direction, distance, maximum_distance, minimum_distance, next_post, next_post_center, next_post_idx, node, pos, post, post_id, right, shift_pixels_right, thumb, width;
    if (!this.post_ids) {
      console.debug('unexpected: center_on_post has no post_ids');
      return;
    }
    post_id = this.post_ids[post_idx];
    if (Post.posts.get(post_id) == null) {
      return;
    }
    if (post_idx > this.post_ids.length * 3 / 4) {
      (function() {        // We're coming near the end of the loaded posts, so load more.  We may be currently
        // in the middle of setting up the post; defer this, so we finish what we're doing first.
        document.fire('viewer:need-more-thumbs', {
          view: this
        });
      }).defer();
    }
    this.centered_post_idx = post_idx;
    if (!this.thumb_container_shown) {
      return;
    }
    while (true) {
      // If centered_post_offset is high enough to put the actual center post somewhere else,
      // adjust it towards zero and change centered_post_idx.  This keeps centered_post_idx
      // pointing at the item that's actually centered.
      post = $('p' + this.centered_post_idx);
      if (!post) {
        break;
      }
      pos = post.offsetWidth / 2 + this.centered_post_offset;
      if (pos >= 0 && pos < post.offsetWidth) {
        break;
      }
      next_post_idx = this.centered_post_idx + (this.centered_post_offset > 0 ? +1 : -1);
      next_post = $('p' + next_post_idx);
      if (next_post == null) {
        break;
      }
      current_post_center = post.offsetLeft + post.offsetWidth / 2;
      next_post_center = next_post.offsetLeft + next_post.offsetWidth / 2;
      distance = next_post_center - current_post_center;
      this.centered_post_offset -= distance;
      this.centered_post_idx = next_post_idx;
      post_idx = this.centered_post_idx;
      break;
    }
    this.populate_post(post_idx);
    // Make sure that we have enough posts populated around the one we're centering
    // on to fill the display.  If we have too many nodes, remove some.
    direction = 0;
    while (direction < 2) {
      right = !!direction;
      // We need at least this.container.offsetWidth/2 in each direction.  Load a little more, to
      // reduce flicker.
      minimum_distance = this.container.offsetWidth / 2;
      minimum_distance *= 1.25;
      maximum_distance = minimum_distance + 500;
      while (true) {
        added = false;
        width = this.get_width_adjacent_to_post(post_idx, right);
        // If we're offset to the right then we need more data to the left, and vice versa.
        width += this.centered_post_offset * (right ? -1 : +1);
        if (width < 0) {
          width = 1;
        }
        if (width < minimum_distance) {
          if (!this.add_post_to_display(right)) {
            break;
          }
          added = false;
        } else if (width > maximum_distance) {
          // We have a lot of posts off-screen.  Remove one.
          this.remove_post(right);
          // Sanity check: we should never add and remove in the same direction.  If this
          // happens, the distance between minimum_distance and maximum_distance may be less
          // than the width of a single thumbnail.
          if (added) {
            alert('error');
            break;
          }
        } else {
          break;
        }
      }
      ++direction;
    }
    this.preload_thumbs();
    // We always center the thumb.  Don't clamp to the edge when we're near the first or last
    // item, so we always have empty space on the sides for expanded landscape thumbnails to
    // be visible.
    thumb = $('p' + post_idx);
    center_on_position = this.container.offsetWidth / 2;
    shift_pixels_right = center_on_position - (thumb.offsetWidth / 2) - thumb.offsetLeft;
    shift_pixels_right -= this.centered_post_offset;
    shift_pixels_right = Math.round(shift_pixels_right);
    node = this.container.down('.post-browser-scroller');
    node.setStyle({
      left: shift_pixels_right + 'px'
    });
  }

  // Preload thumbs on the boundary of what's actually displayed.
  preload_thumbs() {
    var element, i, j, len, post, post_frame, post_id, post_idx, post_idxs, preload_post_idx, ref, url;
    post_idxs = [];
    i = 0;
    while (i < 5) {
      preload_post_idx = this.posts_populated[0] - i - 1;
      if (preload_post_idx >= 0) {
        post_idxs.push(preload_post_idx);
      }
      preload_post_idx = this.posts_populated[1] + i;
      if (preload_post_idx < this.post_ids.length) {
        post_idxs.push(preload_post_idx);
      }
      ++i;
    }
    ref = [...this.thumb_preload_container.getAll()];
    // Remove any preloaded thumbs that are no longer in the preload list.
    for (j = 0, len = ref.length; j < len; j++) {
      element = ref[j];
      post_idx = element.post_idx;
      if (post_idxs.indexOf(post_idx) !== -1) {
        // The post is staying loaded.  Clear the value in post_idxs, so we don't load it
        // again down below.
        post_idxs[post_idx] = null;
        continue;
      }
      // The post is no longer being preloaded.  Remove the preload.
      this.thumb_preload_container.cancelPreload(element);
    }
    // Add new preloads.
    i = 0;
    while (i < post_idxs.length) {
      post_idx = post_idxs[i];
      if (post_idx == null) {
        ++i;
        continue;
      }
      post_id = this.post_ids[post_idx];
      post = Post.posts.get(post_id);
      post_frame = this.post_frames[post_idx];
      url = void 0;
      if (post_frame !== -1) {
        url = post.frames[post_frame].preview_url;
      } else {
        url = post.preview_url;
      }
      element = this.thumb_preload_container.preload(url);
      element.post_idx = post_idx;
      ++i;
    }
  }

  expand_post(post_idx) {
    var bottom, frame, image_url, image_width, left, max_width, overlay, post, post_frame, post_id, thumb;
    // Thumbs on click for touchpads doesn't make much sense anyway--touching the thumb causes it
    // to be loaded.  It also triggers a bug in iPhone WebKit (covering up the original target of
    // a mouseover during the event seems to cause the subsequent click event to not be delivered).
    // Just disable hover thumbnails for touchscreens.
    if (isTouchscreen) {
      return;
    }
    if (!this.thumb_container_shown) {
      return;
    }
    post_id = this.post_ids[post_idx];
    overlay = this.container.down('.browser-thumb-hover-overlay');
    overlay.hide();
    overlay.down('IMG').src = Vars.asset['blank.gif'];
    this.expanded_post_idx = post_idx;
    if (post_idx == null) {
      return;
    }
    post = Post.posts.get(post_id);
    if (post.status === 'deleted') {
      return;
    }
    thumb = $('p' + post_idx);
    bottom = this.container.down('.browser-bottom-bar').offsetHeight;
    overlay.style.bottom = bottom + 'px';
    post_frame = this.post_frames[post_idx];
    image_width = void 0;
    image_url = void 0;
    if (post_frame !== -1) {
      frame = post.frames[post_frame];
      image_width = frame.preview_width;
      image_url = frame.preview_url;
    } else {
      image_width = post.actual_preview_width;
      image_url = post.preview_url;
    }
    left = thumb.cumulativeOffset().left - (image_width / 2) + thumb.offsetWidth / 2;
    overlay.style.left = left + 'px';
    // If the hover thumbnail overflows the right edge of the viewport, it'll extend the document and
    // allow scrolling to the right, which we don't want.  overflow: hidden doesn't fix this, since this
    // element is absolutely positioned.  Set the max-width to clip the right side of the thumbnail if
    // necessary.
    max_width = document.viewport.getDimensions().width - left;
    overlay.style.maxWidth = max_width + 'px';
    overlay.href = '/post/browse#' + post.id + this.view.post_frame_hash(post, post_frame);
    overlay.down('IMG').src = image_url;
    overlay.show();
  }

  create_thumb(post_idx) {
    var div, img, item, post, post_frame, post_id, url;
    post_id = this.post_ids[post_idx];
    post_frame = this.post_frames[post_idx];
    post = Post.posts.get(post_id);
    // Reuse thumbnail blocks that are no longer in use, to avoid WebKit memory leaks: it
    // doesn't like creating and deleting lots of images (or blocks with images inside them).

    // Thumbnails are hidden until they're loaded, so we don't show ugly load-borders.  This
    // also keeps us from showing old thumbnails before the new image is loaded.  Use visibility:
    // hidden, not display: none, or the size of the image won't be defined, which breaks
    // center_on_post.
    if (this.unused_thumb_pool.length === 0) {
      div = '<div class="inner">' + '<a class="thumb" tabindex="-1">' + '<img alt="" class="preview" onload="this.style.visibility = \'visible\';">' + '</a>' + '</div>';
      item = $(document.createElement('li'));
      item.innerHTML = div;
      item.className = 'post-thumb';
    } else {
      item = this.unused_thumb_pool.pop();
    }
    item.id = 'p' + post_idx;
    item.post_idx = post_idx;
    item.down('A').href = '/post/browse#' + post.id + this.view.post_frame_hash(post, post_frame);
    // If the image is already what we want, then leave it alone.  Setting it to what it's
    // already set to won't necessarily cause onload to be fired, so it'll never be set
    // back to visible.
    img = item.down('IMG');
    url = void 0;
    if (post_frame !== -1) {
      url = post.frames[post_frame].preview_url;
    } else {
      url = post.preview_url;
    }
    if (img.src !== url) {
      img.style.visibility = 'hidden';
      img.src = url;
    }
    this.set_thumb_dimensions(item);
    return item;
  }

  set_thumb_dimensions(li) {
    var block_size, crop_left, frame, height, img, inner, pad_top, post, post_frame, post_id, post_idx, width;
    post_idx = li.post_idx;
    post_id = this.post_ids[post_idx];
    post_frame = this.post_frames[post_idx];
    post = Post.posts.get(post_id);
    width = void 0;
    height = void 0;
    if (post_frame !== -1) {
      frame = post.frames[post_frame];
      width = frame.preview_width;
      height = frame.preview_height;
    } else {
      width = post.actual_preview_width;
      height = post.actual_preview_height;
    }
    width *= this.config.thumb_scale;
    height *= this.config.thumb_scale;
    // This crops blocks that are too wide, but doesn't pad them if they're too
    // narrow, since that creates odd spacing.

    // If the height of this block is changed, adjust .post-browser-posts-container in
    // config_changed.
    block_size = [Math.min(width, 200 * this.config.thumb_scale), 200 * this.config.thumb_scale];
    crop_left = Math.round((width - block_size[0]) / 2);
    pad_top = Math.max(0, block_size[1] - height);
    inner = li.down('.inner');
    inner.actual_width = block_size[0];
    inner.actual_height = block_size[1];
    inner.setStyle({
      width: block_size[0] + 'px',
      height: block_size[1] + 'px'
    });
    img = inner.down('img');
    img.width = width;
    img.height = height;
    img.setStyle({
      marginTop: pad_top + 'px',
      marginLeft: -crop_left + 'px'
    });
  }

  config_changed() {
    var container_height;
    // Adjust the size of the container to fit the thumbs at the current scale.  They're the
    // height of the thumb block, plus ten pixels for padding at the top and bottom.
    container_height = 200 * this.config.thumb_scale + 10;
    this.container.down('.post-browser-posts-container').setStyle({
      height: container_height + 'px'
    });
    this.container.select('LI.post-thumb').each(this.set_thumb_dimensions);
    this.center_on_post_for_scroll(this.centered_post_idx);
  }

  container_click_event(event) {
    var li;
    // Ignore the click if it was stopped by the DragElement.
    if (event.stopped) {
      return;
    }
    if ($(event.target).up('.browser-thumb-hover-overlay')) {
      // The hover overlay was clicked.  When the user clicks a thumbnail, this is
      // usually what happens, since the hover overlay covers the actual thumbnail.
      this.set_active_post_idx(this.expanded_post_idx);
      event.preventDefault();
      return;
    }
    li = $(event.target).up('.post-thumb');
    if (li == null) {
      return;
    }
    // An actual thumbnail was clicked.  This can happen if we don't have the expanded
    // thumbnails for some reason.
    event.preventDefault();
    this.set_active_post_idx(li.post_idx);
  }

  container_dblclick_event(event) {
    if (event.button) {
      return;
    }
    event.preventDefault();
    this.show_thumb_bar(false);
  }

  show_thumb_bar(shown) {
    if (this.thumb_container_shown === shown) {
      return;
    }
    this.thumb_container_shown = shown;
    this.container.show(shown);
    // If the centered post was changed while we were hidden, it wasn't applied by
    // center_on_post, so do it now.
    this.center_on_post_for_scroll(this.centered_post_idx);
    document.fire('viewer:thumb-bar-changed', {
      shown: this.thumb_container_shown,
      height: this.thumb_container_shown ? this.container.offsetHeight : 0
    });
  }

  // Return the next or previous post, wrapping around if necessary.
  get_adjacent_post_idx_wrapped(post_idx, next) {
    post_idx += next ? +1 : -1;
    post_idx = (post_idx + this.post_ids.length) % this.post_ids.length;
    return post_idx;
  }

  displayed_image_loaded_event(event) {
    var adjacent_post_idx, post_frame, post_id, post_ids_to_preload, post_idx;
    if (this.post_ids == null) {
      return;
    }
    post_id = event.memo.post_id;
    post_frame = event.memo.post_frame;
    post_idx = this.get_post_idx([post_id, post_frame]);
    if (post_idx == null) {
      return;
    }
    // The image in the post we're displaying is finished loading.

    // Preload the next and previous posts.  Normally, one or the other of these will
    // already be in cache.

    // Include the current post in the preloads, so if we switch from a frame back to
    // the main image, the frame itself will still be loaded.
    post_ids_to_preload = [];
    post_ids_to_preload.push([this.post_ids[post_idx], this.post_frames[post_idx]]);
    adjacent_post_idx = this.get_adjacent_post_idx_wrapped(post_idx, true);
    if (adjacent_post_idx != null) {
      post_ids_to_preload.push([this.post_ids[adjacent_post_idx], this.post_frames[adjacent_post_idx]]);
    }
    adjacent_post_idx = this.get_adjacent_post_idx_wrapped(post_idx, false);
    if (adjacent_post_idx != null) {
      post_ids_to_preload.push([this.post_ids[adjacent_post_idx], this.post_frames[adjacent_post_idx]]);
    }
    this.view.preload(post_ids_to_preload);
  }

};
