// Generated by CoffeeScript 2.7.0
import {
  removeImageElement
} from 'src/utils/image';

let $, ThumbnailUserImage;

$ = jQuery;

// file must be a Blob object.  Create and return a thumbnail of the image.
// Perform an image search using post/similar.

// On completion, onComplete(result) will be called, where result is an object with
// these properties:

// success: true or false.

// On failure:
// aborted: true if failure was due to a user abort.
// chromeFailure: If true, the image loaded but was empty.  Chrome probably ran out
// of memory, but the selected file may be a valid image.

// On success:
// canvas: On success, the canvas containing the thumbnailed image.

export default ThumbnailUserImage = class ThumbnailUserImage {
  constructor (file, onComplete) {
    // When the image finishes loading after form_submit_event sets it, update the canvas
    // thumbnail from it.
    this.image_load_event = this.image_load_event.bind(this);
    this.image_abort_event = this.image_abort_event.bind(this);
    // This happens on normal errors, usually because the file isn't a supported image.
    this.image_error_event = this.image_error_event.bind(this);
    this.file = file;
    this.canvas = document.createElement('canvas');
    this.image = document.createElement('img');
    this.onComplete = onComplete;
    this.url = URL.createObjectURL(this.file);
    $(this.image).on('load', this.image_load_event).on('abort', this.image_abort_event).on('error', this.image_error_event);
    document.documentElement.addClassName('progress');
    this.image.src = this.url;
  }

  // Cancel any running request.  The onComplete callback will not be called.
  // The object must not be reused.
  destroy () {
    document.documentElement.removeClassName('progress');
    this.onComplete = null;
    $(this.image).off();
    this.image = removeImageElement(this.image);
    if (this.url != null) {
      URL.revokeObjectURL(this.url);
      this.url = null;
    }
  }

  completed (result) {
    if (this.onComplete) {
      this.onComplete(result);
    }
    this.destroy();
  }

  image_load_event (e) {
    let canvas, ctx, height, max_height, max_width, ratio, width;
    // Reduce the image size to thumbnail resolution.
    width = this.image.width;
    height = this.image.height;
    max_width = 128;
    max_height = 128;
    ratio = void 0;
    if (width > max_width) {
      ratio = max_width / width;
      height *= ratio;
      width *= ratio;
    }
    if (height > max_height) {
      ratio = max_height / height;
      height *= ratio;
      width *= ratio;
    }
    width = Math.round(width);
    height = Math.round(height);
    // Set the canvas to the image size we want.
    canvas = this.canvas;
    canvas.width = width;
    canvas.height = height;
    // Blit the image onto the canvas.
    ctx = canvas.getContext('2d');
    // Clear the canvas, so check_image_contents can check that the data was correctly loaded.
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(this.image, 0, 0, canvas.width, canvas.height);
    if (!this.check_image_contents()) {
      this.completed({
        success: false,
        chromeFailure: true
      });
      return;
    }
    this.completed({
      success: true,
      canvas: this.canvas
    });
  }

  // Work around a Chrome bug.  When very large images fail to load, we still get
  // onload and the image acts like a loaded, completely transparent image, instead
  // of firing onerror.  This makes it difficult to tell if the image actually loaded
  // or not.  Check that the image loaded by looking at the results; reject the image
  // if it's completely transparent.
  check_image_contents () {
    let ctx, data, idx, image, max_idx;
    ctx = this.canvas.getContext('2d');
    image = ctx.getImageData(0, 0, this.canvas.width, this.canvas.height);
    data = image.data;
    // Iterate through the alpha components, and search for any nonzero value.
    idx = 3;
    max_idx = image.width * image.height * 4;
    while (idx < max_idx) {
      if (data[idx] !== 0) {
        return true;
      }
      idx += 4;
    }
    return false;
  }

  image_abort_event (e) {
    this.completed({
      success: false,
      aborted: true
    });
  }

  image_error_event (e) {
    this.completed({
      success: false
    });
  }
};
