// Generated by CoffeeScript 2.7.0
let $, Timeago;

$ = jQuery;

export default Timeago = class Timeago {
  static set (el, date) {
    $(el).timeago('update', date);
    return Timeago.setTitle(el, date);
  }

  static setTitle (el, date) {
    return el.title = date.toString();
  }

  constructor () {
    this.run = this.run.bind(this);
    this.observe = this.observe.bind(this);
    this.onMutate = this.onMutate.bind(this);
    this.observe();
    this.run();
  }

  run (nodes = document.body) {
    return $(nodes).find('.js-timeago').addBack('.js-timeago').timeago().each((_i, el) => {
      return this.constructor.setTitle(el, new Date(el.getAttribute('datetime')));
    });
  }

  observe () {
    let config;
    this.observer = new MutationObserver(this.onMutate);
    config = {
      childList: true,
      subtree: true
    };
    return this.observer.observe(document, config);
  }

  onMutate (mutations) {
    let i, len, mutation, results;
    results = [];
    for (i = 0, len = mutations.length; i < len; i++) {
      mutation = mutations[i];
      results.push(this.run(mutation.addedNodes));
    }
    return results;
  }
};
