// Generated by CoffeeScript 2.7.0
import ThumbnailUserImage from './thumbnail_user_image';

import {
  hideEl,
  showEl
} from 'src/utils/dom';

let UploadSimilarSearch;

// When file_field is changed to an image, run an image search and put a summary in
// results.
export default UploadSimilarSearch = class UploadSimilarSearch {
  constructor (file_field, results) {
    this.field_changed_event = this.field_changed_event.bind(this);
    this.thumbnail_complete = this.thumbnail_complete.bind(this);
    this.file_field = file_field;
    this.results = results;
    this.file_field.addEventListener('change', this.field_changed_event);
  }

  field_changed_event (event) {
    let file, similar;
    if ((this.file_field.files == null) || this.file_field.files.length === 0) {
      hideEl(this.results);
      return;
    }
    this.results.innerHTML = 'Searching...';
    showEl(this.results);
    file = this.file_field.files[0];
    similar = new ThumbnailUserImage(file, this.thumbnail_complete);
  }

  thumbnail_complete (result) {
    if (!result.success) {
      this.results.innerHTML = 'Image load failed.';
      return;
    }
    return jQuery.ajax('/post/similar.json', {
      data: {
        url: result.canvas.toDataURL()
      },
      dataType: 'json',
      method: 'POST'
    }).done((json) => {
      let html, makeUrl, message, posts, remainingPosts, seeAll, shownPosts;
      if (json.posts.length > 0) {
        posts = [];
        shownPosts = 3;
        makeUrl = User.get_use_browser()
          ? (post) => {
              return `/post/browse#${post.id}`;
            }
          : (post) => {
              return `/post/show/${post.id}`;
            };
        posts = json.posts.slice(0, shownPosts).map((post) => {
          return `<a href='${makeUrl(post)}'>post #${post.id}</a>`;
        });
        seeAll = `<a href='/post/similar?search_id=${json.search_id}'>(see all)</a>`;
        html = `Similar posts ${seeAll}: ${posts.join(', ')}`;
        if (json.posts.length > shownPosts) {
          remainingPosts = json.posts.length - shownPosts;
          html += ` (${remainingPosts} more)`;
        }
        message = html;
      } else {
        message = 'No similar posts found.';
      }
      return this.results.innerHTML = message;
    }).fail((xhr) => {
      let ref, ref1;
      return this.results.innerHTML = (ref = (ref1 = xhr.responseJSON) != null ? ref1.reason : void 0) != null ? ref : 'unknown error';
    });
  }
};
