// Generated by CoffeeScript 2.7.0
var UrlHashHandler;

export default UrlHashHandler = class UrlHashHandler {
  constructor() {
    this.hashchange_event = this.hashchange_event.bind(this);
    this.observers = new Hash();
    this.normalize = function(h) {};
    this.denormalize = function(h) {};
    this.deferred_sets = [];
    this.deferred_replace = false;
    this.current_hash = this.parse(this.get_raw_hash());
    this.normalize(this.current_hash);
    // The last value received by the hashchange event:
    this.last_hashchange = this.current_hash.clone();
    Element.observe(window, 'hashchange', this.hashchange_event);
    return;
  }

  fire_observers(old_hash, new_hash) {
    var all_keys, changed_hash_keys, observers_to_call, universal_observers;
    all_keys = old_hash.keys();
    all_keys = all_keys.concat(new_hash.keys());
    all_keys = all_keys.uniq();
    changed_hash_keys = [];
    all_keys.each(function(key) {
      var new_value, old_value;
      old_value = old_hash.get(key);
      new_value = new_hash.get(key);
      if (old_value !== new_value) {
        changed_hash_keys.push(key);
      }
    });
    observers_to_call = [];
    changed_hash_keys.each((key) => {
      var observers;
      observers = this.observers.get(key);
      if (observers == null) {
        return;
      }
      observers_to_call = observers_to_call.concat(observers);
    });
    universal_observers = this.observers.get(null);
    if (universal_observers != null) {
      observers_to_call = observers_to_call.concat(universal_observers);
    }
    observers_to_call.each(function(observer) {
      observer(changed_hash_keys, old_hash, new_hash);
    });
  }

  // Set handlers to normalize and denormalize the URL hash.

  // Denormalizing a URL hash can convert the URL hash to something clearer for URLs.  Normalizing
  // it reverses any denormalization, giving names to parameters.

  // For example, if a normalized URL is

  // http://www.example.com/app#show?id=1

  // where the hash is {"": "show", id: "1"}, a denormalized URL may be

  // http://www.example.com/app#show/1

  // The denormalize callback will only be called with normalized input.  The normalize callback
  // may receive any combination of normalized or denormalized input.
  set_normalize(norm, denorm) {
    this.normalize = norm;
    this.denormalize = denorm;
    this.normalize(this.current_hash);
    this.set_all(this.current_hash.clone());
  }

  hashchange_event(event) {
    var new_hash, old_hash, raw;
    old_hash = this.last_hashchange.clone();
    this.normalize(old_hash);
    raw = this.get_raw_hash();
    new_hash = this.parse(raw);
    this.normalize(new_hash);
    this.current_hash = new_hash.clone();
    this.last_hashchange = new_hash.clone();
    this.fire_observers(old_hash, new_hash);
  }

  // Parse a hash, returning a Hash.

  // #a/b?c=d&e=f -> {"": 'a/b', c: 'd', e: 'f'}
  parse(hash) {
    var hash_path, hash_query, hash_query_values, i, key, keyval, query_params, value;
    if (hash == null) {
      hash = '';
    }
    if (hash.substr(0, 1) === '#') {
      hash = hash.substr(1);
    }
    hash_path = hash.split('?', 1)[0];
    hash_query = hash.substr(hash_path.length + 1);
    hash_path = window.decodeURIComponent(hash_path);
    query_params = new Hash();
    query_params.set('', hash_path);
    if (hash_query !== '') {
      hash_query_values = hash_query.split('&');
      i = 0;
      while (i < hash_query_values.length) {
        keyval = hash_query_values[i];
        // a=b
        key = keyval.split('=', 1)[0];
        // If the key is blank, eg. "#path?a=b&=d", then ignore the value.  It'll overwrite
        // the path, which is confusing and never what's wanted.
        if (key === '') {
          ++i;
          continue;
        }
        value = keyval.substr(key.length + 1);
        key = window.decodeURIComponent(key);
        value = window.decodeURIComponent(value);
        query_params.set(key, value);
        ++i;
      }
    }
    return query_params;
  }

  construct(hash) {
    var params, path, s;
    s = '#';
    path = hash.get('');
    if (path != null) {
      // For the path portion, we only need to escape the params separator ? and the escape
      // character % itself.  Don't use encodeURIComponent; it'll encode far more than necessary.
      path = path.replace(/%/g, '%25').replace(/\?/g, '%3f');
      s += path;
    }
    params = [];
    hash.each(function(k) {
      var key, value;
      key = k[0];
      value = k[1];
      if (key === '') {
        return;
      }
      if (value == null) {
        return;
      }
      key = window.encodeURIComponent(key);
      value = window.encodeURIComponent(value);
      params.push(key + '=' + value);
    });
    if (params.length !== 0) {
      s += '?' + params.join('&');
    }
    return s;
  }

  get_raw_hash() {
    return window.location.hash.slice(1);
  }

  set_raw_hash(hash) {
    var query_params;
    query_params = this.parse(hash);
    this.set_all(query_params);
  }

  get(key) {
    return this.current_hash.get(key);
  }

  // Set keys in the URL hash.

  // UrlHash.set({id: 50});

  // If replace is true and the History API is available, replace the state instead
  // of pushing it.
  set(hash, replace) {
    var new_hash;
    new_hash = this.current_hash.merge(hash);
    this.normalize(new_hash);
    this.set_all(new_hash, replace);
  }

  // Each call to UrlHash.set() will immediately set the new hash, which will create a new
  // browser history slot.  This isn't always wanted.  When several changes are being made
  // in response to a single action, all changes should be made simultaeously, so only a
  // single history slot is created.  Making only a single call to set() is difficult when
  // these changes are made by unrelated parts of code.

  // Defer changes to the URL hash.  If several calls are made in quick succession, buffer
  // the changes.  When a short timer expires, make all changes at once.  This will never
  // happen before the current Javascript call completes, because timers will never interrupt
  // running code.

  // UrlHash.set() doesn't do this, because set() guarantees that the hashchange event will
  // be fired and complete before the function returns.

  // If replace is true and the History API is available, replace the state instead of pushing
  // it.  If any set_deferred call consolidated into a single update has replace = false, the
  // new state will be pushed.
  set_deferred(hash, replace) {
    var set;
    this.deferred_sets.push(hash);
    if (replace) {
      this.deferred_replace = true;
    }
    set = () => {
      var new_hash;
      this.deferred_set_timer = null;
      new_hash = this.current_hash;
      this.deferred_sets.each(function(m) {
        new_hash = new_hash.merge(m);
      });
      this.normalize(new_hash);
      this.set_all(new_hash, this.deferred_replace);
      this.deferred_sets = [];
      this.hashchange_event(null);
      this.deferred_replace = false;
    };
    if (this.deferred_set_timer == null) {
      this.deferred_set_timer = set.defer();
    }
  }

  set_all(query_params, replace) {
    var new_hash, url;
    query_params = query_params.clone();
    this.normalize(query_params);
    this.current_hash = query_params.clone();
    this.denormalize(query_params);
    new_hash = this.construct(query_params);
    if (window.location.hash !== new_hash) {
      // If the History API is available, use it to support URL replacement.  FF4.0's pushState
      // is broken; don't use it.
      if (window.history && window.history.replaceState && window.history.pushState && !navigator.userAgent.match('Firefox/[45].')) {
        url = window.location.protocol + '//' + window.location.host + window.location.pathname + new_hash;
        if (replace) {
          window.history.replaceState({}, window.title, url);
        } else {
          window.history.pushState({}, window.title, url);
        }
      } else {
        window.location.hash = new_hash;
      }
    }
    // Explicitly fire the hashchange event, so it's handled quickly even if the browser
    // doesn't support the event.  It's harmless if we get this event multiple times due
    // to the browser delivering it normally due to our change.
    this.hashchange_event(null);
  }

  // Observe changes to the specified key.  If key is null, watch for all changes.
  observe(key, func) {
    var observers;
    observers = this.observers.get(key);
    if (observers == null) {
      observers = [];
      this.observers.set(key, observers);
    }
    if (observers.indexOf(func) !== -1) {
      return;
    }
    observers.push(func);
  }

  stopObserving(key, func) {
    var observers;
    observers = this.observers.get(key);
    if (observers == null) {
      return;
    }
    observers = observers.without(func);
    this.observers.set(key, observers);
  }

};
