// Generated by CoffeeScript 2.7.0
var $, UserRecord;

$ = jQuery;

export default UserRecord = class UserRecord {
  constructor() {
    this.destroy = this.destroy.bind(this);
    this.onDestroy = this.onDestroy.bind(this);
    $(document).on('click', '.js-user-record-destroy', this.onDestroy);
  }

  destroy(id) {
    notice(`Deleting record #${id}`);
    return $.ajax({
      url: Moebooru.path('/user_record/destroy.json'),
      type: 'delete',
      data: {
        'id': id
      }
    }).done(function() {
      return notice('Record deleted');
    }).fail(function() {
      return notice('Access denied');
    });
  }

  onDestroy(e) {
    e.preventDefault();
    return this.destroy($(e.currentTarget).data('id'));
  }

};
