// Generated by CoffeeScript 2.7.0
// Update the window title when the display changes.
let WindowTitleHandler;

export default WindowTitleHandler = class WindowTitleHandler {
  constructor () {
    this.update = this.update.bind(this);
    this.searched_tags = '';
    this.post_id = null;
    this.post_frame = null;
    this.pool = null;
    document.on('viewer:searched-tags-changed', (e) => {
      let ref;
      this.searched_tags = (ref = e.memo.tags) != null ? ref : '';
      return this.update();
    });
    document.on('viewer:displayed-post-changed', (e) => {
      this.post_id = e.memo.post_id;
      this.post_frame = e.memo.post_id;
      return this.update();
    });
    document.on('viewer:displayed-pool-changed', (e) => {
      this.pool = e.memo.pool;
      return this.update();
    });
    this.update();
  }

  update () {
    let pool_post, post, sequence, title;
    if (this.pool) {
      post = Post.posts.get(this.post_id);
      title = this.pool.name.replace(/_/g, ' ');
      if (post != null ? post.pool_posts : void 0) {
        pool_post = post.pool_posts[this.pool.id];
        if (pool_post) {
          sequence = pool_post.sequence;
          title += ' ';
          if (sequence.match(/^[0-9]/)) {
            title += '#';
          }
          title += sequence;
        }
      }
    } else {
      title = `/${this.searched_tags.replace(/_/g, ' ')}`;
    }
    title += ' - Browse';
    return document.title = title;
  }
};
