// Generated by CoffeeScript 2.7.0
import DragElement from 'src/classes/drag_element';

let WindowDragElementAbsolute;

// element should be positioned (eg. position: absolute).  When the element is dragged,
// scroll it around.
export default WindowDragElementAbsolute = class WindowDragElementAbsolute {
  constructor (element, ondrag_callback) {
    this.startdrag = this.startdrag.bind(this);
    this.ondrag = this.ondrag.bind(this);
    this.element = element;
    this.ondrag_callback = ondrag_callback;
    this.disabled = false;
    this.dragger = new DragElement(element, {
      ondrag: this.ondrag,
      onstartdrag: this.startdrag
    });
  }

  set_disabled (b) {
    this.disabled = b;
  }

  startdrag () {
    if (this.disabled) {
      return true;
    }
    // cancel
    this.scroll_anchor_x = this.element.offsetLeft;
    this.scroll_anchor_y = this.element.offsetTop;
    return false;
  }

  ondrag (e) {
    let min_visible, scrollLeft, scrollTop;
    scrollLeft = this.scroll_anchor_x + e.aX;
    scrollTop = this.scroll_anchor_y + e.aY;
    // Don't allow dragging the image off the screen; there'll be no way to
    // get it back.
    min_visible = Math.min(100, this.element.offsetWidth);
    scrollLeft = Math.max(scrollLeft, min_visible - this.element.offsetWidth);
    scrollLeft = Math.min(scrollLeft, window.innerWidth - min_visible);
    min_visible = Math.min(100, this.element.offsetHeight);
    scrollTop = Math.max(scrollTop, min_visible - this.element.offsetHeight);
    scrollTop = Math.min(scrollTop, window.innerHeight - min_visible);
    this.element.setStyle({
      left: scrollLeft + 'px',
      top: scrollTop + 'px'
    });
    if (this.ondrag_callback) {
      this.ondrag_callback();
    }
  }

  destroy () {
    this.dragger.destroy();
  }
};
