#!/usr/bin/ruby

require 'rubygems'
require 'aws/s3'

home = File.expand_path("~")

if !File.exists?("#{home}/.s3/access_key")
  STDERR.puts "Access key not found"
  exit 1
end

if !File.exists?("#{home}/.s3/secret_access_key")
  STDERR.puts "Secret access key not found"
  exit 1
end

access_key = open("#{home}/.s3/access_key").read.strip
secret_access_key = open("#{home}/.s3/secret_access_key").read.strip

dump = `svnadmin dump /var/cache/svn`

AWS::S3::Base.establish_connection!(:access_key_id => access_key, :secret_access_key => secret_access_key)
AWS::S3::S3Object.store("svn-dump", dump, "danbooru-backup", :access => :private)
puts "Subversion repository uploaded as svn-dump"
