#!/bin/sh

script/donmai/downbooru
mongrel_rails cluster::stop
app/daemons/job_task_processor_ctl.rb stop
svn update
sleep 5
RAILS_ENV=production rake db:migrate
app/daemons/job_task_processor_ctl.rb start
mongrel_rails cluster::start
sleep 15
script/donmai/upbooru
